// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'app_persistent_state.freezed.dart';

@freezed
sealed class AppPersistentState with _$AppPersistentState {
  const AppPersistentState._();
  const factory AppPersistentState({
    bool? isAgreeAgreement,
    bool? isInitialStartup,
    String? lang,
    int? theme,
    required Map<String, String> unknownField,
  }) = _AppPersistentState;
  static AppPersistentState? fromJson({required String json}) => RustLib
      .instance
      .api
      .crateConfigAppPersistentStateAppPersistentStateFromJson(json: json);

  String toJson() => RustLib.instance.api
      .crateConfigAppPersistentStateAppPersistentStateToJson(that: this);

  String toJsonPretty() => RustLib.instance.api
      .crateConfigAppPersistentStateAppPersistentStateToJsonPretty(that: this);
}
