// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PlatformUpdateInfo {
  final int version;
  final String versionString;
  final String downloadLink;
  final Map<String, String> updateMessage;

  const PlatformUpdateInfo({
    required this.version,
    required this.versionString,
    required this.downloadLink,
    required this.updateMessage,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      versionString.hashCode ^
      downloadLink.hashCode ^
      updateMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlatformUpdateInfo &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          versionString == other.versionString &&
          downloadLink == other.downloadLink &&
          updateMessage == other.updateMessage;
}

class UpdateInfo {
  final PlatformUpdateInfo windows;
  final PlatformUpdateInfo macos;

  const UpdateInfo({required this.windows, required this.macos});

  static UpdateInfo? fromJson({required String json}) =>
      RustLib.instance.api.crateConfigUpdateUpdateInfoFromJson(json: json);

  String toJson() =>
      RustLib.instance.api.crateConfigUpdateUpdateInfoToJson(that: this);

  String toJsonPretty() =>
      RustLib.instance.api.crateConfigUpdateUpdateInfoToJsonPretty(that: this);

  @override
  int get hashCode => windows.hashCode ^ macos.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateInfo &&
          runtimeType == other.runtimeType &&
          windows == other.windows &&
          macos == other.macos;
}
