// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../thumbnail.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 生成 PNG 缩略图
///
/// # Arguments
/// * `png_bytes` - PNG 文件字节数据
/// * `target_width` - 目标宽度(None 表示按高度等比缩放)
/// * `target_height` - 目标高度(None 表示按宽度等比缩放)
///
/// # Returns
/// * `Ok(Thumbnail)` - 缩略图宽度、高度、RGBA 像素数据
/// * `Err(String)` - 错误信息
///
/// # 注意
/// - 如果 width 和 height 都指定，会保持原图比例进行 **Fit**(适应)缩放
/// - 如果都未指定，返回原图尺寸的 RGBA 数据
Future<Thumbnail> generateThumbnail({
  required List<int> pngBytes,
  int? targetWidth,
  int? targetHeight,
}) => RustLib.instance.api.crateThumbnailPngGenerateThumbnail(
  pngBytes: pngBytes,
  targetWidth: targetWidth,
  targetHeight: targetHeight,
);
