// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'model.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`

class Nuan5ClothDiySwatchColor {
  final double r;
  final double g;
  final double b;
  final double a;

  const Nuan5ClothDiySwatchColor({
    required this.r,
    required this.g,
    required this.b,
    required this.a,
  });

  @override
  int get hashCode => r.hashCode ^ g.hashCode ^ b.hashCode ^ a.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5ClothDiySwatchColor &&
          runtimeType == other.runtimeType &&
          r == other.r &&
          g == other.g &&
          b == other.b &&
          a == other.a;
}

class Nuan5ClothDyeArea {
  final int maxColorAreaNum;
  final int maxPatternAreaNum;
  final int maxPatternMaskNum;

  const Nuan5ClothDyeArea({
    required this.maxColorAreaNum,
    required this.maxPatternAreaNum,
    required this.maxPatternMaskNum,
  });

  @override
  int get hashCode =>
      maxColorAreaNum.hashCode ^
      maxPatternAreaNum.hashCode ^
      maxPatternMaskNum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5ClothDyeArea &&
          runtimeType == other.runtimeType &&
          maxColorAreaNum == other.maxColorAreaNum &&
          maxPatternAreaNum == other.maxPatternAreaNum &&
          maxPatternMaskNum == other.maxPatternMaskNum;
}

class Nuan5ClothDyePalette {
  final Int32List directly;
  final Int32List complete;
  final Int32List growUp;
  final Int32List evolution1;
  final Int32List evolution2;

  const Nuan5ClothDyePalette({
    required this.directly,
    required this.complete,
    required this.growUp,
    required this.evolution1,
    required this.evolution2,
  });

  @override
  int get hashCode =>
      directly.hashCode ^
      complete.hashCode ^
      growUp.hashCode ^
      evolution1.hashCode ^
      evolution2.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5ClothDyePalette &&
          runtimeType == other.runtimeType &&
          directly == other.directly &&
          complete == other.complete &&
          growUp == other.growUp &&
          evolution1 == other.evolution1 &&
          evolution2 == other.evolution2;
}

enum Nuan5DatabaseCategory {
  light,
  lightType,
  filter,
  filterType,
  momoPose,
  clothDyeArea,
  clothDyePalette,
  clothDiySwatchColor,
}

@freezed
sealed class Nuan5DatabaseItem with _$Nuan5DatabaseItem {
  const Nuan5DatabaseItem._();

  const factory Nuan5DatabaseItem.light(Nuan5Light field0) =
      Nuan5DatabaseItem_Light;
  const factory Nuan5DatabaseItem.lightType(Nuan5LightType field0) =
      Nuan5DatabaseItem_LightType;
  const factory Nuan5DatabaseItem.filter(Nuan5Filter field0) =
      Nuan5DatabaseItem_Filter;
  const factory Nuan5DatabaseItem.filterType(Nuan5FilterType field0) =
      Nuan5DatabaseItem_FilterType;
  const factory Nuan5DatabaseItem.momoPose(Nuan5MomoPose field0) =
      Nuan5DatabaseItem_MomoPose;
  const factory Nuan5DatabaseItem.clothDyeArea(Nuan5ClothDyeArea field0) =
      Nuan5DatabaseItem_ClothDyeArea;
  const factory Nuan5DatabaseItem.clothDyePalette(Nuan5ClothDyePalette field0) =
      Nuan5DatabaseItem_ClothDyePalette;
  const factory Nuan5DatabaseItem.clothDiySwatchColor(
    Nuan5ClothDiySwatchColor field0,
  ) = Nuan5DatabaseItem_ClothDiySwatchColor;
}

class Nuan5Filter {
  final String stringId;
  final String paramId;

  const Nuan5Filter({required this.stringId, required this.paramId});

  @override
  int get hashCode => stringId.hashCode ^ paramId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5Filter &&
          runtimeType == other.runtimeType &&
          stringId == other.stringId &&
          paramId == other.paramId;
}

class Nuan5FilterType {
  final Int32List filter;

  const Nuan5FilterType({required this.filter});

  @override
  int get hashCode => filter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5FilterType &&
          runtimeType == other.runtimeType &&
          filter == other.filter;
}

class Nuan5Light {
  final String stringId;
  final String paramId;

  const Nuan5Light({required this.stringId, required this.paramId});

  @override
  int get hashCode => stringId.hashCode ^ paramId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5Light &&
          runtimeType == other.runtimeType &&
          stringId == other.stringId &&
          paramId == other.paramId;
}

class Nuan5LightType {
  final Int32List light;

  const Nuan5LightType({required this.light});

  @override
  int get hashCode => light.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5LightType &&
          runtimeType == other.runtimeType &&
          light == other.light;
}

class Nuan5MomoPose {
  final String stringId;

  const Nuan5MomoPose({required this.stringId});

  @override
  int get hashCode => stringId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5MomoPose &&
          runtimeType == other.runtimeType &&
          stringId == other.stringId;
}
