// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clear`, `clear`, `clear`, `clear`, `clear`, `clear`, `clear`, `clear`, `clear`, `clear`, `clear`, `clear`, `clear`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `encode_raw`, `encode_raw`, `encode_raw`, `encode_raw`, `encode_raw`, `encode_raw`, `encode_raw`, `encode_raw`, `encode_raw`, `encode_raw`, `encode_raw`, `encode_raw`, `encode_raw`, `encoded_len`, `encoded_len`, `encoded_len`, `encoded_len`, `encoded_len`, `encoded_len`, `encoded_len`, `encoded_len`, `encoded_len`, `encoded_len`, `encoded_len`, `encoded_len`, `encoded_len`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `merge_field`, `merge_field`, `merge_field`, `merge_field`, `merge_field`, `merge_field`, `merge_field`, `merge_field`, `merge_field`, `merge_field`, `merge_field`, `merge_field`, `merge_field`

class Nuan5ClothDiySwatchColor {
  final Float64List rgba;

  const Nuan5ClothDiySwatchColor({required this.rgba});

  static Future<Nuan5ClothDiySwatchColor> default_() => RustLib.instance.api
      .crateNuan5DatabaseModelNuan5ClothDiySwatchColorDefault();

  @override
  int get hashCode => rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5ClothDiySwatchColor &&
          runtimeType == other.runtimeType &&
          rgba == other.rgba;
}

class Nuan5ClothDyeArea {
  final int maxColorAreaNum;
  final int maxPatternAreaNum;
  final int maxPatternMaskNum;
  final Int32List customAreaOrder;

  const Nuan5ClothDyeArea({
    required this.maxColorAreaNum,
    required this.maxPatternAreaNum,
    required this.maxPatternMaskNum,
    required this.customAreaOrder,
  });

  static Future<Nuan5ClothDyeArea> default_() =>
      RustLib.instance.api.crateNuan5DatabaseModelNuan5ClothDyeAreaDefault();

  @override
  int get hashCode =>
      maxColorAreaNum.hashCode ^
      maxPatternAreaNum.hashCode ^
      maxPatternMaskNum.hashCode ^
      customAreaOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5ClothDyeArea &&
          runtimeType == other.runtimeType &&
          maxColorAreaNum == other.maxColorAreaNum &&
          maxPatternAreaNum == other.maxPatternAreaNum &&
          maxPatternMaskNum == other.maxPatternMaskNum &&
          customAreaOrder == other.customAreaOrder;
}

class Nuan5ClothDyePalette {
  final Int32List directly;
  final Int32List complete;
  final Int32List growUp;
  final Int32List evolution1;
  final Int32List evolution2;

  const Nuan5ClothDyePalette({
    required this.directly,
    required this.complete,
    required this.growUp,
    required this.evolution1,
    required this.evolution2,
  });

  static Future<Nuan5ClothDyePalette> default_() =>
      RustLib.instance.api.crateNuan5DatabaseModelNuan5ClothDyePaletteDefault();

  @override
  int get hashCode =>
      directly.hashCode ^
      complete.hashCode ^
      growUp.hashCode ^
      evolution1.hashCode ^
      evolution2.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5ClothDyePalette &&
          runtimeType == other.runtimeType &&
          directly == other.directly &&
          complete == other.complete &&
          growUp == other.growUp &&
          evolution1 == other.evolution1 &&
          evolution2 == other.evolution2;
}

class Nuan5Config {
  final Nuan5Table? table;
  final Nuan5NetworkImage? networkImage;
  final Map<int, Nuan5Light> light;
  final Map<int, Nuan5LightType> lightType;
  final Map<int, Nuan5Filter> filter;
  final Map<int, Nuan5FilterType> filterType;
  final Map<int, Nuan5MomoPose> momoPose;
  final Map<int, Nuan5ClothDyeArea> clothDyeArea;
  final Map<int, Nuan5ClothDyePalette> clothDyePalette;
  final Map<int, Nuan5ClothDiySwatchColor> clothDiySwatchColor;

  const Nuan5Config({
    this.table,
    this.networkImage,
    required this.light,
    required this.lightType,
    required this.filter,
    required this.filterType,
    required this.momoPose,
    required this.clothDyeArea,
    required this.clothDyePalette,
    required this.clothDiySwatchColor,
  });

  static Future<Nuan5Config> default_() =>
      RustLib.instance.api.crateNuan5DatabaseModelNuan5ConfigDefault();

  static Future<Nuan5Config?> tryFrom({required String path}) => RustLib
      .instance
      .api
      .crateNuan5DatabaseModelNuan5ConfigTryFrom(path: path);

  @override
  int get hashCode =>
      table.hashCode ^
      networkImage.hashCode ^
      light.hashCode ^
      lightType.hashCode ^
      filter.hashCode ^
      filterType.hashCode ^
      momoPose.hashCode ^
      clothDyeArea.hashCode ^
      clothDyePalette.hashCode ^
      clothDiySwatchColor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5Config &&
          runtimeType == other.runtimeType &&
          table == other.table &&
          networkImage == other.networkImage &&
          light == other.light &&
          lightType == other.lightType &&
          filter == other.filter &&
          filterType == other.filterType &&
          momoPose == other.momoPose &&
          clothDyeArea == other.clothDyeArea &&
          clothDyePalette == other.clothDyePalette &&
          clothDiySwatchColor == other.clothDiySwatchColor;
}

class Nuan5DiyPattern {
  final String stringId;

  const Nuan5DiyPattern({required this.stringId});

  static Future<Nuan5DiyPattern> default_() =>
      RustLib.instance.api.crateNuan5DatabaseModelNuan5DiyPatternDefault();

  @override
  int get hashCode => stringId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5DiyPattern &&
          runtimeType == other.runtimeType &&
          stringId == other.stringId;
}

class Nuan5Filter {
  final String stringId;
  final String paramId;

  const Nuan5Filter({required this.stringId, required this.paramId});

  static Future<Nuan5Filter> default_() =>
      RustLib.instance.api.crateNuan5DatabaseModelNuan5FilterDefault();

  @override
  int get hashCode => stringId.hashCode ^ paramId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5Filter &&
          runtimeType == other.runtimeType &&
          stringId == other.stringId &&
          paramId == other.paramId;
}

class Nuan5FilterType {
  final Int32List filter;

  const Nuan5FilterType({required this.filter});

  static Future<Nuan5FilterType> default_() =>
      RustLib.instance.api.crateNuan5DatabaseModelNuan5FilterTypeDefault();

  @override
  int get hashCode => filter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5FilterType &&
          runtimeType == other.runtimeType &&
          filter == other.filter;
}

class Nuan5Light {
  final String stringId;
  final String paramId;

  const Nuan5Light({required this.stringId, required this.paramId});

  static Future<Nuan5Light> default_() =>
      RustLib.instance.api.crateNuan5DatabaseModelNuan5LightDefault();

  @override
  int get hashCode => stringId.hashCode ^ paramId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5Light &&
          runtimeType == other.runtimeType &&
          stringId == other.stringId &&
          paramId == other.paramId;
}

class Nuan5LightType {
  final Int32List light;

  const Nuan5LightType({required this.light});

  static Future<Nuan5LightType> default_() =>
      RustLib.instance.api.crateNuan5DatabaseModelNuan5LightTypeDefault();

  @override
  int get hashCode => light.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5LightType &&
          runtimeType == other.runtimeType &&
          light == other.light;
}

class Nuan5MomoPose {
  final String stringId;

  const Nuan5MomoPose({required this.stringId});

  static Future<Nuan5MomoPose> default_() =>
      RustLib.instance.api.crateNuan5DatabaseModelNuan5MomoPoseDefault();

  @override
  int get hashCode => stringId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5MomoPose &&
          runtimeType == other.runtimeType &&
          stringId == other.stringId;
}

class Nuan5NetworkImage {
  final Nuan5NetworkImageItem? light;
  final Nuan5NetworkImageItem? filter;
  final Nuan5NetworkImageItem? momoPose;
  final Nuan5NetworkImageItem? cloth;
  final Nuan5NetworkImageItem? clothOutfit;
  final Nuan5NetworkImageItem? diyPattern;

  const Nuan5NetworkImage({
    this.light,
    this.filter,
    this.momoPose,
    this.cloth,
    this.clothOutfit,
    this.diyPattern,
  });

  static Future<Nuan5NetworkImage> default_() =>
      RustLib.instance.api.crateNuan5DatabaseModelNuan5NetworkImageDefault();

  @override
  int get hashCode =>
      light.hashCode ^
      filter.hashCode ^
      momoPose.hashCode ^
      cloth.hashCode ^
      clothOutfit.hashCode ^
      diyPattern.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5NetworkImage &&
          runtimeType == other.runtimeType &&
          light == other.light &&
          filter == other.filter &&
          momoPose == other.momoPose &&
          cloth == other.cloth &&
          clothOutfit == other.clothOutfit &&
          diyPattern == other.diyPattern;
}

class Nuan5NetworkImageItem {
  final String baseUrl;
  final String replace;

  const Nuan5NetworkImageItem({required this.baseUrl, required this.replace});

  static Future<Nuan5NetworkImageItem> default_() => RustLib.instance.api
      .crateNuan5DatabaseModelNuan5NetworkImageItemDefault();

  @override
  int get hashCode => baseUrl.hashCode ^ replace.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5NetworkImageItem &&
          runtimeType == other.runtimeType &&
          baseUrl == other.baseUrl &&
          replace == other.replace;
}

class Nuan5Table {
  final Int32List lightType;
  final Int32List filterType;
  final Int32List momoPose;

  const Nuan5Table({
    required this.lightType,
    required this.filterType,
    required this.momoPose,
  });

  static Future<Nuan5Table> default_() =>
      RustLib.instance.api.crateNuan5DatabaseModelNuan5TableDefault();

  @override
  int get hashCode =>
      lightType.hashCode ^ filterType.hashCode ^ momoPose.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Nuan5Table &&
          runtimeType == other.runtimeType &&
          lightType == other.lightType &&
          filterType == other.filterType &&
          momoPose == other.momoPose;
}
