// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Nuan5Database`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `close`, `get`, `has`, `is_open`, `list`, `open`

abstract class Nuan5DatabaseReader {
  Future<void> close();

  Future<Map<PlatformInt64, Nuan5DatabaseItem>> get_({
    required Nuan5DatabaseCategory category,
    required Int64List ids,
  });

  Future<bool> has({required Nuan5DatabaseCategory category});

  Future<bool> isOpen();

  Future<Int64List> list({
    required Nuan5DatabaseCategory category,
    required BigInt from,
    required PlatformInt64 max,
  });

  Future<bool> open({required String path});
}
