// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model.dart';
import 'nuan5_database.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decrypt`, `derive_key`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Nuan5DatabaseV1`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Nuan5DatabaseReaderV1>>
abstract class Nuan5DatabaseReaderV1
    implements RustOpaqueInterface, Nuan5DatabaseReader {
  @override
  Future<void> close();

  @override
  Future<Map<PlatformInt64, Nuan5DatabaseItem>> get_({
    required Nuan5DatabaseCategory category,
    required Int64List ids,
  });

  @override
  Future<bool> has({required Nuan5DatabaseCategory category});

  @override
  Future<bool> isOpen();

  @override
  Future<Int64List> list({
    required Nuan5DatabaseCategory category,
    required BigInt from,
    required PlatformInt64 max,
  });

  @override
  Future<bool> open({required String path});
}
