use crate::nuan5_params::nuan5_structs::camera_params;
use crate::nuan5_params::nuan5_structs::camera_params::{CameraParamsV1, CameraParamsV2, CameraParamsV2MomoHidden};
use crate::nuan5_params::unparser::camera_params_unparser::*;
use super::structs::{nikki_photo_params::*, camera_params::*};

pub(crate) fn revert_camera_params(data: &CameraParams) -> camera_params::CameraParams{
  match &data.momo{
    Some(camera_params_momo_hidden) => camera_params::CameraParams::V2(CameraParamsV2{
      flag: 0,
      portrait_mode: if data.portrait_mode { 1 } else { 0 },
      dx_camera_actor: data.camera_actor_loc.0,
      dy_camera_actor: data.camera_actor_loc.1,
      dz_camera_actor: data.camera_actor_loc.2,
      d_pitch_camera_actor: data.camera_actor_rot.1,
      d_yaw_camera_actor: data.camera_actor_rot.0,
      mode: 0,
      dx_camera_component: data.camera_component_loc.0,
      dy_camera_component: data.camera_actor_loc.1,
      dz_camera_component: data.camera_actor_loc.2,
      d_pitch_camera_component: data.camera_component_rot.1,
      d_yaw_camera_component: data.camera_component_rot.0,
      d_roll_camera_actor: data.camera_actor_rot.2,
      camera_focal_length: data.camera_focal_length,
      aperture_section: data.aperture_section,
      d_roll_camera_component: data.camera_component_rot.2,
      light_id: match &data.light{
        LightParams::Some{id, strength: _} => id.clone(),
        LightParams::None => String::from("None"),
      },
      light_strength: match &data.light{
        LightParams::Some{id: _, strength} => strength.clone(),
        LightParams::None => 0.5,
      },
      vignette_intensity: data.vignette_intensity,
      bloom_intensity: unparse_bloom_intensity(data.bloom_intensity),
      bloom_threshold: unparse_bloom_threshold(data.bloom_threshold),
      brightness: unparse_brightness(data.brightness),
      exposure: unparse_exposure(data.exposure),
      contrast: unparse_contrast(data.contrast),
      saturation: unparse_saturation(data.saturation),
      vibrance: unparse_vibrance(data.vibrance),
      highlights: unparse_highlights(data.highlights),
      shadows: unparse_shadows(data.shadows),
      filter_id: match &data.filter{
        FilterParams::Some{id, strength: _} => id.clone(),
        FilterParams::None => String::from("None"),
      },
      filter_strength: match &data.filter{
        FilterParams::Some{id: _, strength} => strength.clone(),
        FilterParams::None => 1.0,
      },
      momo: match camera_params_momo_hidden{
        CameraParamsMomoHidden::Disable{
          momo_pose,
          horizontal,
          distance,
          height,
          rotate_momo,
          auto_ground_snap,
          floating_effect,
          pose_with_nikki,
        } => CameraParamsV2MomoHidden::Disable{
          momo_pose: *momo_pose,
          horizontal: unparse_horizontal(*horizontal),
          distance: unparse_distance(*distance),
          height: unparse_height(*height),
          rotate_momo: unparse_rotate_momo(*rotate_momo),
          auto_ground_snap: if *auto_ground_snap { 1 } else { 0 },
          floating_effect: if *floating_effect { 1 } else { 0 },
          pose_with_nikki: if *pose_with_nikki { 1 } else { 0 },
        },
        CameraParamsMomoHidden::Enable => CameraParamsV2MomoHidden::Enable,
      },
    }),
    None => camera_params::CameraParams::V1(CameraParamsV1{
      flag: 0,
      portrait_mode: if data.portrait_mode { 1 } else { 0 },
      dx_camera_actor: data.camera_actor_loc.0,
      dy_camera_actor: data.camera_actor_loc.1,
      dz_camera_actor: data.camera_actor_loc.2,
      d_pitch_camera_actor: data.camera_actor_rot.1,
      d_yaw_camera_actor: data.camera_actor_rot.0,
      mode: 0,
      dx_camera_component: data.camera_component_loc.0,
      dy_camera_component: data.camera_actor_loc.1,
      dz_camera_component: data.camera_actor_loc.2,
      d_pitch_camera_component: data.camera_component_rot.1,
      d_yaw_camera_component: data.camera_component_rot.0,
      d_roll_camera_actor: data.camera_actor_rot.2,
      camera_focal_length: data.camera_focal_length,
      aperture_section: data.aperture_section,
      d_roll_camera_component: data.camera_component_rot.2,
      light_id: match &data.light{
        LightParams::Some{id, strength: _} => id.clone(),
        LightParams::None => String::from("None"),
      },
      light_strength: match &data.light{
        LightParams::Some{id: _, strength} => strength.clone(),
        LightParams::None => 0.5,
      },
      vignette_intensity: data.vignette_intensity,
      bloom_intensity: unparse_bloom_intensity(data.bloom_intensity),
      bloom_threshold: unparse_bloom_threshold(data.bloom_threshold),
      brightness: unparse_brightness(data.brightness),
      exposure: unparse_exposure(data.exposure),
      contrast: unparse_contrast(data.contrast),
      saturation: unparse_saturation(data.saturation),
      vibrance: unparse_vibrance(data.vibrance),
      highlights: unparse_highlights(data.highlights),
      shadows: unparse_shadows(data.shadows),
      filter_id: match &data.filter{
        FilterParams::Some{id, strength: _} => id.clone(),
        FilterParams::None => String::from("None"),
      },
      filter_strength: match &data.filter{
        FilterParams::Some{id: _, strength} => strength.clone(),
        FilterParams::None => 1.0,
      },
    }),
  }
}