// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'nuan5_database/model.dart';
import 'nuan5_database/nuan5_database.dart';
import 'nuan5_database/reader_v1.dart';
import 'nuan5_params/decode.dart';
import 'nuan5_params/decrypt.dart';
import 'nuan5_params/encode.dart';
import 'nuan5_params/encrypt.dart';
import 'nuan5_params/structs/building_params.dart';
import 'nuan5_params/structs/camera_params.dart';
import 'nuan5_params/structs/clock_in_photo_params.dart';
import 'nuan5_params/structs/cloth.dart';
import 'nuan5_params/structs/cloth_diy_params.dart';
import 'nuan5_params/structs/collage_params.dart';
import 'nuan5_params/structs/eureka.dart';
import 'nuan5_params/structs/nikki_photo_params.dart';
import 'nuan5_params/structs/world.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'serde_config/de.dart';
import 'serde_config/se.dart';
import 'serde_config/structs/common.dart';
import 'serde_config/structs/game_config.dart';
import 'serde_config/structs/plugin_info.dart';
import 'serde_config/structs/theme.dart';
import 'thumbnail.dart';
import 'thumbnail/jpeg.dart';
import 'thumbnail/mp4_h264.dart';
import 'thumbnail/png.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ClothDiyShareCodePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCodePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_HomeBuildShareCodePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCodePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MediaKeyPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKeyPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_Nuan5DatabaseReaderV1Ptr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1Ptr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ClothDiyShareCode
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode(
    dynamic raw,
  );

  @protected
  HomeBuildShareCode
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode(
    dynamic raw,
  );

  @protected
  MediaKey
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    dynamic raw,
  );

  @protected
  Nuan5DatabaseReaderV1
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1(
    dynamic raw,
  );

  @protected
  Nuan5DatabaseReaderV1
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1(
    dynamic raw,
  );

  @protected
  ClothDiyShareCode
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode(
    dynamic raw,
  );

  @protected
  HomeBuildShareCode
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode(
    dynamic raw,
  );

  @protected
  MediaKey
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    dynamic raw,
  );

  @protected
  Nuan5DatabaseReaderV1
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1(
    dynamic raw,
  );

  @protected
  Map<String, bool> dco_decode_Map_String_bool_None(dynamic raw);

  @protected
  Map<int, Nuan5DatabaseItem> dco_decode_Map_i_32_nuan_5_database_item_None(
    dynamic raw,
  );

  @protected
  Map<PlatformInt64, bool> dco_decode_Map_i_64_bool_None(dynamic raw);

  @protected
  Map<PlatformInt64, PlatformInt64> dco_decode_Map_i_64_i_64_None(dynamic raw);

  @protected
  ClothDiyShareCode
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode(
    dynamic raw,
  );

  @protected
  HomeBuildShareCode
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode(
    dynamic raw,
  );

  @protected
  MediaKey
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    dynamic raw,
  );

  @protected
  Nuan5DatabaseReaderV1
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1(
    dynamic raw,
  );

  @protected
  RustStreamSink<MediaCustomDataResult>
  dco_decode_StreamSink_media_custom_data_result_Sse(dynamic raw);

  @protected
  RustStreamSink<MediaDecodeEvent> dco_decode_StreamSink_media_decode_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<MediaStreamResult>
  dco_decode_StreamSink_media_stream_result_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Nuan5DatabaseReader dco_decode_TraitDef_Nuan5DatabaseReader(dynamic raw);

  @protected
  AndroidCustomGameConfig dco_decode_android_custom_game_config(dynamic raw);

  @protected
  AndroidGameConfig dco_decode_android_game_config(dynamic raw);

  @protected
  AndroidGameLocationConfig dco_decode_android_game_location_config(
    dynamic raw,
  );

  @protected
  AndroidGameSearcherConfig dco_decode_android_game_searcher_config(
    dynamic raw,
  );

  @protected
  Area dco_decode_area(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AndroidCustomGameConfig dco_decode_box_autoadd_android_custom_game_config(
    dynamic raw,
  );

  @protected
  AndroidGameConfig dco_decode_box_autoadd_android_game_config(dynamic raw);

  @protected
  Area dco_decode_box_autoadd_area(dynamic raw);

  @protected
  CameraParams dco_decode_box_autoadd_camera_params(dynamic raw);

  @protected
  CameraParamsMomoHidden dco_decode_box_autoadd_camera_params_momo_hidden(
    dynamic raw,
  );

  @protected
  ClockInPhotoParams dco_decode_box_autoadd_clock_in_photo_params(dynamic raw);

  @protected
  ClothDiyParam dco_decode_box_autoadd_cloth_diy_param(dynamic raw);

  @protected
  ClothDiyParams dco_decode_box_autoadd_cloth_diy_params(dynamic raw);

  @protected
  CollageParams dco_decode_box_autoadd_collage_params(dynamic raw);

  @protected
  CustomData dco_decode_box_autoadd_custom_data(dynamic raw);

  @protected
  Dimension dco_decode_box_autoadd_dimension(dynamic raw);

  @protected
  DiyData dco_decode_box_autoadd_diy_data(dynamic raw);

  @protected
  DyeColorParams dco_decode_box_autoadd_dye_color_params(dynamic raw);

  @protected
  EditPhotoParams dco_decode_box_autoadd_edit_photo_params(dynamic raw);

  @protected
  GameConfig dco_decode_box_autoadd_game_config(dynamic raw);

  @protected
  HomeBuildParam dco_decode_box_autoadd_home_build_param(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  Location dco_decode_box_autoadd_location(dynamic raw);

  @protected
  LocationParams dco_decode_box_autoadd_location_params(dynamic raw);

  @protected
  MacOSCustomGameConfig dco_decode_box_autoadd_mac_os_custom_game_config(
    dynamic raw,
  );

  @protected
  MacOSGameConfig dco_decode_box_autoadd_mac_os_game_config(dynamic raw);

  @protected
  MediaCustomData dco_decode_box_autoadd_media_custom_data(dynamic raw);

  @protected
  MediaParam dco_decode_box_autoadd_media_param(dynamic raw);

  @protected
  MomoHiddenState dco_decode_box_autoadd_momo_hidden_state(dynamic raw);

  @protected
  MomoParams dco_decode_box_autoadd_momo_params(dynamic raw);

  @protected
  Nation dco_decode_box_autoadd_nation(dynamic raw);

  @protected
  NikkiParams dco_decode_box_autoadd_nikki_params(dynamic raw);

  @protected
  NikkiPhotoParams dco_decode_box_autoadd_nikki_photo_params(dynamic raw);

  @protected
  Nuan5ClothDiySwatchColor dco_decode_box_autoadd_nuan_5_cloth_diy_swatch_color(
    dynamic raw,
  );

  @protected
  Nuan5ClothDyeArea dco_decode_box_autoadd_nuan_5_cloth_dye_area(dynamic raw);

  @protected
  Nuan5ClothDyePalette dco_decode_box_autoadd_nuan_5_cloth_dye_palette(
    dynamic raw,
  );

  @protected
  Nuan5Filter dco_decode_box_autoadd_nuan_5_filter(dynamic raw);

  @protected
  Nuan5FilterType dco_decode_box_autoadd_nuan_5_filter_type(dynamic raw);

  @protected
  Nuan5Light dco_decode_box_autoadd_nuan_5_light(dynamic raw);

  @protected
  Nuan5LightType dco_decode_box_autoadd_nuan_5_light_type(dynamic raw);

  @protected
  Nuan5MomoPose dco_decode_box_autoadd_nuan_5_momo_pose(dynamic raw);

  @protected
  ObjectParams dco_decode_box_autoadd_object_params(dynamic raw);

  @protected
  OrdinaryText dco_decode_box_autoadd_ordinary_text(dynamic raw);

  @protected
  OutfitDyeGeneralData dco_decode_box_autoadd_outfit_dye_general_data(
    dynamic raw,
  );

  @protected
  OutfitDyeHairData dco_decode_box_autoadd_outfit_dye_hair_data(dynamic raw);

  @protected
  PluginInfo dco_decode_box_autoadd_plugin_info(dynamic raw);

  @protected
  Region dco_decode_box_autoadd_region(dynamic raw);

  @protected
  RichBuildingParams dco_decode_box_autoadd_rich_building_params(dynamic raw);

  @protected
  RichCameraParams dco_decode_box_autoadd_rich_camera_params(dynamic raw);

  @protected
  RichCameraParamsMomoHidden
  dco_decode_box_autoadd_rich_camera_params_momo_hidden(dynamic raw);

  @protected
  ShootingDate dco_decode_box_autoadd_shooting_date(dynamic raw);

  @protected
  ShootingTime dco_decode_box_autoadd_shooting_time(dynamic raw);

  @protected
  Subarea dco_decode_box_autoadd_subarea(dynamic raw);

  @protected
  Text dco_decode_box_autoadd_text(dynamic raw);

  @protected
  ThemeConfigV1 dco_decode_box_autoadd_theme_config_v_1(dynamic raw);

  @protected
  ThemeConfigWrapper dco_decode_box_autoadd_theme_config_wrapper(dynamic raw);

  @protected
  TranslateText dco_decode_box_autoadd_translate_text(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  WeaponParams dco_decode_box_autoadd_weapon_params(dynamic raw);

  @protected
  WindowsCustomGameConfig dco_decode_box_autoadd_windows_custom_game_config(
    dynamic raw,
  );

  @protected
  WindowsGameConfig dco_decode_box_autoadd_windows_game_config(dynamic raw);

  @protected
  WindowsRegistryConfig dco_decode_box_autoadd_windows_registry_config(
    dynamic raw,
  );

  @protected
  CameraParams dco_decode_camera_params(dynamic raw);

  @protected
  CameraParamsMomoHidden dco_decode_camera_params_momo_hidden(dynamic raw);

  @protected
  ClockInPhotoParams dco_decode_clock_in_photo_params(dynamic raw);

  @protected
  Cloth dco_decode_cloth(dynamic raw);

  @protected
  ClothDiyParam dco_decode_cloth_diy_param(dynamic raw);

  @protected
  ClothDiyParamType dco_decode_cloth_diy_param_type(dynamic raw);

  @protected
  ClothDiyParams dco_decode_cloth_diy_params(dynamic raw);

  @protected
  ClothParams dco_decode_cloth_params(dynamic raw);

  @protected
  CollageParams dco_decode_collage_params(dynamic raw);

  @protected
  ColorRoleScheme dco_decode_color_role_scheme(dynamic raw);

  @protected
  ColorScheme dco_decode_color_scheme(dynamic raw);

  @protected
  ConfigFileType dco_decode_config_file_type(dynamic raw);

  @protected
  CustomData dco_decode_custom_data(dynamic raw);

  @protected
  DecryptionError dco_decode_decryption_error(dynamic raw);

  @protected
  Dimension dco_decode_dimension(dynamic raw);

  @protected
  DiyData dco_decode_diy_data(dynamic raw);

  @protected
  DiyHistoryShareCodeParams dco_decode_diy_history_share_code_params(
    dynamic raw,
  );

  @protected
  DressingParams dco_decode_dressing_params(dynamic raw);

  @protected
  DyeColorParams dco_decode_dye_color_params(dynamic raw);

  @protected
  EditPhotoParams dco_decode_edit_photo_params(dynamic raw);

  @protected
  EditPhotoState dco_decode_edit_photo_state(dynamic raw);

  @protected
  EncryptionError dco_decode_encryption_error(dynamic raw);

  @protected
  Eureka dco_decode_eureka(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FileEntityLocationConfig dco_decode_file_entity_location_config(dynamic raw);

  @protected
  FileEntityType dco_decode_file_entity_type(dynamic raw);

  @protected
  FilterParams dco_decode_filter_params(dynamic raw);

  @protected
  GameAlbumConfig dco_decode_game_album_config(dynamic raw);

  @protected
  GameConfig dco_decode_game_config(dynamic raw);

  @protected
  GameSelectorConfig dco_decode_game_selector_config(dynamic raw);

  @protected
  GameUidConfig dco_decode_game_uid_config(dynamic raw);

  @protected
  HomeBuildParam dco_decode_home_build_param(dynamic raw);

  @protected
  HomeBuildParamType dco_decode_home_build_param_type(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  LightParams dco_decode_light_params(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AndroidGameLocationConfig> dco_decode_list_android_game_location_config(
    dynamic raw,
  );

  @protected
  List<ClothParams> dco_decode_list_cloth_params(dynamic raw);

  @protected
  List<DiyHistoryShareCodeParams> dco_decode_list_diy_history_share_code_params(
    dynamic raw,
  );

  @protected
  List<Eureka> dco_decode_list_eureka(dynamic raw);

  @protected
  List<FileEntityLocationConfig> dco_decode_list_file_entity_location_config(
    dynamic raw,
  );

  @protected
  List<GameAlbumConfig> dco_decode_list_game_album_config(dynamic raw);

  @protected
  List<Location> dco_decode_list_location(dynamic raw);

  @protected
  List<MacOSGameLocationConfig> dco_decode_list_mac_os_game_location_config(
    dynamic raw,
  );

  @protected
  List<ObjectParams> dco_decode_list_object_params(dynamic raw);

  @protected
  List<CustomData?> dco_decode_list_opt_box_autoadd_custom_data(dynamic raw);

  @protected
  List<OutfitDyeData> dco_decode_list_outfit_dye_data(dynamic raw);

  @protected
  List<PatternCreationData> dco_decode_list_pattern_creation_data(dynamic raw);

  @protected
  List<Platform> dco_decode_list_platform(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_32_loose(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(int, Nuan5DatabaseItem)>
  dco_decode_list_record_i_32_nuan_5_database_item(dynamic raw);

  @protected
  List<(PlatformInt64, bool)> dco_decode_list_record_i_64_bool(dynamic raw);

  @protected
  List<(PlatformInt64, PlatformInt64)> dco_decode_list_record_i_64_i_64(
    dynamic raw,
  );

  @protected
  List<(String, bool)> dco_decode_list_record_string_bool(dynamic raw);

  @protected
  List<RegionPicture> dco_decode_list_region_picture(dynamic raw);

  @protected
  List<SpecialEffectData> dco_decode_list_special_effect_data(dynamic raw);

  @protected
  List<TaskParams> dco_decode_list_task_params(dynamic raw);

  @protected
  List<WindowsGameLocationConfig> dco_decode_list_windows_game_location_config(
    dynamic raw,
  );

  @protected
  List<WindowsGameSearcherConfig> dco_decode_list_windows_game_searcher_config(
    dynamic raw,
  );

  @protected
  Location dco_decode_location(dynamic raw);

  @protected
  LocationParams dco_decode_location_params(dynamic raw);

  @protected
  LocationType dco_decode_location_type(dynamic raw);

  @protected
  MacOSCustomGameConfig dco_decode_mac_os_custom_game_config(dynamic raw);

  @protected
  MacOSGameConfig dco_decode_mac_os_game_config(dynamic raw);

  @protected
  MacOSGameLocationConfig dco_decode_mac_os_game_location_config(dynamic raw);

  @protected
  MacOSGameSearcherConfig dco_decode_mac_os_game_searcher_config(dynamic raw);

  @protected
  MediaCustomData dco_decode_media_custom_data(dynamic raw);

  @protected
  MediaCustomDataResult dco_decode_media_custom_data_result(dynamic raw);

  @protected
  MediaDecodeEvent dco_decode_media_decode_event(dynamic raw);

  @protected
  MediaParam dco_decode_media_param(dynamic raw);

  @protected
  MediaParamType dco_decode_media_param_type(dynamic raw);

  @protected
  MediaStreamResult dco_decode_media_stream_result(dynamic raw);

  @protected
  MomoHiddenState dco_decode_momo_hidden_state(dynamic raw);

  @protected
  MomoParams dco_decode_momo_params(dynamic raw);

  @protected
  Nation dco_decode_nation(dynamic raw);

  @protected
  NikkiParams dco_decode_nikki_params(dynamic raw);

  @protected
  NikkiPhotoParams dco_decode_nikki_photo_params(dynamic raw);

  @protected
  Nuan5ClothDiySwatchColor dco_decode_nuan_5_cloth_diy_swatch_color(
    dynamic raw,
  );

  @protected
  Nuan5ClothDyeArea dco_decode_nuan_5_cloth_dye_area(dynamic raw);

  @protected
  Nuan5ClothDyePalette dco_decode_nuan_5_cloth_dye_palette(dynamic raw);

  @protected
  Nuan5DatabaseCategory dco_decode_nuan_5_database_category(dynamic raw);

  @protected
  Nuan5DatabaseItem dco_decode_nuan_5_database_item(dynamic raw);

  @protected
  Nuan5Filter dco_decode_nuan_5_filter(dynamic raw);

  @protected
  Nuan5FilterType dco_decode_nuan_5_filter_type(dynamic raw);

  @protected
  Nuan5Light dco_decode_nuan_5_light(dynamic raw);

  @protected
  Nuan5LightType dco_decode_nuan_5_light_type(dynamic raw);

  @protected
  Nuan5MomoPose dco_decode_nuan_5_momo_pose(dynamic raw);

  @protected
  ObjectParams dco_decode_object_params(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AndroidCustomGameConfig?
  dco_decode_opt_box_autoadd_android_custom_game_config(dynamic raw);

  @protected
  AndroidGameConfig? dco_decode_opt_box_autoadd_android_game_config(
    dynamic raw,
  );

  @protected
  Area? dco_decode_opt_box_autoadd_area(dynamic raw);

  @protected
  CameraParamsMomoHidden? dco_decode_opt_box_autoadd_camera_params_momo_hidden(
    dynamic raw,
  );

  @protected
  ClothDiyParam? dco_decode_opt_box_autoadd_cloth_diy_param(dynamic raw);

  @protected
  CustomData? dco_decode_opt_box_autoadd_custom_data(dynamic raw);

  @protected
  Dimension? dco_decode_opt_box_autoadd_dimension(dynamic raw);

  @protected
  DiyData? dco_decode_opt_box_autoadd_diy_data(dynamic raw);

  @protected
  DyeColorParams? dco_decode_opt_box_autoadd_dye_color_params(dynamic raw);

  @protected
  HomeBuildParam? dco_decode_opt_box_autoadd_home_build_param(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  LocationParams? dco_decode_opt_box_autoadd_location_params(dynamic raw);

  @protected
  MacOSCustomGameConfig? dco_decode_opt_box_autoadd_mac_os_custom_game_config(
    dynamic raw,
  );

  @protected
  MacOSGameConfig? dco_decode_opt_box_autoadd_mac_os_game_config(dynamic raw);

  @protected
  MediaCustomData? dco_decode_opt_box_autoadd_media_custom_data(dynamic raw);

  @protected
  MomoHiddenState? dco_decode_opt_box_autoadd_momo_hidden_state(dynamic raw);

  @protected
  Nation? dco_decode_opt_box_autoadd_nation(dynamic raw);

  @protected
  NikkiParams? dco_decode_opt_box_autoadd_nikki_params(dynamic raw);

  @protected
  ObjectParams? dco_decode_opt_box_autoadd_object_params(dynamic raw);

  @protected
  Region? dco_decode_opt_box_autoadd_region(dynamic raw);

  @protected
  RichCameraParams? dco_decode_opt_box_autoadd_rich_camera_params(dynamic raw);

  @protected
  RichCameraParamsMomoHidden?
  dco_decode_opt_box_autoadd_rich_camera_params_momo_hidden(dynamic raw);

  @protected
  ShootingDate? dco_decode_opt_box_autoadd_shooting_date(dynamic raw);

  @protected
  ShootingTime? dco_decode_opt_box_autoadd_shooting_time(dynamic raw);

  @protected
  Subarea? dco_decode_opt_box_autoadd_subarea(dynamic raw);

  @protected
  Text? dco_decode_opt_box_autoadd_text(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  WeaponParams? dco_decode_opt_box_autoadd_weapon_params(dynamic raw);

  @protected
  WindowsCustomGameConfig?
  dco_decode_opt_box_autoadd_windows_custom_game_config(dynamic raw);

  @protected
  WindowsGameConfig? dco_decode_opt_box_autoadd_windows_game_config(
    dynamic raw,
  );

  @protected
  WindowsRegistryConfig? dco_decode_opt_box_autoadd_windows_registry_config(
    dynamic raw,
  );

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  List<FileEntityLocationConfig>?
  dco_decode_opt_list_file_entity_location_config(dynamic raw);

  @protected
  OrdinaryText dco_decode_ordinary_text(dynamic raw);

  @protected
  OutfitDyeData dco_decode_outfit_dye_data(dynamic raw);

  @protected
  OutfitDyeGeneralData dco_decode_outfit_dye_general_data(dynamic raw);

  @protected
  OutfitDyeHairData dco_decode_outfit_dye_hair_data(dynamic raw);

  @protected
  PatternCreationData dco_decode_pattern_creation_data(dynamic raw);

  @protected
  PhotographyParams dco_decode_photography_params(dynamic raw);

  @protected
  Platform dco_decode_platform(dynamic raw);

  @protected
  PluginInfo dco_decode_plugin_info(dynamic raw);

  @protected
  (double, double) dco_decode_record_f_64_f_64(dynamic raw);

  @protected
  (double, double, double) dco_decode_record_f_64_f_64_f_64(dynamic raw);

  @protected
  (double, double, double, double) dco_decode_record_f_64_f_64_f_64_f_64(
    dynamic raw,
  );

  @protected
  (int, Nuan5DatabaseItem) dco_decode_record_i_32_nuan_5_database_item(
    dynamic raw,
  );

  @protected
  (PlatformInt64, bool) dco_decode_record_i_64_bool(dynamic raw);

  @protected
  (PlatformInt64, PlatformInt64) dco_decode_record_i_64_i_64(dynamic raw);

  @protected
  (String, bool) dco_decode_record_string_bool(dynamic raw);

  @protected
  (int, int, int) dco_decode_record_u_8_u_8_u_8(dynamic raw);

  @protected
  Region dco_decode_region(dynamic raw);

  @protected
  RegionPicture dco_decode_region_picture(dynamic raw);

  @protected
  RichBuildingParams dco_decode_rich_building_params(dynamic raw);

  @protected
  RichCameraParams dco_decode_rich_camera_params(dynamic raw);

  @protected
  RichCameraParamsMomoHidden dco_decode_rich_camera_params_momo_hidden(
    dynamic raw,
  );

  @protected
  ShootingDate dco_decode_shooting_date(dynamic raw);

  @protected
  ShootingTime dco_decode_shooting_time(dynamic raw);

  @protected
  SpecialEffectData dco_decode_special_effect_data(dynamic raw);

  @protected
  Subarea dco_decode_subarea(dynamic raw);

  @protected
  TaskParams dco_decode_task_params(dynamic raw);

  @protected
  Text dco_decode_text(dynamic raw);

  @protected
  ThemeConfigV1 dco_decode_theme_config_v_1(dynamic raw);

  @protected
  ThemeConfigWrapper dco_decode_theme_config_wrapper(dynamic raw);

  @protected
  Thumbnail dco_decode_thumbnail(dynamic raw);

  @protected
  TranslateText dco_decode_translate_text(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WeaponParams dco_decode_weapon_params(dynamic raw);

  @protected
  WindowsCustomGameConfig dco_decode_windows_custom_game_config(dynamic raw);

  @protected
  WindowsGameConfig dco_decode_windows_game_config(dynamic raw);

  @protected
  WindowsGameLocationConfig dco_decode_windows_game_location_config(
    dynamic raw,
  );

  @protected
  WindowsGameSearcherConfig dco_decode_windows_game_searcher_config(
    dynamic raw,
  );

  @protected
  WindowsRegistryConfig dco_decode_windows_registry_config(dynamic raw);

  @protected
  WindowsRegistryHive dco_decode_windows_registry_hive(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ClothDiyShareCode
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode(
    SseDeserializer deserializer,
  );

  @protected
  HomeBuildShareCode
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode(
    SseDeserializer deserializer,
  );

  @protected
  MediaKey
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    SseDeserializer deserializer,
  );

  @protected
  Nuan5DatabaseReaderV1
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1(
    SseDeserializer deserializer,
  );

  @protected
  Nuan5DatabaseReaderV1
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1(
    SseDeserializer deserializer,
  );

  @protected
  ClothDiyShareCode
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode(
    SseDeserializer deserializer,
  );

  @protected
  HomeBuildShareCode
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode(
    SseDeserializer deserializer,
  );

  @protected
  MediaKey
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    SseDeserializer deserializer,
  );

  @protected
  Nuan5DatabaseReaderV1
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, bool> sse_decode_Map_String_bool_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<int, Nuan5DatabaseItem> sse_decode_Map_i_32_nuan_5_database_item_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<PlatformInt64, bool> sse_decode_Map_i_64_bool_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<PlatformInt64, PlatformInt64> sse_decode_Map_i_64_i_64_None(
    SseDeserializer deserializer,
  );

  @protected
  ClothDiyShareCode
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode(
    SseDeserializer deserializer,
  );

  @protected
  HomeBuildShareCode
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode(
    SseDeserializer deserializer,
  );

  @protected
  MediaKey
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    SseDeserializer deserializer,
  );

  @protected
  Nuan5DatabaseReaderV1
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MediaCustomDataResult>
  sse_decode_StreamSink_media_custom_data_result_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MediaDecodeEvent> sse_decode_StreamSink_media_decode_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MediaStreamResult>
  sse_decode_StreamSink_media_stream_result_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AndroidCustomGameConfig sse_decode_android_custom_game_config(
    SseDeserializer deserializer,
  );

  @protected
  AndroidGameConfig sse_decode_android_game_config(
    SseDeserializer deserializer,
  );

  @protected
  AndroidGameLocationConfig sse_decode_android_game_location_config(
    SseDeserializer deserializer,
  );

  @protected
  AndroidGameSearcherConfig sse_decode_android_game_searcher_config(
    SseDeserializer deserializer,
  );

  @protected
  Area sse_decode_area(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AndroidCustomGameConfig sse_decode_box_autoadd_android_custom_game_config(
    SseDeserializer deserializer,
  );

  @protected
  AndroidGameConfig sse_decode_box_autoadd_android_game_config(
    SseDeserializer deserializer,
  );

  @protected
  Area sse_decode_box_autoadd_area(SseDeserializer deserializer);

  @protected
  CameraParams sse_decode_box_autoadd_camera_params(
    SseDeserializer deserializer,
  );

  @protected
  CameraParamsMomoHidden sse_decode_box_autoadd_camera_params_momo_hidden(
    SseDeserializer deserializer,
  );

  @protected
  ClockInPhotoParams sse_decode_box_autoadd_clock_in_photo_params(
    SseDeserializer deserializer,
  );

  @protected
  ClothDiyParam sse_decode_box_autoadd_cloth_diy_param(
    SseDeserializer deserializer,
  );

  @protected
  ClothDiyParams sse_decode_box_autoadd_cloth_diy_params(
    SseDeserializer deserializer,
  );

  @protected
  CollageParams sse_decode_box_autoadd_collage_params(
    SseDeserializer deserializer,
  );

  @protected
  CustomData sse_decode_box_autoadd_custom_data(SseDeserializer deserializer);

  @protected
  Dimension sse_decode_box_autoadd_dimension(SseDeserializer deserializer);

  @protected
  DiyData sse_decode_box_autoadd_diy_data(SseDeserializer deserializer);

  @protected
  DyeColorParams sse_decode_box_autoadd_dye_color_params(
    SseDeserializer deserializer,
  );

  @protected
  EditPhotoParams sse_decode_box_autoadd_edit_photo_params(
    SseDeserializer deserializer,
  );

  @protected
  GameConfig sse_decode_box_autoadd_game_config(SseDeserializer deserializer);

  @protected
  HomeBuildParam sse_decode_box_autoadd_home_build_param(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  Location sse_decode_box_autoadd_location(SseDeserializer deserializer);

  @protected
  LocationParams sse_decode_box_autoadd_location_params(
    SseDeserializer deserializer,
  );

  @protected
  MacOSCustomGameConfig sse_decode_box_autoadd_mac_os_custom_game_config(
    SseDeserializer deserializer,
  );

  @protected
  MacOSGameConfig sse_decode_box_autoadd_mac_os_game_config(
    SseDeserializer deserializer,
  );

  @protected
  MediaCustomData sse_decode_box_autoadd_media_custom_data(
    SseDeserializer deserializer,
  );

  @protected
  MediaParam sse_decode_box_autoadd_media_param(SseDeserializer deserializer);

  @protected
  MomoHiddenState sse_decode_box_autoadd_momo_hidden_state(
    SseDeserializer deserializer,
  );

  @protected
  MomoParams sse_decode_box_autoadd_momo_params(SseDeserializer deserializer);

  @protected
  Nation sse_decode_box_autoadd_nation(SseDeserializer deserializer);

  @protected
  NikkiParams sse_decode_box_autoadd_nikki_params(SseDeserializer deserializer);

  @protected
  NikkiPhotoParams sse_decode_box_autoadd_nikki_photo_params(
    SseDeserializer deserializer,
  );

  @protected
  Nuan5ClothDiySwatchColor sse_decode_box_autoadd_nuan_5_cloth_diy_swatch_color(
    SseDeserializer deserializer,
  );

  @protected
  Nuan5ClothDyeArea sse_decode_box_autoadd_nuan_5_cloth_dye_area(
    SseDeserializer deserializer,
  );

  @protected
  Nuan5ClothDyePalette sse_decode_box_autoadd_nuan_5_cloth_dye_palette(
    SseDeserializer deserializer,
  );

  @protected
  Nuan5Filter sse_decode_box_autoadd_nuan_5_filter(
    SseDeserializer deserializer,
  );

  @protected
  Nuan5FilterType sse_decode_box_autoadd_nuan_5_filter_type(
    SseDeserializer deserializer,
  );

  @protected
  Nuan5Light sse_decode_box_autoadd_nuan_5_light(SseDeserializer deserializer);

  @protected
  Nuan5LightType sse_decode_box_autoadd_nuan_5_light_type(
    SseDeserializer deserializer,
  );

  @protected
  Nuan5MomoPose sse_decode_box_autoadd_nuan_5_momo_pose(
    SseDeserializer deserializer,
  );

  @protected
  ObjectParams sse_decode_box_autoadd_object_params(
    SseDeserializer deserializer,
  );

  @protected
  OrdinaryText sse_decode_box_autoadd_ordinary_text(
    SseDeserializer deserializer,
  );

  @protected
  OutfitDyeGeneralData sse_decode_box_autoadd_outfit_dye_general_data(
    SseDeserializer deserializer,
  );

  @protected
  OutfitDyeHairData sse_decode_box_autoadd_outfit_dye_hair_data(
    SseDeserializer deserializer,
  );

  @protected
  PluginInfo sse_decode_box_autoadd_plugin_info(SseDeserializer deserializer);

  @protected
  Region sse_decode_box_autoadd_region(SseDeserializer deserializer);

  @protected
  RichBuildingParams sse_decode_box_autoadd_rich_building_params(
    SseDeserializer deserializer,
  );

  @protected
  RichCameraParams sse_decode_box_autoadd_rich_camera_params(
    SseDeserializer deserializer,
  );

  @protected
  RichCameraParamsMomoHidden
  sse_decode_box_autoadd_rich_camera_params_momo_hidden(
    SseDeserializer deserializer,
  );

  @protected
  ShootingDate sse_decode_box_autoadd_shooting_date(
    SseDeserializer deserializer,
  );

  @protected
  ShootingTime sse_decode_box_autoadd_shooting_time(
    SseDeserializer deserializer,
  );

  @protected
  Subarea sse_decode_box_autoadd_subarea(SseDeserializer deserializer);

  @protected
  Text sse_decode_box_autoadd_text(SseDeserializer deserializer);

  @protected
  ThemeConfigV1 sse_decode_box_autoadd_theme_config_v_1(
    SseDeserializer deserializer,
  );

  @protected
  ThemeConfigWrapper sse_decode_box_autoadd_theme_config_wrapper(
    SseDeserializer deserializer,
  );

  @protected
  TranslateText sse_decode_box_autoadd_translate_text(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WeaponParams sse_decode_box_autoadd_weapon_params(
    SseDeserializer deserializer,
  );

  @protected
  WindowsCustomGameConfig sse_decode_box_autoadd_windows_custom_game_config(
    SseDeserializer deserializer,
  );

  @protected
  WindowsGameConfig sse_decode_box_autoadd_windows_game_config(
    SseDeserializer deserializer,
  );

  @protected
  WindowsRegistryConfig sse_decode_box_autoadd_windows_registry_config(
    SseDeserializer deserializer,
  );

  @protected
  CameraParams sse_decode_camera_params(SseDeserializer deserializer);

  @protected
  CameraParamsMomoHidden sse_decode_camera_params_momo_hidden(
    SseDeserializer deserializer,
  );

  @protected
  ClockInPhotoParams sse_decode_clock_in_photo_params(
    SseDeserializer deserializer,
  );

  @protected
  Cloth sse_decode_cloth(SseDeserializer deserializer);

  @protected
  ClothDiyParam sse_decode_cloth_diy_param(SseDeserializer deserializer);

  @protected
  ClothDiyParamType sse_decode_cloth_diy_param_type(
    SseDeserializer deserializer,
  );

  @protected
  ClothDiyParams sse_decode_cloth_diy_params(SseDeserializer deserializer);

  @protected
  ClothParams sse_decode_cloth_params(SseDeserializer deserializer);

  @protected
  CollageParams sse_decode_collage_params(SseDeserializer deserializer);

  @protected
  ColorRoleScheme sse_decode_color_role_scheme(SseDeserializer deserializer);

  @protected
  ColorScheme sse_decode_color_scheme(SseDeserializer deserializer);

  @protected
  ConfigFileType sse_decode_config_file_type(SseDeserializer deserializer);

  @protected
  CustomData sse_decode_custom_data(SseDeserializer deserializer);

  @protected
  DecryptionError sse_decode_decryption_error(SseDeserializer deserializer);

  @protected
  Dimension sse_decode_dimension(SseDeserializer deserializer);

  @protected
  DiyData sse_decode_diy_data(SseDeserializer deserializer);

  @protected
  DiyHistoryShareCodeParams sse_decode_diy_history_share_code_params(
    SseDeserializer deserializer,
  );

  @protected
  DressingParams sse_decode_dressing_params(SseDeserializer deserializer);

  @protected
  DyeColorParams sse_decode_dye_color_params(SseDeserializer deserializer);

  @protected
  EditPhotoParams sse_decode_edit_photo_params(SseDeserializer deserializer);

  @protected
  EditPhotoState sse_decode_edit_photo_state(SseDeserializer deserializer);

  @protected
  EncryptionError sse_decode_encryption_error(SseDeserializer deserializer);

  @protected
  Eureka sse_decode_eureka(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FileEntityLocationConfig sse_decode_file_entity_location_config(
    SseDeserializer deserializer,
  );

  @protected
  FileEntityType sse_decode_file_entity_type(SseDeserializer deserializer);

  @protected
  FilterParams sse_decode_filter_params(SseDeserializer deserializer);

  @protected
  GameAlbumConfig sse_decode_game_album_config(SseDeserializer deserializer);

  @protected
  GameConfig sse_decode_game_config(SseDeserializer deserializer);

  @protected
  GameSelectorConfig sse_decode_game_selector_config(
    SseDeserializer deserializer,
  );

  @protected
  GameUidConfig sse_decode_game_uid_config(SseDeserializer deserializer);

  @protected
  HomeBuildParam sse_decode_home_build_param(SseDeserializer deserializer);

  @protected
  HomeBuildParamType sse_decode_home_build_param_type(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  LightParams sse_decode_light_params(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AndroidGameLocationConfig> sse_decode_list_android_game_location_config(
    SseDeserializer deserializer,
  );

  @protected
  List<ClothParams> sse_decode_list_cloth_params(SseDeserializer deserializer);

  @protected
  List<DiyHistoryShareCodeParams> sse_decode_list_diy_history_share_code_params(
    SseDeserializer deserializer,
  );

  @protected
  List<Eureka> sse_decode_list_eureka(SseDeserializer deserializer);

  @protected
  List<FileEntityLocationConfig> sse_decode_list_file_entity_location_config(
    SseDeserializer deserializer,
  );

  @protected
  List<GameAlbumConfig> sse_decode_list_game_album_config(
    SseDeserializer deserializer,
  );

  @protected
  List<Location> sse_decode_list_location(SseDeserializer deserializer);

  @protected
  List<MacOSGameLocationConfig> sse_decode_list_mac_os_game_location_config(
    SseDeserializer deserializer,
  );

  @protected
  List<ObjectParams> sse_decode_list_object_params(
    SseDeserializer deserializer,
  );

  @protected
  List<CustomData?> sse_decode_list_opt_box_autoadd_custom_data(
    SseDeserializer deserializer,
  );

  @protected
  List<OutfitDyeData> sse_decode_list_outfit_dye_data(
    SseDeserializer deserializer,
  );

  @protected
  List<PatternCreationData> sse_decode_list_pattern_creation_data(
    SseDeserializer deserializer,
  );

  @protected
  List<Platform> sse_decode_list_platform(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_i_32_loose(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(int, Nuan5DatabaseItem)>
  sse_decode_list_record_i_32_nuan_5_database_item(
    SseDeserializer deserializer,
  );

  @protected
  List<(PlatformInt64, bool)> sse_decode_list_record_i_64_bool(
    SseDeserializer deserializer,
  );

  @protected
  List<(PlatformInt64, PlatformInt64)> sse_decode_list_record_i_64_i_64(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, bool)> sse_decode_list_record_string_bool(
    SseDeserializer deserializer,
  );

  @protected
  List<RegionPicture> sse_decode_list_region_picture(
    SseDeserializer deserializer,
  );

  @protected
  List<SpecialEffectData> sse_decode_list_special_effect_data(
    SseDeserializer deserializer,
  );

  @protected
  List<TaskParams> sse_decode_list_task_params(SseDeserializer deserializer);

  @protected
  List<WindowsGameLocationConfig> sse_decode_list_windows_game_location_config(
    SseDeserializer deserializer,
  );

  @protected
  List<WindowsGameSearcherConfig> sse_decode_list_windows_game_searcher_config(
    SseDeserializer deserializer,
  );

  @protected
  Location sse_decode_location(SseDeserializer deserializer);

  @protected
  LocationParams sse_decode_location_params(SseDeserializer deserializer);

  @protected
  LocationType sse_decode_location_type(SseDeserializer deserializer);

  @protected
  MacOSCustomGameConfig sse_decode_mac_os_custom_game_config(
    SseDeserializer deserializer,
  );

  @protected
  MacOSGameConfig sse_decode_mac_os_game_config(SseDeserializer deserializer);

  @protected
  MacOSGameLocationConfig sse_decode_mac_os_game_location_config(
    SseDeserializer deserializer,
  );

  @protected
  MacOSGameSearcherConfig sse_decode_mac_os_game_searcher_config(
    SseDeserializer deserializer,
  );

  @protected
  MediaCustomData sse_decode_media_custom_data(SseDeserializer deserializer);

  @protected
  MediaCustomDataResult sse_decode_media_custom_data_result(
    SseDeserializer deserializer,
  );

  @protected
  MediaDecodeEvent sse_decode_media_decode_event(SseDeserializer deserializer);

  @protected
  MediaParam sse_decode_media_param(SseDeserializer deserializer);

  @protected
  MediaParamType sse_decode_media_param_type(SseDeserializer deserializer);

  @protected
  MediaStreamResult sse_decode_media_stream_result(
    SseDeserializer deserializer,
  );

  @protected
  MomoHiddenState sse_decode_momo_hidden_state(SseDeserializer deserializer);

  @protected
  MomoParams sse_decode_momo_params(SseDeserializer deserializer);

  @protected
  Nation sse_decode_nation(SseDeserializer deserializer);

  @protected
  NikkiParams sse_decode_nikki_params(SseDeserializer deserializer);

  @protected
  NikkiPhotoParams sse_decode_nikki_photo_params(SseDeserializer deserializer);

  @protected
  Nuan5ClothDiySwatchColor sse_decode_nuan_5_cloth_diy_swatch_color(
    SseDeserializer deserializer,
  );

  @protected
  Nuan5ClothDyeArea sse_decode_nuan_5_cloth_dye_area(
    SseDeserializer deserializer,
  );

  @protected
  Nuan5ClothDyePalette sse_decode_nuan_5_cloth_dye_palette(
    SseDeserializer deserializer,
  );

  @protected
  Nuan5DatabaseCategory sse_decode_nuan_5_database_category(
    SseDeserializer deserializer,
  );

  @protected
  Nuan5DatabaseItem sse_decode_nuan_5_database_item(
    SseDeserializer deserializer,
  );

  @protected
  Nuan5Filter sse_decode_nuan_5_filter(SseDeserializer deserializer);

  @protected
  Nuan5FilterType sse_decode_nuan_5_filter_type(SseDeserializer deserializer);

  @protected
  Nuan5Light sse_decode_nuan_5_light(SseDeserializer deserializer);

  @protected
  Nuan5LightType sse_decode_nuan_5_light_type(SseDeserializer deserializer);

  @protected
  Nuan5MomoPose sse_decode_nuan_5_momo_pose(SseDeserializer deserializer);

  @protected
  ObjectParams sse_decode_object_params(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AndroidCustomGameConfig?
  sse_decode_opt_box_autoadd_android_custom_game_config(
    SseDeserializer deserializer,
  );

  @protected
  AndroidGameConfig? sse_decode_opt_box_autoadd_android_game_config(
    SseDeserializer deserializer,
  );

  @protected
  Area? sse_decode_opt_box_autoadd_area(SseDeserializer deserializer);

  @protected
  CameraParamsMomoHidden? sse_decode_opt_box_autoadd_camera_params_momo_hidden(
    SseDeserializer deserializer,
  );

  @protected
  ClothDiyParam? sse_decode_opt_box_autoadd_cloth_diy_param(
    SseDeserializer deserializer,
  );

  @protected
  CustomData? sse_decode_opt_box_autoadd_custom_data(
    SseDeserializer deserializer,
  );

  @protected
  Dimension? sse_decode_opt_box_autoadd_dimension(SseDeserializer deserializer);

  @protected
  DiyData? sse_decode_opt_box_autoadd_diy_data(SseDeserializer deserializer);

  @protected
  DyeColorParams? sse_decode_opt_box_autoadd_dye_color_params(
    SseDeserializer deserializer,
  );

  @protected
  HomeBuildParam? sse_decode_opt_box_autoadd_home_build_param(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LocationParams? sse_decode_opt_box_autoadd_location_params(
    SseDeserializer deserializer,
  );

  @protected
  MacOSCustomGameConfig? sse_decode_opt_box_autoadd_mac_os_custom_game_config(
    SseDeserializer deserializer,
  );

  @protected
  MacOSGameConfig? sse_decode_opt_box_autoadd_mac_os_game_config(
    SseDeserializer deserializer,
  );

  @protected
  MediaCustomData? sse_decode_opt_box_autoadd_media_custom_data(
    SseDeserializer deserializer,
  );

  @protected
  MomoHiddenState? sse_decode_opt_box_autoadd_momo_hidden_state(
    SseDeserializer deserializer,
  );

  @protected
  Nation? sse_decode_opt_box_autoadd_nation(SseDeserializer deserializer);

  @protected
  NikkiParams? sse_decode_opt_box_autoadd_nikki_params(
    SseDeserializer deserializer,
  );

  @protected
  ObjectParams? sse_decode_opt_box_autoadd_object_params(
    SseDeserializer deserializer,
  );

  @protected
  Region? sse_decode_opt_box_autoadd_region(SseDeserializer deserializer);

  @protected
  RichCameraParams? sse_decode_opt_box_autoadd_rich_camera_params(
    SseDeserializer deserializer,
  );

  @protected
  RichCameraParamsMomoHidden?
  sse_decode_opt_box_autoadd_rich_camera_params_momo_hidden(
    SseDeserializer deserializer,
  );

  @protected
  ShootingDate? sse_decode_opt_box_autoadd_shooting_date(
    SseDeserializer deserializer,
  );

  @protected
  ShootingTime? sse_decode_opt_box_autoadd_shooting_time(
    SseDeserializer deserializer,
  );

  @protected
  Subarea? sse_decode_opt_box_autoadd_subarea(SseDeserializer deserializer);

  @protected
  Text? sse_decode_opt_box_autoadd_text(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WeaponParams? sse_decode_opt_box_autoadd_weapon_params(
    SseDeserializer deserializer,
  );

  @protected
  WindowsCustomGameConfig?
  sse_decode_opt_box_autoadd_windows_custom_game_config(
    SseDeserializer deserializer,
  );

  @protected
  WindowsGameConfig? sse_decode_opt_box_autoadd_windows_game_config(
    SseDeserializer deserializer,
  );

  @protected
  WindowsRegistryConfig? sse_decode_opt_box_autoadd_windows_registry_config(
    SseDeserializer deserializer,
  );

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  List<FileEntityLocationConfig>?
  sse_decode_opt_list_file_entity_location_config(SseDeserializer deserializer);

  @protected
  OrdinaryText sse_decode_ordinary_text(SseDeserializer deserializer);

  @protected
  OutfitDyeData sse_decode_outfit_dye_data(SseDeserializer deserializer);

  @protected
  OutfitDyeGeneralData sse_decode_outfit_dye_general_data(
    SseDeserializer deserializer,
  );

  @protected
  OutfitDyeHairData sse_decode_outfit_dye_hair_data(
    SseDeserializer deserializer,
  );

  @protected
  PatternCreationData sse_decode_pattern_creation_data(
    SseDeserializer deserializer,
  );

  @protected
  PhotographyParams sse_decode_photography_params(SseDeserializer deserializer);

  @protected
  Platform sse_decode_platform(SseDeserializer deserializer);

  @protected
  PluginInfo sse_decode_plugin_info(SseDeserializer deserializer);

  @protected
  (double, double) sse_decode_record_f_64_f_64(SseDeserializer deserializer);

  @protected
  (double, double, double) sse_decode_record_f_64_f_64_f_64(
    SseDeserializer deserializer,
  );

  @protected
  (double, double, double, double) sse_decode_record_f_64_f_64_f_64_f_64(
    SseDeserializer deserializer,
  );

  @protected
  (int, Nuan5DatabaseItem) sse_decode_record_i_32_nuan_5_database_item(
    SseDeserializer deserializer,
  );

  @protected
  (PlatformInt64, bool) sse_decode_record_i_64_bool(
    SseDeserializer deserializer,
  );

  @protected
  (PlatformInt64, PlatformInt64) sse_decode_record_i_64_i_64(
    SseDeserializer deserializer,
  );

  @protected
  (String, bool) sse_decode_record_string_bool(SseDeserializer deserializer);

  @protected
  (int, int, int) sse_decode_record_u_8_u_8_u_8(SseDeserializer deserializer);

  @protected
  Region sse_decode_region(SseDeserializer deserializer);

  @protected
  RegionPicture sse_decode_region_picture(SseDeserializer deserializer);

  @protected
  RichBuildingParams sse_decode_rich_building_params(
    SseDeserializer deserializer,
  );

  @protected
  RichCameraParams sse_decode_rich_camera_params(SseDeserializer deserializer);

  @protected
  RichCameraParamsMomoHidden sse_decode_rich_camera_params_momo_hidden(
    SseDeserializer deserializer,
  );

  @protected
  ShootingDate sse_decode_shooting_date(SseDeserializer deserializer);

  @protected
  ShootingTime sse_decode_shooting_time(SseDeserializer deserializer);

  @protected
  SpecialEffectData sse_decode_special_effect_data(
    SseDeserializer deserializer,
  );

  @protected
  Subarea sse_decode_subarea(SseDeserializer deserializer);

  @protected
  TaskParams sse_decode_task_params(SseDeserializer deserializer);

  @protected
  Text sse_decode_text(SseDeserializer deserializer);

  @protected
  ThemeConfigV1 sse_decode_theme_config_v_1(SseDeserializer deserializer);

  @protected
  ThemeConfigWrapper sse_decode_theme_config_wrapper(
    SseDeserializer deserializer,
  );

  @protected
  Thumbnail sse_decode_thumbnail(SseDeserializer deserializer);

  @protected
  TranslateText sse_decode_translate_text(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WeaponParams sse_decode_weapon_params(SseDeserializer deserializer);

  @protected
  WindowsCustomGameConfig sse_decode_windows_custom_game_config(
    SseDeserializer deserializer,
  );

  @protected
  WindowsGameConfig sse_decode_windows_game_config(
    SseDeserializer deserializer,
  );

  @protected
  WindowsGameLocationConfig sse_decode_windows_game_location_config(
    SseDeserializer deserializer,
  );

  @protected
  WindowsGameSearcherConfig sse_decode_windows_game_searcher_config(
    SseDeserializer deserializer,
  );

  @protected
  WindowsRegistryConfig sse_decode_windows_registry_config(
    SseDeserializer deserializer,
  );

  @protected
  WindowsRegistryHive sse_decode_windows_registry_hive(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode(
    ClothDiyShareCode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode(
    HomeBuildShareCode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    MediaKey self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1(
    Nuan5DatabaseReaderV1 self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1(
    Nuan5DatabaseReaderV1 self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode(
    ClothDiyShareCode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode(
    HomeBuildShareCode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    MediaKey self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1(
    Nuan5DatabaseReaderV1 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_bool_None(
    Map<String, bool> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_i_32_nuan_5_database_item_None(
    Map<int, Nuan5DatabaseItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_i_64_bool_None(
    Map<PlatformInt64, bool> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_i_64_i_64_None(
    Map<PlatformInt64, PlatformInt64> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode(
    ClothDiyShareCode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode(
    HomeBuildShareCode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    MediaKey self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1(
    Nuan5DatabaseReaderV1 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_media_custom_data_result_Sse(
    RustStreamSink<MediaCustomDataResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_media_decode_event_Sse(
    RustStreamSink<MediaDecodeEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_media_stream_result_Sse(
    RustStreamSink<MediaStreamResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_android_custom_game_config(
    AndroidCustomGameConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_android_game_config(
    AndroidGameConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_android_game_location_config(
    AndroidGameLocationConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_android_game_searcher_config(
    AndroidGameSearcherConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_area(Area self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_android_custom_game_config(
    AndroidCustomGameConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_android_game_config(
    AndroidGameConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_area(Area self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_camera_params(
    CameraParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_camera_params_momo_hidden(
    CameraParamsMomoHidden self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_clock_in_photo_params(
    ClockInPhotoParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_cloth_diy_param(
    ClothDiyParam self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_cloth_diy_params(
    ClothDiyParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_collage_params(
    CollageParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_custom_data(
    CustomData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_dimension(
    Dimension self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_diy_data(DiyData self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dye_color_params(
    DyeColorParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_edit_photo_params(
    EditPhotoParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_game_config(
    GameConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_home_build_param(
    HomeBuildParam self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_location(Location self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_location_params(
    LocationParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mac_os_custom_game_config(
    MacOSCustomGameConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mac_os_game_config(
    MacOSGameConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_media_custom_data(
    MediaCustomData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_media_param(
    MediaParam self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_momo_hidden_state(
    MomoHiddenState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_momo_params(
    MomoParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_nation(Nation self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_nikki_params(
    NikkiParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_nikki_photo_params(
    NikkiPhotoParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_nuan_5_cloth_diy_swatch_color(
    Nuan5ClothDiySwatchColor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_nuan_5_cloth_dye_area(
    Nuan5ClothDyeArea self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_nuan_5_cloth_dye_palette(
    Nuan5ClothDyePalette self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_nuan_5_filter(
    Nuan5Filter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_nuan_5_filter_type(
    Nuan5FilterType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_nuan_5_light(
    Nuan5Light self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_nuan_5_light_type(
    Nuan5LightType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_nuan_5_momo_pose(
    Nuan5MomoPose self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_object_params(
    ObjectParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ordinary_text(
    OrdinaryText self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_outfit_dye_general_data(
    OutfitDyeGeneralData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_outfit_dye_hair_data(
    OutfitDyeHairData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_plugin_info(
    PluginInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_region(Region self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rich_building_params(
    RichBuildingParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rich_camera_params(
    RichCameraParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rich_camera_params_momo_hidden(
    RichCameraParamsMomoHidden self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_shooting_date(
    ShootingDate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_shooting_time(
    ShootingTime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_subarea(Subarea self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_text(Text self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_theme_config_v_1(
    ThemeConfigV1 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_theme_config_wrapper(
    ThemeConfigWrapper self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_translate_text(
    TranslateText self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_weapon_params(
    WeaponParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_windows_custom_game_config(
    WindowsCustomGameConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_windows_game_config(
    WindowsGameConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_windows_registry_config(
    WindowsRegistryConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_camera_params(CameraParams self, SseSerializer serializer);

  @protected
  void sse_encode_camera_params_momo_hidden(
    CameraParamsMomoHidden self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_clock_in_photo_params(
    ClockInPhotoParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cloth(Cloth self, SseSerializer serializer);

  @protected
  void sse_encode_cloth_diy_param(ClothDiyParam self, SseSerializer serializer);

  @protected
  void sse_encode_cloth_diy_param_type(
    ClothDiyParamType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cloth_diy_params(
    ClothDiyParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cloth_params(ClothParams self, SseSerializer serializer);

  @protected
  void sse_encode_collage_params(CollageParams self, SseSerializer serializer);

  @protected
  void sse_encode_color_role_scheme(
    ColorRoleScheme self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_color_scheme(ColorScheme self, SseSerializer serializer);

  @protected
  void sse_encode_config_file_type(
    ConfigFileType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_custom_data(CustomData self, SseSerializer serializer);

  @protected
  void sse_encode_decryption_error(
    DecryptionError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dimension(Dimension self, SseSerializer serializer);

  @protected
  void sse_encode_diy_data(DiyData self, SseSerializer serializer);

  @protected
  void sse_encode_diy_history_share_code_params(
    DiyHistoryShareCodeParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dressing_params(
    DressingParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dye_color_params(
    DyeColorParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_edit_photo_params(
    EditPhotoParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_edit_photo_state(
    EditPhotoState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_encryption_error(
    EncryptionError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_eureka(Eureka self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_file_entity_location_config(
    FileEntityLocationConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_entity_type(
    FileEntityType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_filter_params(FilterParams self, SseSerializer serializer);

  @protected
  void sse_encode_game_album_config(
    GameAlbumConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_game_config(GameConfig self, SseSerializer serializer);

  @protected
  void sse_encode_game_selector_config(
    GameSelectorConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_game_uid_config(GameUidConfig self, SseSerializer serializer);

  @protected
  void sse_encode_home_build_param(
    HomeBuildParam self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_home_build_param_type(
    HomeBuildParamType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_light_params(LightParams self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_android_game_location_config(
    List<AndroidGameLocationConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_cloth_params(
    List<ClothParams> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_diy_history_share_code_params(
    List<DiyHistoryShareCodeParams> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_eureka(List<Eureka> self, SseSerializer serializer);

  @protected
  void sse_encode_list_file_entity_location_config(
    List<FileEntityLocationConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_game_album_config(
    List<GameAlbumConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_location(List<Location> self, SseSerializer serializer);

  @protected
  void sse_encode_list_mac_os_game_location_config(
    List<MacOSGameLocationConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_object_params(
    List<ObjectParams> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_opt_box_autoadd_custom_data(
    List<CustomData?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_outfit_dye_data(
    List<OutfitDyeData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pattern_creation_data(
    List<PatternCreationData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_platform(List<Platform> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_i_32_nuan_5_database_item(
    List<(int, Nuan5DatabaseItem)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_i_64_bool(
    List<(PlatformInt64, bool)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_i_64_i_64(
    List<(PlatformInt64, PlatformInt64)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_bool(
    List<(String, bool)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_region_picture(
    List<RegionPicture> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_special_effect_data(
    List<SpecialEffectData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_task_params(
    List<TaskParams> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_windows_game_location_config(
    List<WindowsGameLocationConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_windows_game_searcher_config(
    List<WindowsGameSearcherConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_location(Location self, SseSerializer serializer);

  @protected
  void sse_encode_location_params(
    LocationParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_location_type(LocationType self, SseSerializer serializer);

  @protected
  void sse_encode_mac_os_custom_game_config(
    MacOSCustomGameConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mac_os_game_config(
    MacOSGameConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mac_os_game_location_config(
    MacOSGameLocationConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mac_os_game_searcher_config(
    MacOSGameSearcherConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_custom_data(
    MediaCustomData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_custom_data_result(
    MediaCustomDataResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_decode_event(
    MediaDecodeEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_param(MediaParam self, SseSerializer serializer);

  @protected
  void sse_encode_media_param_type(
    MediaParamType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_stream_result(
    MediaStreamResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_momo_hidden_state(
    MomoHiddenState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_momo_params(MomoParams self, SseSerializer serializer);

  @protected
  void sse_encode_nation(Nation self, SseSerializer serializer);

  @protected
  void sse_encode_nikki_params(NikkiParams self, SseSerializer serializer);

  @protected
  void sse_encode_nikki_photo_params(
    NikkiPhotoParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nuan_5_cloth_diy_swatch_color(
    Nuan5ClothDiySwatchColor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nuan_5_cloth_dye_area(
    Nuan5ClothDyeArea self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nuan_5_cloth_dye_palette(
    Nuan5ClothDyePalette self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nuan_5_database_category(
    Nuan5DatabaseCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nuan_5_database_item(
    Nuan5DatabaseItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nuan_5_filter(Nuan5Filter self, SseSerializer serializer);

  @protected
  void sse_encode_nuan_5_filter_type(
    Nuan5FilterType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nuan_5_light(Nuan5Light self, SseSerializer serializer);

  @protected
  void sse_encode_nuan_5_light_type(
    Nuan5LightType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nuan_5_momo_pose(
    Nuan5MomoPose self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_object_params(ObjectParams self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_android_custom_game_config(
    AndroidCustomGameConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_android_game_config(
    AndroidGameConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_area(Area? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_camera_params_momo_hidden(
    CameraParamsMomoHidden? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_cloth_diy_param(
    ClothDiyParam? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_custom_data(
    CustomData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_dimension(
    Dimension? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_diy_data(
    DiyData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_dye_color_params(
    DyeColorParams? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_home_build_param(
    HomeBuildParam? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_location_params(
    LocationParams? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_mac_os_custom_game_config(
    MacOSCustomGameConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_mac_os_game_config(
    MacOSGameConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_media_custom_data(
    MediaCustomData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_momo_hidden_state(
    MomoHiddenState? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_nation(
    Nation? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_nikki_params(
    NikkiParams? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_object_params(
    ObjectParams? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_region(
    Region? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_rich_camera_params(
    RichCameraParams? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_rich_camera_params_momo_hidden(
    RichCameraParamsMomoHidden? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_shooting_date(
    ShootingDate? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_shooting_time(
    ShootingTime? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_subarea(
    Subarea? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_text(Text? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_weapon_params(
    WeaponParams? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_windows_custom_game_config(
    WindowsCustomGameConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_windows_game_config(
    WindowsGameConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_windows_registry_config(
    WindowsRegistryConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_file_entity_location_config(
    List<FileEntityLocationConfig>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ordinary_text(OrdinaryText self, SseSerializer serializer);

  @protected
  void sse_encode_outfit_dye_data(OutfitDyeData self, SseSerializer serializer);

  @protected
  void sse_encode_outfit_dye_general_data(
    OutfitDyeGeneralData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_outfit_dye_hair_data(
    OutfitDyeHairData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pattern_creation_data(
    PatternCreationData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_photography_params(
    PhotographyParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_platform(Platform self, SseSerializer serializer);

  @protected
  void sse_encode_plugin_info(PluginInfo self, SseSerializer serializer);

  @protected
  void sse_encode_record_f_64_f_64(
    (double, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_f_64_f_64_f_64(
    (double, double, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_f_64_f_64_f_64_f_64(
    (double, double, double, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_i_32_nuan_5_database_item(
    (int, Nuan5DatabaseItem) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_i_64_bool(
    (PlatformInt64, bool) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_i_64_i_64(
    (PlatformInt64, PlatformInt64) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_bool(
    (String, bool) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_8_u_8_u_8(
    (int, int, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_region(Region self, SseSerializer serializer);

  @protected
  void sse_encode_region_picture(RegionPicture self, SseSerializer serializer);

  @protected
  void sse_encode_rich_building_params(
    RichBuildingParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rich_camera_params(
    RichCameraParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rich_camera_params_momo_hidden(
    RichCameraParamsMomoHidden self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_shooting_date(ShootingDate self, SseSerializer serializer);

  @protected
  void sse_encode_shooting_time(ShootingTime self, SseSerializer serializer);

  @protected
  void sse_encode_special_effect_data(
    SpecialEffectData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_subarea(Subarea self, SseSerializer serializer);

  @protected
  void sse_encode_task_params(TaskParams self, SseSerializer serializer);

  @protected
  void sse_encode_text(Text self, SseSerializer serializer);

  @protected
  void sse_encode_theme_config_v_1(
    ThemeConfigV1 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_theme_config_wrapper(
    ThemeConfigWrapper self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_thumbnail(Thumbnail self, SseSerializer serializer);

  @protected
  void sse_encode_translate_text(TranslateText self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_weapon_params(WeaponParams self, SseSerializer serializer);

  @protected
  void sse_encode_windows_custom_game_config(
    WindowsCustomGameConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_windows_game_config(
    WindowsGameConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_windows_game_location_config(
    WindowsGameLocationConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_windows_game_searcher_config(
    WindowsGameSearcherConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_windows_registry_config(
    WindowsRegistryConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_windows_registry_hive(
    WindowsRegistryHive self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCodePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_nikki_albums_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCodePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCodePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_nikki_albums_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCode =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerClothDiyShareCodePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCodePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_nikki_albums_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCodePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCodePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_nikki_albums_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCode =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHomeBuildShareCodePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKeyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_nikki_albums_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKeyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKeyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_nikki_albums_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKeyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1Ptr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_nikki_albums_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1 =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1Ptr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1Ptr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_nikki_albums_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1 =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNuan5DatabaseReaderV1Ptr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
