// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'nuan5_media_param/decrypt.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'thumbnail.dart';
import 'thumbnail/jpeg.dart';
import 'thumbnail/mp4_h264.dart';
import 'thumbnail/png.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1422373251;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_nikki_albums',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  MediaKey crateNuan5MediaParamDecryptMediaKeyCameraParam();

  Future<void> crateNuan5MediaParamDecryptMediaKeyDispose({
    required MediaKey that,
  });

  MediaKey crateNuan5MediaParamDecryptMediaKeyFromStr({required String s});

  MediaKey crateNuan5MediaParamDecryptMediaKeyFromStrBytes({
    required List<int> bytes,
  });

  Future<Thumbnail> crateThumbnailJpegGenerateThumbnail({
    required List<int> jpegBytes,
    int? targetWidth,
    int? targetHeight,
  });

  Future<Thumbnail> crateThumbnailMp4H264GenerateThumbnail({
    required List<int> mp4Bytes,
    int? targetWidth,
    int? targetHeight,
  });

  Future<Thumbnail> crateThumbnailPngGenerateThumbnail({
    required List<int> pngBytes,
    int? targetWidth,
    int? targetHeight,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  CustomData? crateNuan5MediaParamDecryptMediaDecodeFileBytesUnchecked({
    required List<int> flag,
    required List<int> bytes,
    required MediaKey key,
  });

  Future<CustomData?> crateNuan5MediaParamDecryptMediaDecodeFileUnchecked({
    required List<int> flag,
    required String path,
    required MediaKey key,
  });

  CustomData? crateNuan5MediaParamDecryptMediaDecodeFileUncheckedSync({
    required List<int> flag,
    required String path,
    required MediaKey key,
  });

  Stream<MediaDecodeEvent>
  crateNuan5MediaParamDecryptMediaDecodeFilesUnchecked({
    required List<int> flag,
    required List<String> paths,
    required MediaKey key,
  });

  Future<List<CustomData?>>
  crateNuan5MediaParamDecryptMediaDecodeFilesUncheckedNoProgress({
    required List<int> flag,
    required List<String> paths,
    required MediaKey key,
  });

  CustomData? crateNuan5MediaParamDecryptMediaDecrypt({
    required List<int> data,
    required MediaKey key,
  });

  int crateApiSimpleTestAdd({required int num1, required int num2});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MediaKey;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MediaKey;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MediaKeyPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  MediaKey crateNuan5MediaParamDecryptMediaKeyCameraParam() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateNuan5MediaParamDecryptMediaKeyCameraParamConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateNuan5MediaParamDecryptMediaKeyCameraParamConstMeta =>
      const TaskConstMeta(debugName: "MediaKey_camera_param", argNames: []);

  @override
  Future<void> crateNuan5MediaParamDecryptMediaKeyDispose({
    required MediaKey that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateNuan5MediaParamDecryptMediaKeyDisposeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateNuan5MediaParamDecryptMediaKeyDisposeConstMeta =>
      const TaskConstMeta(debugName: "MediaKey_dispose", argNames: ["that"]);

  @override
  MediaKey crateNuan5MediaParamDecryptMediaKeyFromStr({required String s}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(s, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateNuan5MediaParamDecryptMediaKeyFromStrConstMeta,
        argValues: [s],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateNuan5MediaParamDecryptMediaKeyFromStrConstMeta =>
      const TaskConstMeta(debugName: "MediaKey_from_str", argNames: ["s"]);

  @override
  MediaKey crateNuan5MediaParamDecryptMediaKeyFromStrBytes({
    required List<int> bytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateNuan5MediaParamDecryptMediaKeyFromStrBytesConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateNuan5MediaParamDecryptMediaKeyFromStrBytesConstMeta =>
      const TaskConstMeta(
        debugName: "MediaKey_from_str_bytes",
        argNames: ["bytes"],
      );

  @override
  Future<Thumbnail> crateThumbnailJpegGenerateThumbnail({
    required List<int> jpegBytes,
    int? targetWidth,
    int? targetHeight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(jpegBytes, serializer);
          sse_encode_opt_box_autoadd_u_32(targetWidth, serializer);
          sse_encode_opt_box_autoadd_u_32(targetHeight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_thumbnail,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateThumbnailJpegGenerateThumbnailConstMeta,
        argValues: [jpegBytes, targetWidth, targetHeight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateThumbnailJpegGenerateThumbnailConstMeta =>
      const TaskConstMeta(
        debugName: "generate_thumbnail",
        argNames: ["jpegBytes", "targetWidth", "targetHeight"],
      );

  @override
  Future<Thumbnail> crateThumbnailMp4H264GenerateThumbnail({
    required List<int> mp4Bytes,
    int? targetWidth,
    int? targetHeight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(mp4Bytes, serializer);
          sse_encode_opt_box_autoadd_u_32(targetWidth, serializer);
          sse_encode_opt_box_autoadd_u_32(targetHeight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_thumbnail,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateThumbnailMp4H264GenerateThumbnailConstMeta,
        argValues: [mp4Bytes, targetWidth, targetHeight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateThumbnailMp4H264GenerateThumbnailConstMeta =>
      const TaskConstMeta(
        debugName: "generate_thumbnail",
        argNames: ["mp4Bytes", "targetWidth", "targetHeight"],
      );

  @override
  Future<Thumbnail> crateThumbnailPngGenerateThumbnail({
    required List<int> pngBytes,
    int? targetWidth,
    int? targetHeight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(pngBytes, serializer);
          sse_encode_opt_box_autoadd_u_32(targetWidth, serializer);
          sse_encode_opt_box_autoadd_u_32(targetHeight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_thumbnail,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateThumbnailPngGenerateThumbnailConstMeta,
        argValues: [pngBytes, targetWidth, targetHeight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateThumbnailPngGenerateThumbnailConstMeta =>
      const TaskConstMeta(
        debugName: "generate_thumbnail",
        argNames: ["pngBytes", "targetWidth", "targetHeight"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  CustomData? crateNuan5MediaParamDecryptMediaDecodeFileBytesUnchecked({
    required List<int> flag,
    required List<int> bytes,
    required MediaKey key,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(flag, serializer);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
            key,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_custom_data,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateNuan5MediaParamDecryptMediaDecodeFileBytesUncheckedConstMeta,
        argValues: [flag, bytes, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateNuan5MediaParamDecryptMediaDecodeFileBytesUncheckedConstMeta =>
      const TaskConstMeta(
        debugName: "media_decode_file_bytes_unchecked",
        argNames: ["flag", "bytes", "key"],
      );

  @override
  Future<CustomData?> crateNuan5MediaParamDecryptMediaDecodeFileUnchecked({
    required List<int> flag,
    required String path,
    required MediaKey key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(flag, serializer);
          sse_encode_String(path, serializer);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
            key,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_custom_data,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateNuan5MediaParamDecryptMediaDecodeFileUncheckedConstMeta,
        argValues: [flag, path, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateNuan5MediaParamDecryptMediaDecodeFileUncheckedConstMeta =>
      const TaskConstMeta(
        debugName: "media_decode_file_unchecked",
        argNames: ["flag", "path", "key"],
      );

  @override
  CustomData? crateNuan5MediaParamDecryptMediaDecodeFileUncheckedSync({
    required List<int> flag,
    required String path,
    required MediaKey key,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(flag, serializer);
          sse_encode_String(path, serializer);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
            key,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_custom_data,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateNuan5MediaParamDecryptMediaDecodeFileUncheckedSyncConstMeta,
        argValues: [flag, path, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateNuan5MediaParamDecryptMediaDecodeFileUncheckedSyncConstMeta =>
      const TaskConstMeta(
        debugName: "media_decode_file_unchecked_sync",
        argNames: ["flag", "path", "key"],
      );

  @override
  Stream<MediaDecodeEvent>
  crateNuan5MediaParamDecryptMediaDecodeFilesUnchecked({
    required List<int> flag,
    required List<String> paths,
    required MediaKey key,
  }) {
    final progressSink = RustStreamSink<MediaDecodeEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_list_prim_u_8_loose(flag, serializer);
            sse_encode_list_String(paths, serializer);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
              key,
              serializer,
            );
            sse_encode_StreamSink_media_decode_event_Sse(
              progressSink,
              serializer,
            );
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 13,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta:
              kCrateNuan5MediaParamDecryptMediaDecodeFilesUncheckedConstMeta,
          argValues: [flag, paths, key, progressSink],
          apiImpl: this,
        ),
      ),
    );
    return progressSink.stream;
  }

  TaskConstMeta
  get kCrateNuan5MediaParamDecryptMediaDecodeFilesUncheckedConstMeta =>
      const TaskConstMeta(
        debugName: "media_decode_files_unchecked",
        argNames: ["flag", "paths", "key", "progressSink"],
      );

  @override
  Future<List<CustomData?>>
  crateNuan5MediaParamDecryptMediaDecodeFilesUncheckedNoProgress({
    required List<int> flag,
    required List<String> paths,
    required MediaKey key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(flag, serializer);
          sse_encode_list_String(paths, serializer);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
            key,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_opt_box_autoadd_custom_data,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateNuan5MediaParamDecryptMediaDecodeFilesUncheckedNoProgressConstMeta,
        argValues: [flag, paths, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateNuan5MediaParamDecryptMediaDecodeFilesUncheckedNoProgressConstMeta =>
      const TaskConstMeta(
        debugName: "media_decode_files_unchecked_no_progress",
        argNames: ["flag", "paths", "key"],
      );

  @override
  CustomData? crateNuan5MediaParamDecryptMediaDecrypt({
    required List<int> data,
    required MediaKey key,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
            key,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_custom_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateNuan5MediaParamDecryptMediaDecryptConstMeta,
        argValues: [data, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateNuan5MediaParamDecryptMediaDecryptConstMeta =>
      const TaskConstMeta(
        debugName: "media_decrypt",
        argNames: ["data", "key"],
      );

  @override
  int crateApiSimpleTestAdd({required int num1, required int num2}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(num1, serializer);
          sse_encode_i_32(num2, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleTestAddConstMeta,
        argValues: [num1, num2],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTestAddConstMeta =>
      const TaskConstMeta(debugName: "test_add", argNames: ["num1", "num2"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MediaKey => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MediaKey => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  MediaKey
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaKeyImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MediaKey
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaKeyImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MediaKey
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaKeyImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<MediaDecodeEvent> dco_decode_StreamSink_media_decode_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  CustomData dco_decode_box_autoadd_custom_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_custom_data(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CustomData dco_decode_custom_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CustomData_Invalid();
      case 1:
        return CustomData_Valid(dco_decode_list_prim_u_8_strict(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CustomData?> dco_decode_list_opt_box_autoadd_custom_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_opt_box_autoadd_custom_data)
        .toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MediaDecodeEvent dco_decode_media_decode_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MediaDecodeEvent_Progress(dco_decode_f_64(raw[1]));
      case 1:
        return MediaDecodeEvent_Result(
          dco_decode_list_opt_box_autoadd_custom_data(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  CustomData? dco_decode_opt_box_autoadd_custom_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_custom_data(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  Thumbnail dco_decode_thumbnail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Thumbnail(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      bytes: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  MediaKey
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MediaKeyImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MediaKey
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MediaKeyImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MediaKey
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MediaKeyImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<MediaDecodeEvent> sse_decode_StreamSink_media_decode_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  CustomData sse_decode_box_autoadd_custom_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_custom_data(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CustomData sse_decode_custom_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return CustomData_Invalid();
      case 1:
        var var_field0 = sse_decode_list_prim_u_8_strict(deserializer);
        return CustomData_Valid(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CustomData?> sse_decode_list_opt_box_autoadd_custom_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CustomData?>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_opt_box_autoadd_custom_data(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MediaDecodeEvent sse_decode_media_decode_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_f_64(deserializer);
        return MediaDecodeEvent_Progress(var_field0);
      case 1:
        var var_field0 = sse_decode_list_opt_box_autoadd_custom_data(
          deserializer,
        );
        return MediaDecodeEvent_Result(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  CustomData? sse_decode_opt_box_autoadd_custom_data(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_custom_data(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Thumbnail sse_decode_thumbnail(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    return Thumbnail(width: var_width, height: var_height, bytes: var_bytes);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    MediaKey self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MediaKeyImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    MediaKey self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MediaKeyImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaKey(
    MediaKey self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MediaKeyImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_media_decode_event_Sse(
    RustStreamSink<MediaDecodeEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_media_decode_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_custom_data(
    CustomData self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_custom_data(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_custom_data(CustomData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CustomData_Invalid():
        sse_encode_i_32(0, serializer);
      case CustomData_Valid(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_list_prim_u_8_strict(field0, serializer);
    }
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_opt_box_autoadd_custom_data(
    List<CustomData?> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_opt_box_autoadd_custom_data(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_media_decode_event(
    MediaDecodeEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MediaDecodeEvent_Progress(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_f_64(field0, serializer);
      case MediaDecodeEvent_Result(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_list_opt_box_autoadd_custom_data(field0, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_custom_data(
    CustomData? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_custom_data(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_thumbnail(Thumbnail self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class MediaKeyImpl extends RustOpaque implements MediaKey {
  // Not to be used by end users
  MediaKeyImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MediaKeyImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_MediaKey,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_MediaKey,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_MediaKeyPtr,
  );

  Future<void> dispose() => RustLib.instance.api
      .crateNuan5MediaParamDecryptMediaKeyDispose(that: this);
}
