// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'decrypt.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'structs/building_params.dart';
import 'structs/camera_params.dart';
import 'structs/clock_in_photo_params.dart';
import 'structs/cloth.dart';
import 'structs/cloth_diy_params.dart';
import 'structs/collage_params.dart';
import 'structs/eureka.dart';
import 'structs/nikki_photo_params.dart';
import 'structs/world.dart';
part 'decode.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `get_flag`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MediaStreamCallbackContext`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`

Future<MediaCustomData> decodeMediaParam({
  required MediaParamType paramType,
  required CustomData data,
}) => RustLib.instance.api.crateNuan5ParamsDecodeDecodeMediaParam(
  paramType: paramType,
  data: data,
);

Future<MediaCustomData> mediaDe({
  required MediaParamType paramType,
  required List<int> data,
  required MediaKey key,
}) => RustLib.instance.api.crateNuan5ParamsDecodeMediaDe(
  paramType: paramType,
  data: data,
  key: key,
);

Future<MediaCustomData> mediaDeFileBytesUnchecked({
  required MediaParamType paramType,
  required List<int> bytes,
  required MediaKey key,
}) => RustLib.instance.api.crateNuan5ParamsDecodeMediaDeFileBytesUnchecked(
  paramType: paramType,
  bytes: bytes,
  key: key,
);

Future<MediaCustomData> mediaDeFileUnchecked({
  required MediaParamType paramType,
  required String path,
  required MediaKey key,
}) => RustLib.instance.api.crateNuan5ParamsDecodeMediaDeFileUnchecked(
  paramType: paramType,
  path: path,
  key: key,
);

MediaCustomData mediaDeFileUncheckedSync({
  required MediaParamType paramType,
  required String path,
  required MediaKey key,
}) => RustLib.instance.api.crateNuan5ParamsDecodeMediaDeFileUncheckedSync(
  paramType: paramType,
  path: path,
  key: key,
);

Stream<MediaCustomDataResult> mediaDeFilesUnchecked({
  required MediaParamType paramType,
  required List<String> paths,
  required MediaKey key,
}) => RustLib.instance.api.crateNuan5ParamsDecodeMediaDeFilesUnchecked(
  paramType: paramType,
  paths: paths,
  key: key,
);

Future<ClothDiyParam?> deClothDiyParam({
  required ClothDiyParamType paramType,
  required List<int> bytes,
}) => RustLib.instance.api.crateNuan5ParamsDecodeDeClothDiyParam(
  paramType: paramType,
  bytes: bytes,
);

Future<ClothDiyParam?> clothDiyDeNetwork({
  required ClothDiyShareCode key,
  String? cachePath,
}) => RustLib.instance.api.crateNuan5ParamsDecodeClothDiyDeNetwork(
  key: key,
  cachePath: cachePath,
);

Future<ClothDiyParam?> clothDiyDeFile({
  required ClothDiyParamType paramType,
  required String path,
}) => RustLib.instance.api.crateNuan5ParamsDecodeClothDiyDeFile(
  paramType: paramType,
  path: path,
);

Future<HomeBuildParam?> deHomeBuildParam({
  required HomeBuildParamType paramType,
  required List<int> bytes,
}) => RustLib.instance.api.crateNuan5ParamsDecodeDeHomeBuildParam(
  paramType: paramType,
  bytes: bytes,
);

Future<HomeBuildParam?> homeBuildDeNetwork({
  required HomeBuildShareCode key,
  String? cachePath,
}) => RustLib.instance.api.crateNuan5ParamsDecodeHomeBuildDeNetwork(
  key: key,
  cachePath: cachePath,
);

@freezed
sealed class ClothDiyParam with _$ClothDiyParam {
  const ClothDiyParam._();

  const factory ClothDiyParam.clothDiy(ClothDiyParams field0) =
      ClothDiyParam_ClothDiy;
  const factory ClothDiyParam.diyHistoryShareCode(
    List<DiyHistoryShareCodeParams> field0,
  ) = ClothDiyParam_DiyHistoryShareCode;
  const factory ClothDiyParam.qrCode(ClothDiyQrCodeParams field0) =
      ClothDiyParam_QrCode;
}

/// ============================================================
/// ClothDiy
/// ============================================================
enum ClothDiyParamType { clothDiy, diyHistoryShareCode, qrCode }

@freezed
sealed class HomeBuildParam with _$HomeBuildParam {
  const HomeBuildParam._();

  const factory HomeBuildParam.netHomeBuild(RichBuildingParams field0) =
      HomeBuildParam_NetHomeBuild;
}

/// ============================================================
/// HomeBuild
/// ============================================================
enum HomeBuildParamType { netHomeBuild }

@freezed
sealed class MediaCustomData with _$MediaCustomData {
  const MediaCustomData._();

  const factory MediaCustomData.invalid() = MediaCustomData_Invalid;
  const factory MediaCustomData.valid(MediaParam field0) =
      MediaCustomData_Valid;
}

class MediaCustomDataResult {
  final BigInt index;
  final MediaCustomData? data;

  const MediaCustomDataResult({required this.index, this.data});

  @override
  int get hashCode => index.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaCustomDataResult &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          data == other.data;
}

@freezed
sealed class MediaParam with _$MediaParam {
  const MediaParam._();

  const factory MediaParam.cameraParams(CameraParams field0) =
      MediaParam_CameraParams;
  const factory MediaParam.nikkiPhoto(NikkiPhotoParams field0) =
      MediaParam_NikkiPhoto;
  const factory MediaParam.clockInPhoto(ClockInPhotoParams field0) =
      MediaParam_ClockInPhoto;
  const factory MediaParam.collage(CollageParams field0) = MediaParam_Collage;
  const factory MediaParam.diy(ClothDiyParams field0) = MediaParam_DIY;
}

/// ============================================================
/// Media
/// ============================================================
enum MediaParamType { cameraParams, nikkiPhoto, clockInPhoto, collage, diy }
