// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BuildingParams`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

class RichBuildingParams {
  final String name;
  final String? coverImage;
  final int mapId;
  final PlatformInt64 lastModifyTime;
  final PlatformInt64 uid;
  final String gameArea;
  final int templateType;
  final int furnitureCount;
  final String version;

  const RichBuildingParams({
    required this.name,
    this.coverImage,
    required this.mapId,
    required this.lastModifyTime,
    required this.uid,
    required this.gameArea,
    required this.templateType,
    required this.furnitureCount,
    required this.version,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      coverImage.hashCode ^
      mapId.hashCode ^
      lastModifyTime.hashCode ^
      uid.hashCode ^
      gameArea.hashCode ^
      templateType.hashCode ^
      furnitureCount.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RichBuildingParams &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          coverImage == other.coverImage &&
          mapId == other.mapId &&
          lastModifyTime == other.lastModifyTime &&
          uid == other.uid &&
          gameArea == other.gameArea &&
          templateType == other.templateType &&
          furnitureCount == other.furnitureCount &&
          version == other.version;
}
