// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'cloth.dart';
import 'nikki_photo_params.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DiyHistoryShareCodeParams`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

class ClothDiyParams {
  final PlatformInt64? poseId;
  final Map<PlatformInt64, PlatformInt64> patternData;
  final List<ClothParams> clothes;

  const ClothDiyParams({
    this.poseId,
    required this.patternData,
    required this.clothes,
  });

  @override
  int get hashCode => poseId.hashCode ^ patternData.hashCode ^ clothes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClothDiyParams &&
          runtimeType == other.runtimeType &&
          poseId == other.poseId &&
          patternData == other.patternData &&
          clothes == other.clothes;
}
