// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'cloth.dart';
import 'eureka.dart';
import 'nikki_photo_params.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'world.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

class CollageParams {
  final PlatformInt64 templateId;
  final List<RegionPicture> regionPictures;

  const CollageParams({required this.templateId, required this.regionPictures});

  @override
  int get hashCode => templateId.hashCode ^ regionPictures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollageParams &&
          runtimeType == other.runtimeType &&
          templateId == other.templateId &&
          regionPictures == other.regionPictures;
}

class RegionPicture {
  final (double, double) position;
  final double rotation;
  final double scale;
  final String imageId;
  final NikkiPhotoParams oriCustomData;

  const RegionPicture({
    required this.position,
    required this.rotation,
    required this.scale,
    required this.imageId,
    required this.oriCustomData,
  });

  @override
  int get hashCode =>
      position.hashCode ^
      rotation.hashCode ^
      scale.hashCode ^
      imageId.hashCode ^
      oriCustomData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegionPicture &&
          runtimeType == other.runtimeType &&
          position == other.position &&
          rotation == other.rotation &&
          scale == other.scale &&
          imageId == other.imageId &&
          oriCustomData == other.oriCustomData;
}
