// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

class Eureka {
  final PlatformInt64 id;
  final PlatformInt64 outfit;
  final int attachmentPoint;
  final int level;
  final int color;

  const Eureka({
    required this.id,
    required this.outfit,
    required this.attachmentPoint,
    required this.level,
    required this.color,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      outfit.hashCode ^
      attachmentPoint.hashCode ^
      level.hashCode ^
      color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Eureka &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          outfit == other.outfit &&
          attachmentPoint == other.attachmentPoint &&
          level == other.level &&
          color == other.color;
}
