// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'nikki_photo_params.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'momo_camera_params.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

class CameraParams {
  final (double, double, double) cameraActorLoc;
  final (double, double, double) cameraActorRot;
  final (double, double, double) cameraComponentLoc;
  final (double, double, double) cameraComponentRot;
  final PlatformInt64 portraitMode;
  final double cameraFocalLength;
  final int apertureSection;
  final double vignetteIntensity;
  final double bloomIntensity;
  final double bloomThreshold;
  final double brightness;
  final double exposure;
  final double contrast;
  final double saturation;
  final double vibrance;
  final double highlights;
  final double shadows;
  final LightParams light;
  final FilterParams filter;
  final CameraParamsMomoHidden? momo;

  const CameraParams({
    required this.cameraActorLoc,
    required this.cameraActorRot,
    required this.cameraComponentLoc,
    required this.cameraComponentRot,
    required this.portraitMode,
    required this.cameraFocalLength,
    required this.apertureSection,
    required this.vignetteIntensity,
    required this.bloomIntensity,
    required this.bloomThreshold,
    required this.brightness,
    required this.exposure,
    required this.contrast,
    required this.saturation,
    required this.vibrance,
    required this.highlights,
    required this.shadows,
    required this.light,
    required this.filter,
    this.momo,
  });

  @override
  int get hashCode =>
      cameraActorLoc.hashCode ^
      cameraActorRot.hashCode ^
      cameraComponentLoc.hashCode ^
      cameraComponentRot.hashCode ^
      portraitMode.hashCode ^
      cameraFocalLength.hashCode ^
      apertureSection.hashCode ^
      vignetteIntensity.hashCode ^
      bloomIntensity.hashCode ^
      bloomThreshold.hashCode ^
      brightness.hashCode ^
      exposure.hashCode ^
      contrast.hashCode ^
      saturation.hashCode ^
      vibrance.hashCode ^
      highlights.hashCode ^
      shadows.hashCode ^
      light.hashCode ^
      filter.hashCode ^
      momo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CameraParams &&
          runtimeType == other.runtimeType &&
          cameraActorLoc == other.cameraActorLoc &&
          cameraActorRot == other.cameraActorRot &&
          cameraComponentLoc == other.cameraComponentLoc &&
          cameraComponentRot == other.cameraComponentRot &&
          portraitMode == other.portraitMode &&
          cameraFocalLength == other.cameraFocalLength &&
          apertureSection == other.apertureSection &&
          vignetteIntensity == other.vignetteIntensity &&
          bloomIntensity == other.bloomIntensity &&
          bloomThreshold == other.bloomThreshold &&
          brightness == other.brightness &&
          exposure == other.exposure &&
          contrast == other.contrast &&
          saturation == other.saturation &&
          vibrance == other.vibrance &&
          highlights == other.highlights &&
          shadows == other.shadows &&
          light == other.light &&
          filter == other.filter &&
          momo == other.momo;
}

@freezed
sealed class CameraParamsMomoHidden with _$CameraParamsMomoHidden {
  const CameraParamsMomoHidden._();

  const factory CameraParamsMomoHidden.enable() = CameraParamsMomoHidden_Enable;
  const factory CameraParamsMomoHidden.disable({
    required PlatformInt64 momoPose,
    required double horizontal,
    required double distance,
    required double height,
    required double rotateMomo,
    required bool autoGroundSnap,
    required bool floatingEffect,
    required bool poseWithNikki,
  }) = CameraParamsMomoHidden_Disable;
}
