// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'world.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`

enum Area {
  /// # Region::Wishfield
  memorialMountains,
  florawish,
  breezyMeadow,
  stoneville,
  abandonedDistrict,
  wishingWoods,
  fireworkIsles,
  serenityIsland,
  danqingIsland,
  danqingRealm,

  /// # Region::Itzaland
  itzalandCanyon,
  elderwoodForest,
  spira,
  boneyard,
  wanxiangRealm,
}

enum Dimension { miraland, seaOfStars, home }

@freezed
sealed class Location with _$Location {
  const Location._();

  const factory Location.standard({
    Dimension? dimension,
    Nation? nation,
    Region? region,
    Area? area,
    Subarea? subarea,
  }) = Location_Standard;
  const factory Location.special({Dimension? dimension, Subarea? subarea}) =
      Location_Special;
}

enum Nation {
  /// # Dimension::Miraland
  heartcraftKingdom,
  empireOfLight,
  terraAlliance,
  starhailFederation,
  linlangEmpire,
  twinmoonKingdom,
  whalePort,
  umbraso,
}

enum Region {
  /// # Nation::HeartcraftKingdom
  wishfield,

  /// # Nation::TerraAlliance
  itzaland,
}

enum Subarea {
  /// # Region::MemorialMountains
  oldFlorawishMemorial,
  stylistGuildMemorial,

  /// # Region::Florawish
  dreamwovenRuins,
  fortuneFalls,
  greatWishtreeSquare,
  lakesideDistrict,
  outskirtsForest,

  /// # Region::BreezyMeadow
  abandonedFanaticWisherCamp,
  breezyMeadowActivityArea,
  bugSongHills,
  ciciaHighlands,
  heartcraftKingdomOutpost,
  lakesideHill,
  meadowWharf,
  queenPalaceRuins,
  relicHill,
  sleepyFishHills,
  swanGazebo,

  /// # Region::Stoneville
  dyeWorkshop,
  flowerFieldsResidence,
  rockfallValley,
  stonevilleMarket,

  /// # Region::AbandonedDistrict
  chooChooStation,
  goldenFields,
  marketOfMirth,
  prosperville,
  rippleEstate,
  stellarFishingGround,
  stonecrown,
  windriderMill,

  /// # Region::WishingWoods
  brookwoodForest,
  cavernOfWishes,
  fallenWishHighlands,
  grandTreeValley,
  sacredMountains,
  valleyOfBlossoms,

  /// # Region::FireworkIsles
  clearheartLake,
  crescentMoonRuins,
  flamingForest,
  relicIsles,
  songbreezeHighland,
  sparkheartIsland,

  /// # Region::SerenityIsland
  oldRuins,
  soakville,
  soakvilleOutskirts,
  steamville,

  /// # Region::DanqingIsland
  danqingIslandBackMountain,
  bambooGrove,
  danqingIslandInkville,
  inkwashStream,
  loongPagoda,
  loongPeak,
  reedblossomShore,

  /// # Region::DanqingRealm
  greenBambooGrove,
  inkPool,
  inkshorePlain,
  danqingRealmInkville,
  wildfieldWaterside,

  /// # Region::ElderwoodForest
  behemothObservationSite,

  /// 巨兽观测点
  coliseum,
  elderwoodShade,
  elderwoodWharf,
  forestOfSlumber,
  forgottenStreet,
  giantVineForest,
  leafRiver,
  mothershroomWoods,
  parkyaCraterLake,
  pottsville,

  /// 陶罐村
  rockvilleRuins,
  shellIsland,
  shroomville,
  snailRanch,
  spiraWaterfall,
  titanGraveyard,

  /// 大拉姆居落
  titansOutpostRuins,

  /// 叶子河
  /// # Region::Spira
  spira1F,
  spira2F,
  spira3F,
  spiraShelldome,

  /// # Region::Boneyard
  bluePools,

  /// 蓝池
  cultivarium,

  /// 修习所
  dragonRuins,

  /// 龙埙遗所
  dragonrestFlowerfield,
  glimmeringLake,
  greatLumieville,
  healingGround,
  hollowbreathPassage,

  /// 幽息廊道
  lonestoneShore,

  /// 孤石滩
  soulSpring,

  /// 甜泉
  /// # Region::WanxiangRealm
  wanxiangRealmBackMountain,
  caiYeMarket,
  caiYeOutskirts,
  dazzlebloomMeadow,
  deepValleySpring,
  jiuhuaPavilion,
  jiuhuaPenitentiary,
  valleyPath,
  whereWoodEchoes,

  /// # Dimension::SeaOfStars
  crystalvale,
  dreamStarIsles,
  starshore,
  unboundWharf,

  /// # Dimension::Home
  dockArea,
}
