// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AppPersistentState {
  final bool isAgreeAgreement;
  final bool isInitialStartup;
  final String lang;
  final int theme;
  final Map<String, String> unknownField;

  const AppPersistentState({
    required this.isAgreeAgreement,
    required this.isInitialStartup,
    required this.lang,
    required this.theme,
    required this.unknownField,
  });

  static AppPersistentState? fromJson({required String json}) => RustLib
      .instance
      .api
      .crateConfigAppPersistentStateAppPersistentStateFromJson(json: json);

  String toJson() => RustLib.instance.api
      .crateConfigAppPersistentStateAppPersistentStateToJson(that: this);

  String toJsonPretty() => RustLib.instance.api
      .crateConfigAppPersistentStateAppPersistentStateToJsonPretty(that: this);

  @override
  int get hashCode =>
      isAgreeAgreement.hashCode ^
      isInitialStartup.hashCode ^
      lang.hashCode ^
      theme.hashCode ^
      unknownField.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppPersistentState &&
          runtimeType == other.runtimeType &&
          isAgreeAgreement == other.isAgreeAgreement &&
          isInitialStartup == other.isInitialStartup &&
          lang == other.lang &&
          theme == other.theme &&
          unknownField == other.unknownField;
}
