// Translation Dictionary for Landing Page
const i18n = {
	zh: {
		page_title: "暖暖相册 - 一款用于管理你的无限暖暖相册的工具",
		app_name: "暖暖相册",
		nav_qq: "交流群1062670402",
		nav_tutorial: "教程",
		nav_download: "下载",
		hero_title: "暖暖相册",
		hero_desc: "一款专为《无限暖暖》玩家精心打造的相册管理软件",
		hero_subdesc: "轻松、高效地管理游戏相册，让游戏体验更加畅快无忧。免费开源，无广告。",
		btn_download: "立即下载",
		btn_github: "GitHub 仓库",
		compat_hint: "支持 Windows 10/11 和 macOS (M系列芯片)",
		tab_wall: "相册概览",
		tab_decode: "参数解码",
		card_1_title: "全方位相册管理",
		card_1_desc: "支持查看 19 类相册与 3 类内部资源，深度适配日常、趣拼、动态影集等多种分类。",
		card_2_title: "相机参数解析",
		card_2_desc: "自动解析相机光圈、焦距、滤镜参数及拍摄坐标，助你轻松复现精美构图。",
		card_3_title: "高效批量处理",
		card_3_desc: "支持批量导出、还原、转移、删除，内置智能去重功能，让相册管理更省心。",
		card_4_title: "动图与实况转换",
		card_4_desc: "一键将视频或动态影集转换为苹果或安卓兼容的实况照片 (Live Photo) 或 GIF 动图。",
		card_5_title: "多渠道无损分享",
		card_5_desc: "支持一键复制到剪贴板，通过本地硬盘或局域网无损导出，分享快人一步。",
		footer_disclaimer: "暖暖相册并非《无限暖暖》官方或叠纸游戏的官方产品。所有素材版权归原公司所有。",
		modal_title: "首次运行 macOS 版的重要提示",
		modal_desc: "由于当前程序是免签名的便携版，首次打开可能会被系统拦截。<br><br>请按照以下步骤正常打开：<br>1. 若弹出“Apple 无法检查 App 是否包含恶意软件”，请点按 <b>好</b>。<br>2. 打开系统的 <b>系统设置</b> > <b>隐私与安全性</b>。<br>3. 前往“安全性”部分，找到关于 Nikki Albums 的提示，然后点按 <b>打开</b>。<br>4. 点按 <b>仍要打开</b>，输入你的登录密码，然后点按 <b>好</b>。",
		modal_btn: "我已了解"
	},
	"zh-tw": {
		page_title: "暖暖相冊 - 一款用於管理你的無限暖暖相冊的工具",
		app_name: "暖暖相冊",
		nav_qq: "交流群1062670402",
		nav_tutorial: "教程",
		nav_download: "下載",
		hero_title: "暖暖相冊",
		hero_desc: "一款專為《無限暖暖》玩家精心打造的相冊管理軟件",
		hero_subdesc: "輕鬆、高效地管理遊戲相冊，讓遊戲體驗更加暢快無憂。免費開源，無廣告。",
		btn_download: "立即下載",
		btn_github: "GitHub 倉庫",
		compat_hint: "支持 Windows 10/11 和 macOS (M系列晶片)",
		tab_wall: "相冊概覽",
		tab_decode: "參數解碼",
		card_1_title: "多種相冊管理",
		card_1_desc: "支持查看 19 類相冊與 3 類遊戲內部資源，涵蓋日常、趣拼、動態影集等。",
		card_2_title: "相機參數解碼",
		card_2_desc: "自動解碼相機光圈、焦距、濾鏡參數及拍攝坐標，輕鬆復現精美構圖。",
		card_3_title: "高效批量操作",
		card_3_desc: "支持批量導出、還原、轉移、刪除、移動，內置智能去重，管理更省心。",
		card_4_title: "動圖與實況轉換",
		card_4_desc: "一鍵將視頻或動態影集轉換為 GIF 動圖或 macOS 系統實況照片 (Live Photo)。",
		card_5_title: "多渠道導出分享",
		card_5_desc: "支持複製到剪貼簿，支持區域網路或同一網路設備無損導出，分享快人一步。",
		footer_disclaimer: "暖暖相冊並非《無限暖暖》官方或疊紙遊戲的官方產品。所有素材版權歸原公司所有。",
		modal_title: "首次運行 macOS 版的重要提示",
		modal_desc: "由於當前程序是免簽名的攜帶版，首次打開可能會被系統攔截。<br><br>請按照以下步驟正常打開：<br>1. 若彈出“Apple 無法檢查 App 是否包含惡意軟件”，請點按 <b>好</b>。<br>2. 打開系統的 <b>系統設置</b> > <b>隱私與安全性</b>。<br>3. 前往“安全性”部分，找到關於 Nikki Albums 的提示，然後點按 <b>打開</b>。<br>4. 點按 <b>仍要打開</b>，輸入你的登錄密碼，然後點按 <b>好</b>。",
		modal_btn: "我已了解",
	},
	en: {
		page_title: "Nikki Albums - A photo album manager for Infinity Nikki",
		app_name: "Nikki Albums",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "Tutorial",
		nav_download: "Download",
		hero_title: "Nikki Albums",
		hero_desc: "An elegant and efficient photo album manager built for Infinity Nikki players",
		hero_subdesc: "Easily manage your in-game photo albums across multiple accounts. Fully open-source and completely free.",
		btn_download: "Download Now",
		btn_github: "GitHub Repo",
		compat_hint: "Supports Windows 10/11 & macOS (Apple Silicon)",
		tab_wall: "Album Showcase",
		tab_decode: "Metadata Decoder",
		card_1_title: "Diverse Albums",
		card_1_desc: "Supports viewing 19 album categories and 3 game resource types, including video albums.",
		card_2_title: "Metadata Decoding",
		card_2_desc: "Extracts aperture, focal length, filters, and coordinates to help reproduce your best shots.",
		card_3_title: "Batch Processing",
		card_3_desc: "Batch export, restore, transfer, delete, and move with smart duplicate detection.",
		card_4_title: "Live Photo & GIF Maker",
		card_4_desc: "Convert game video albums to animated GIFs or macOS Live Photos seamlessly.",
		card_5_title: "Easy Export",
		card_5_desc: "Export losslessly to the clipboard or transfer directly to network devices.",
		footer_disclaimer: "Nikki Albums is an open-source tool and is not affiliated with Infinity Nikki or Papergames. All copyrights belong to their respective owners.",
		modal_title: "Important Note for macOS Users",
		modal_desc: "Since this is an ad-hoc signed app, macOS Gatekeeper might block it on the first run.<br><br>Please follow these steps to open it normally:<br>1. If a dialog says \"Apple can't check app for malicious software\", click <b>OK</b>.<br>2. Open <b>System Settings</b> > <b>Privacy & Security</b>.<br>3. Under the \"Security\" section, locate Nikki Albums and click <b>Open</b>.<br>4. Click <b>Open Anyway</b>, enter your login password, and click <b>OK</b>.",
		modal_btn: "Got it"
	},
	ja: {
		page_title: "Nikki Albums - インフィニティニキの写真アルバム管理ツール",
		app_name: "Nikki Albums",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "チュートリアル",
		nav_download: "ダウンロード",
		hero_title: "Nikki Albums",
		hero_desc: "『インフィニティニキ』プレイヤーのために設計されたアルバム管理ソフト",
		hero_subdesc: "ゲーム内の写真アルバムを簡単に効率よく管理。完全無料でオープンソース、広告なし。",
		btn_download: "今すぐダウンロード",
		btn_github: "GitHub リポジトリ",
		compat_hint: "Windows 10/11 および macOS (Apple Silicon) に対応",
		tab_wall: "アルバム一覧",
		tab_decode: "パラメータ解析",
		card_1_title: "多種多様なアルバム管理",
		card_1_desc: "日常、コラージュ、動画アルバムなど、19種類のアルバムと3種類のゲーム内リソースの閲覧に対応。",
		card_2_title: "撮影パラメータ解析",
		card_2_desc: "絞り、焦点距離、フィルター、撮影座標を自動解析し、美しい構図の再現をサポート。",
		card_3_title: "一括操作",
		card_3_desc: "一括書き出し、復元、転送、削除、移动に対応。重複画像のインテリジェント検出機能も搭載。",
		card_4_title: "GIF・ライブフォト変換",
		card_4_desc: "ワンクリックで動画やライブアルバムをGIF画像またはmacOS用のLive Photoに変換可能。",
		card_5_title: "多様な書き出し共有",
		card_5_desc: "クリップボードへのコピー、ローカルネットワーク内のデバイスへの無劣化転送で、素早く共有。",
		footer_disclaimer: "『Nikki Albums』はオープンソースのツールであり、インフィニティニキ公式やPapergamesとは一切関係ありません。すべての素材の著作権は原権利者に归属します。",
		modal_title: "macOS版の初回実行に関する重要なお知らせ",
		modal_desc: "署名なしのポータブル版であるため、初回起動時にmacOSによってブロックされる場合があります。<br><br>以下の手順に従って正常に開いてください：<br>1. 「Appleは悪質なソフトウェアがないか確認できません」と表示された場合は、<b>OK</b>をクリックします。<br>2. <b>システム設定</b> > <b>プライバシーとセキュリティ</b>を開きます。<br>3. セキュリティ欄にあるNikki Albumsの起動に関するメッセージを確認し、<b>このまま開く</b>をクリックします。<br>4. ログインパスワードを入力し、<b>OK</b>をクリックします。",
		modal_btn: "了解しました"
	},
	ko: {
		page_title: "Nikki Albums - 인피니티 니키 사진 앨범 관리 도구",
		app_name: "Nikki Albums",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "튜토리얼",
		nav_download: "다운로드",
		hero_title: "Nikki Albums",
		hero_desc: "인피니티 니키 플레이어를 위해 특별히 제작된 앨범 관리 소프트웨어",
		hero_subdesc: "게임 앨범을 쉽고 효율적으로 관리하여 더욱 쾌적한 게임 경험을 선사합니다. 광고 없는 완전 무료 오픈 소스.",
		btn_download: "지금 다운로드",
		btn_github: "GitHub 저장소",
		compat_hint: "Windows 10/11 및 macOS (Apple Silicon) 지원",
		tab_wall: "앨범 개요",
		tab_decode: "파라미터 디코더",
		card_1_title: "다양한 앨범 관리",
		card_1_desc: "일상, 퍼즐, 동영상 앨범을 포함한 19개 앨범 카테고리와 3개 게임 내 리소스 뷰어 지원.",
		card_2_title: "카메라 파라미터 디코딩",
		card_2_desc: "조리개, 초점 거리, 필터 파라미터 및 촬영 좌표를 자동으로 디코딩하여 멋진 구도를 쉽게 재현.",
		card_3_title: "효율적인 일괄 작업",
		card_3_desc: "스마트 중복 제거 기능이 내장되어 일괄 내보내기, 복원, 전송, 삭제 및 이동을 더욱 간편하게 관리.",
		card_4_title: "움짤 및 라이브 포토 변환",
		card_4_desc: "동영상이나 라이브 앨범을 원클릭으로 GIF 움짤 또는 macOS 라이브 포토(Live Photo)로 변환.",
		card_5_title: "다채널 내보내기 및 공유",
		card_5_desc: "클립보드 복사 및 로컬 네트워크(LAN) 내 무손실 전송을 지원하여 한발 빠른 공유 가능.",
		footer_disclaimer: "Nikki Albums는 오픈 소스 도구이며 인피니티 니키 공식 또는 Papergames와 관련이 없습니다. 모든 자료의 저작권은 해당 회사에 있습니다.",
		modal_title: "macOS 버전 최초 실행 시 중요 안내",
		modal_desc: "본 앱은 서명되지 않은 포터블 버전으로, 최초 실행 시 시스템에 의해 차단될 수 있습니다.<br><br>정상적으로 실행하려면 다음 단계를 따르십시오:<br>1. \"Apple에서 악성 소프트웨어가 있는지 확인할 수 없습니다\"라는 팝업이 뜨면 <b>확인</b>을 클릭합니다.<br>2. 시스템의 <b>설정</b> > <b>개인정보 보호 및 보안</b>을 엽니다.<br>3. 보안 섹션에서 Nikki Albums 관련 안내를 찾아 <b>열기</b>를 클릭합니다.<br>4. <b>계속 열기</b>를 클릭하고 컴퓨터 암호를 입력한 뒤 <b>확인</b>을 클릭합니다.",
		modal_btn: "확인 완료"
	},
	fr: {
		page_title: "Nikki Albums - Un gestionnaire d'albums photo pour Infinity Nikki",
		app_name: "Nikki Albums",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "Tutoriel",
		nav_download: "Télécharger",
		hero_title: "Nikki Albums",
		hero_desc: "Un gestionnaire d'albums photo élégant et efficace conçu pour les joueurs d'Infinity Nikki",
		hero_subdesc: "Gerez facilement et efficacement vos albums photo de jeu. Entièrement gratuit, open-source et sans publicité.",
		btn_download: "Télécharger maintenant",
		btn_github: "Dépôt GitHub",
		compat_hint: "Prend en charge Windows 10/11 et macOS (Apple Silicon)",
		tab_wall: "Galerie d'Albums",
		tab_decode: "Décodeur de métadonnées",
		card_1_title: "Gestion d'Albums Variés",
		card_1_desc: "Permet de visualiser 19 catégories d'albums et 3 types de ressources internes au jeu, y compris les albums vidéo.",
		card_2_title: "Décodage de métadonnées",
		card_2_desc: "Décode automatiquement l'ouverture de l'appareil, la focale, les filtres et les coordonnées pour recréer de superbes compositions.",
		card_3_title: "Traitement par lots",
		card_3_desc: "Exportation, restauration, transfert, suppression et déplacement par lot avec détection intelligente des doublons.",
		card_4_title: "Live Photo & Créateur GIF",
		card_4_desc: "Convertissez en un clic vos vidéos et albums dynamiques en GIF animés ou en Live Photos système macOS.",
		card_5_title: "Export facile",
		card_5_desc: "Copie dans le presse-papiers, transfert sans perte via réseau local ou appareils connectés.",
		footer_disclaimer: "Nikki Albums est un outil open-source non affilié à Infinity Nikki ou Papergames. Tous les droits d'auteur appartiennent à leurs propriétaires respectifs.",
		modal_title: "Note importante pour les utilisateurs macOS",
		modal_desc: "Puisqu'il s'agit d'une application portable signée ad-hoc, macOS Gatekeeper peut la bloquer lors du premier lancement.<br><br>Veuillez suivre ces étapes pour l'ouvrir normalement :<br>1. Si une boîte de dialogue indique \"Apple ne peut pas vérifier si l'application contient des logiciels malveillants\", cliquez sur <b>OK</b>.<br>2. Ouvrez <b>Réglages Système</b> > <b>Confidentialité et sécurité</b>.<br>3. Dans la section \"Sécurité\", localisez l'avis Nikki Albums et cliquez sur <b>Ouvrir quand même</b>.<br>4. Entrez votre mot de passe et validez.",
		modal_btn: "J'ai compris"
	},
	de: {
		page_title: "Nikki Albums - Ein Fotoalbum-Manager für Infinity Nikki",
		app_name: "Nikki Albums",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "Tutorial",
		nav_download: "Herunterladen",
		hero_title: "Nikki Albums",
		hero_desc: "Ein eleganter und effizienter Fotoalbum-Manager für Spieler von Infinity Nikki",
		hero_subdesc: "Verwalten Sie Ihre Fotoalben im Spiel einfach und effizient. Völlig kostenlos, Open-Source und werbefrei.",
		btn_download: "Jetzt herunterladen",
		btn_github: "GitHub-Repository",
		compat_hint: "Unterstützt Windows 10/11 & macOS (Apple Silicon)",
		tab_wall: "Album-Galerie",
		tab_decode: "Metadaten-Decoder",
		card_1_title: "Diverse Alben-Verwaltung",
		card_1_desc: "Unterstützt die Anzeige von 19 Albumkategorien und 3 spielinternen Ressourcentypen, einschließlich Videoalben.",
		card_2_title: "Metadaten-Dekodierung",
		card_2_desc: "Dekodiert automatisch Blende, Brennweite, Filter und Koordinaten, um hervorragende Bildkompositionen zu reproduzieren.",
		card_3_title: "Stapelverarbeitung",
		card_3_desc: "Massenexport, Wiederherstellung, Übertragung, Löschung und Verschiebung mit einer intelligenten Duplikaterkennung.",
		card_4_title: "Live Photo & GIF-Ersteller",
		card_4_desc: "Konvertieren Sie Spielevideos und dynamische Alben nahtlos in animierte GIFs oder macOS Live Photos.",
		card_5_title: "Einfacher Export",
		card_5_desc: "Kopieren in die Zwischenablage, verlustfreier Export im lokalen Netzwerk oder an Netzwerkgeräte.",
		footer_disclaimer: "Nikki Albums ist ein Open-Source-Tool und steht in keiner Verbindung zu Infinity Nikki oder Papergames. Alle Urheberrechte liegen bei ihren jeweiligen Eigentümern.",
		modal_title: "Wichtiger Hinweis für macOS-Benutzer",
		modal_desc: "Da es sich um eine nicht signierte portable Anwendung handelt, blockiert macOS Gatekeeper sie möglicherweise beim ersten Start.<br><br>Bitte befolgen Sie diese Schritte, um sie normal zu öffnen:<br>1. Wenn ein Dialogfeld meldet, dass Apple die App nicht auf Schadsoftware überprüfen kann, klicken Sie auf <b>OK</b>.<br>2. Öffnen Sie die <b>Systemeinstellungen</b> > <b>Datenschutz & Sicherheit</b>.<br>3. Suchen Sie im Bereich „Sicherheit“ nach dem Hinweis zu Nikki Albums und klicken Sie auf <b>Dennoch öffnen</b>.<br>4. Geben Sie Ihr Passwort ein und bestätigen Sie.",
		modal_btn: "Verstanden"
	},
	es: {
		page_title: "Nikki Albums - Un gestor de álbumes de fotos para Infinity Nikki",
		app_name: "Nikki Albums",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "Tutorial",
		nav_download: "Descargar",
		hero_title: "Nikki Albums",
		hero_desc: "Un gestor de álbumes de fotos elegante y eficiente diseñado para jugadores de Infinity Nikki",
		hero_subdesc: "Gestiona tus álbumes de fotos del juego de forma fácil y eficaz. Totalmente gratuito, de código abierto y sin anuncios.",
		btn_download: "Descargar ahora",
		btn_github: "Repositorio GitHub",
		compat_hint: "Soporta Windows 10/11 y macOS (Apple Silicon)",
		tab_wall: "Galería de Álbumes",
		tab_decode: "Decodificador de metadatos",
		card_1_title: "Gestión de Álbumes Diversos",
		card_1_desc: "Soporta la visualización de 19 categorías de álbumes y 3 tipos de recursos internos del juego, incluyendo álbumes de vídeo.",
		card_2_title: "Decodificación de metadatos",
		card_2_desc: "Decodifica automáticamente la apertura, la distancia focal, los filtros y las coordenadas para reproducir bellas composiciones.",
		card_3_title: "Procesamiento por lotes",
		card_3_desc: "Exportación, restauración, transferencia, eliminación y movimiento por lotes con detección inteligente de duplicados.",
		card_4_title: "Live Photo & Creador de GIF",
		card_4_desc: "Convierte vídeos o álbumes dinámicos en GIF animados o Live Photos de macOS con un solo clic.",
		card_5_title: "Exportación fácil",
		card_5_desc: "Copiar al portapapeles, exportar sin pérdidas a la red local o a dispositivos de red.",
		footer_disclaimer: "Nikki Albums es una herramienta de código abierto y no está afiliada a Infinity Nikki ni a Papergames. Todos los derechos de autor pertenecen a sus respectivos propietarios.",
		modal_title: "Nota importante para usuarios de macOS",
		modal_desc: "Como es una aplicación portátil sin firmar, macOS Gatekeeper podría bloquearla en el primer inicio.<br><br>Sigue estos pasos para abrirla normalmente:<br>1. Si aparece un diálogo que dice \"Apple no puede comprobar si la aplicación contiene software malicioso\", haz clic en <b>OK</b>.<br>2. Abre <b>Ajustes del Sistema</b> > <b>Privacidad y seguridad</b>.<br>3. En la sección \"Seguridad\", busca el aviso sobre Nikki Albums y haz clic en <b>Abrir de todos modos</b>.<br>4. Introduce tu contraseña y confirma.",
		modal_btn: "Entendido"
	},
	it: {
		page_title: "Nikki Albums - Un gestore di album fotografici per Infinity Nikki",
		app_name: "Nikki Albums",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "Tutorial",
		nav_download: "Scarica",
		hero_title: "Nikki Albums",
		hero_desc: "Un gestore di album fotografici elegante ed efficiente pensato per i giocatori di Infinity Nikki",
		hero_subdesc: "Gestisci i tuoi album fotografici di gioco in modo facile ed efficiente. Completamente gratuito, open-source e tanpa pubblicità.",
		btn_download: "Scarica ora",
		btn_github: "Repository GitHub",
		compat_hint: "Supporta Windows 10/11 e macOS (Apple Silicon)",
		tab_wall: "Galleria Album",
		tab_decode: "Decodificatore metadati",
		card_1_title: "Gestione di Album Diversi",
		card_1_desc: "Supporta la visualizzazione di 19 categorie di album e 3 tipi di risorse interne del gioco, inclusi gli album video.",
		card_2_title: "Decodifica metadati",
		card_2_desc: "Decodifica automaticamente l'apertura, la lunghezza focale, i filtri e le coordinate per riprodurre splendide composizioni.",
		card_3_title: "Elaborazione in batch",
		card_3_desc: "Esportazione, ripristino, trasferimento, eliminazione e spostamento in batch con rilevamento intelligente dei duplicati.",
		card_4_title: "Live Photo & Creatore GIF",
		card_4_desc: "Converti video o album dinamici in GIF animate o Live Photo di macOS con un solo clic.",
		card_5_title: "Esportazione facile",
		card_5_desc: "Copia negli appunti, esportazione senza perdita di dati su rete locale o dispositivi di rete.",
		footer_disclaimer: "Nikki Albums è uno strumento open-source e non è affiliato a Infinity Nikki o Papergames. Tutti i diritti d'autore appartengono ai rispettivi proprietari.",
		modal_title: "Nota importante per gli utenti macOS",
		modal_desc: "Trattandosi di un'applicazione portabile non firmata, macOS Gatekeeper potrebbe bloccarla al primo avvio.<br><br>Segui questi passaggi per aprirla normalmente:<br>1. Se compare un avviso che dice \"Apple non può verificare la presenza di malware\", fai clic su <b>OK</b>.<br>2. Apri <b>Impostazioni di Sistema</b> > <b>Privacy e sicurezza</b>.<br>3. Nella sezione \"Sicurezza\", individua l'avviso su Nikki Albums e fai clic su <b>Apri comunque</b>.<br>4. Inserisci la tua password e conferma.",
		modal_btn: "Capito"
	},
	pt: {
		page_title: "Nikki Albums - Um gerenciador de álbuns de fotos para Infinity Nikki",
		app_name: "Nikki Albums",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "Tutorial",
		nav_download: "Baixar",
		hero_title: "Nikki Albums",
		hero_desc: "Um gerenciador de álbuns de fotos elegante e eficiente criado para jogadores de Infinity Nikki",
		hero_subdesc: "Gerencie seus álbuns de fotos do jogo de forma fácil e eficiente. Totalmente gratuito, de código aberto e sem anúncios.",
		btn_download: "Baixar agora",
		btn_github: "Repositório GitHub",
		compat_hint: "Suporta Windows 10/11 e macOS (Apple Silicon)",
		tab_wall: "Galeria de Álbuns",
		tab_decode: "Decodificador de metadados",
		card_1_title: "Gerenciamento de Álbuns Diversos",
		card_1_desc: "Suporta a exibição de 19 categorias de álbuns e 3 tipos de recursos internos do jogo, incluindo álbuns de vídeo.",
		card_2_title: "Decodificação de metadados",
		card_2_desc: "Decodifica automaticamente abertura, distância focal, filtros e coordenadas para reproduzir belas composições.",
		card_3_title: "Processamento em lote",
		card_3_desc: "Exportação, restauração, transferência, exclusão e movimentação em lote com detecção inteligente de duplicadas.",
		card_4_title: "Live Photo & Criador de GIF",
		card_4_desc: "Converta vídeos ou álbuns dinâmicos em GIFs animados ou Live Photos do macOS com um clique.",
		card_5_title: "Exportação fácil",
		card_5_desc: "Copiar para a área de transferência, exportar sem perdas para a rede local ou dispositivos de rede.",
		footer_disclaimer: "Nikki Albums é uma ferramenta de código aberto e não é afiliada à Infinity Nikki ou Papergames. Todos os direitos autorais pertencem aos seus respectivos proprietários.",
		modal_title: "Nota importante para usuários do macOS",
		modal_desc: "Como este é um aplicativo portátil sem assinatura oficial, o macOS Gatekeeper pode bloqueá-lo na primeira execução.<br><br>Siga estas etapas para abri-lo normalmente:<br>1. Se um aviso disser que a Apple não pode verificar se há malware, clique em <b>OK</b>.<br>2. Abra <b>Ajustes do Sistema</b> > <b>Privacidade e Segurança</b>.<br>3. Na seção \"Segurança\", localize a mensagem sobre o Nikki Albums e clique em <b>Abrir Mesmo Assim</b>.<br>4. Digite a sua senha e confirme.",
		modal_btn: "Entendido"
	},
	id: {
		page_title: "Nikki Albums - Pengelola album foto untuk Infinity Nikki",
		app_name: "Nikki Albums",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "Tutorial",
		nav_download: "Unduh",
		hero_title: "Nikki Albums",
		hero_desc: "Pengelola album foto yang elegan dan efisien untuk pemain Infinity Nikki",
		hero_subdesc: "Kelola album foto game Anda dengan mudah dan efisien. Sepenuhnya gratis, open-source, dan tanpa iklan.",
		btn_download: "Unduh Sekarang",
		btn_github: "Repositori GitHub",
		compat_hint: "Mendukung Windows 10/11 & macOS (Apple Silicon)",
		tab_wall: "Galeri Album",
		tab_decode: "Dekoder Metadata",
		card_1_title: "Pengelolaan Album Beragam",
		card_1_desc: "Mendukung tampilan 19 kategori album dan 3 jenis sumber daya internal game, termasuk album video.",
		card_2_title: "Dekode Metadata",
		card_2_desc: "Mendekode secara otomatis bukaan kamera, panjang fokus, filter, dan koordinat untuk mempermudah reproduksi komposisi indah.",
		card_3_title: "Pemrosesan Massal",
		card_3_desc: "Ekspor, pulihkan, transfer, hapus, dan pindahkan secara massal dilengkapi pendeteksi duplikasi cerdas.",
		card_4_title: "Live Photo & Pembuat GIF",
		card_4_desc: "Konversi video atau album dinamis menjadi GIF animasi atau Live Photo macOS secara instan.",
		card_5_title: "Ekspor Mudah",
		card_5_desc: "Salin ke papan klip, ekspor tanpa penurunan kualitas ke jaringan lokal atau perangkat jaringan.",
		footer_disclaimer: "Nikki Albums adalah alat sumber terbuka dan tidak berafiliasi dengan Infinity Nikki atau Papergames. Hak cipta materi milik pemilik aslinya.",
		modal_title: "Pemberitahuan Penting untuk Pengguna macOS",
		modal_desc: "Karena ini adalah aplikasi portabel yang tidak ditandatangani secara resmi, macOS Gatekeeper mungkin memblokirnya pada peluncuran pertama.<br><br>Silakan ikuti langkah-langkah berikut untuk membukanya secara normal:<br>1. Jika muncul dialog \"Apple tidak dapat memeriksa apakah aplikasi mengandung malware\", klik <b>OK</b>.<br>2. Buka <b>Pengaturan Sistem</b> > <b>Privasi & Keamanan</b>.<br>3. Di bawah bagian \"Keamanan\", cari pesan tentang Nikki Albums lalu klik <b>Tetap Buka</b>.<br>4. Masukkan kata sandi komputer Anda lalu konfirmasi.",
		modal_btn: "Saya mengerti"
	},
	th: {
		page_title: "Nikki Albums - เครื่องมือจัดการอัลบั้มรูปภาพสำหรับ Infinity Nikki",
		app_name: "Nikki Albums",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "บทช่วยสอน",
		nav_download: "ดาวน์โหลด",
		hero_title: "Nikki Albums",
		hero_desc: "ซอฟต์แวร์จัดการอัลบั้มรูปภาพที่หรูหราและมีประสิทธิภาพสำหรับผู้เล่น Infinity Nikki",
		hero_subdesc: "จัดการอัลบั้มรูปภาพในเกมได้อย่างง่ายดายและมีประสิทธิภาพ ฟรี เปิดเผยซอร์สโค้ด และไม่มีโฆษณา",
		btn_download: "ดาวน์โหลดทันที",
		btn_github: "พื้นที่จัดเก็บ GitHub",
		compat_hint: "รองรับ Windows 10/11 และ macOS (Apple Silicon)",
		tab_wall: "ภาพรวมอัลบั้ม",
		tab_decode: "ตัวถอดรหัสพารามิเตอร์",
		card_1_title: "การจัดการอัลบั้มที่หลากหลาย",
		card_1_desc: "รองรับการดูอัลบั้ม 19 ประเภท และทรัพยากรภายในเกม 3 ประเภท รวมถึงอัลบั้มวิดีโอ",
		card_2_title: "การถอดรหัสพารามิเตอร์กล้อง",
		card_2_desc: "ถอดรหัสรูรับแสงกล้อง ความยาวโฟกัส พารามิเตอร์ฟิลเตอร์ และพิกัดการถ่ายภาพโดยอัตโนมัติ ช่วยให้เลียนแบบมุมมองที่สวยงามได้อย่างง่ายดาย",
		card_3_title: "การดำเนินการเป็นกลุ่มที่มีประสิทธิภาพ",
		card_3_desc: "รองรับการส่งออกเป็นกลุ่ม กู้คืน โอน ลบ และย้ายข้อมูล พร้อมระบบลบไฟล์ซ้ำอัจฉริยะในตัว",
		card_4_title: "การแปลงภาพเคลื่อนไหวและภาพสด",
		card_4_desc: "แปลงวิดีโอหรืออัลบั้มภาพเคลื่อนไหวเป็นภาพเคลื่อนไหว GIF หรือภาพสด (Live Photo) ของระบบ macOS ได้ในคลิกเดียว",
		card_5_title: "การส่งออกและแบ่งปันผ่านหลายช่องทาง",
		card_5_desc: "รองรับการคัดลอกไปยังคลิปบอร์ด ส่งออกข้อมูลแบบไม่สูญเสียความละเอียดผ่าน LAN หรืออุปกรณ์เครือข่ายเดียวกัน",
		footer_disclaimer: "Nikki Albums เป็นเครื่องมือเปิดเผยซอร์สโค้ดและไม่ได้เกี่ยวข้องกับ Infinity Nikki หรือ Papergames ลิขสิทธิ์ของเนื้อหาทั้งหมดเป็นของบริษัทผู้พัฒนาดั้งเดิม",
		modal_title: "คำแนะนำที่สำคัญสำหรับการเรียกใช้งาน macOS เป็นครั้งแรก",
		modal_desc: "เนื่องจากโปรแกรมปัจจุบันเป็นเวอร์ชันพกพาที่ไม่มีการลงนามดิจิทัล ระบบอาจสกัดกั้นการเปิดใช้งานในครั้งแรก<br><br>โปรดปฏิบัติตามขั้นตอนต่อไปนี้เพื่อเปิดตามปกติ:<br>1. หากมีข้อความแจ้งเตือน \"Apple ไม่สามารถตรวจสอบแอปเพื่อหาซอฟต์แวร์ที่เป็นอันตรายได้\" โปรดคลิก <b>ตกลง</b><br>2. เปิด <b>การตั้งค่าระบบ</b> > <b>ความเป็นส่วนตัวและความปลอดภัย</b><br>3. 去到ส่วน \"ความปลอดภัย\" ค้นหาข้อความแจ้งเตือนเกี่ยวกับ Nikki Albums แล้วคลิก <b>เปิดต่อไป</b><br>4. ป้อนรหัสผ่านการเข้าสู่ระบบของคุณแล้วคลิก <b>ตกลง</b>",
		modal_btn: "ฉันเข้าใจแล้ว"
	}
};
