// Translation Dictionary for Landing Page
const i18n = {
	zh: {
		page_title: "暖暖相册 - 一款用于管理你的无限暖暖相册的工具",
		app_name: "暖暖相册",
		nav_qq: "交流群1062670402",
		nav_tutorial: "教程",
		nav_download: "下载",
		hero_title: "暖暖相册",
		hero_desc: "一款专为《无限暖暖》玩家精心打造的相册管理软件",
		hero_subdesc: "轻松、高效地管理游戏相册，让游戏体验更加畅快无忧。免费开源，无广告。",
		btn_download: "立即下载",
		btn_github: "GitHub 仓库",
		compat_hint: "支持 Windows 10/11 和 macOS (M系列芯片)",
		tab_wall: "相册概览",
		tab_decode: "参数解码",
		card_1_title: "全方位相册管理",
		card_1_desc: "支持查看 19 类相册与 3 类内部资源，深度适配日常、趣拼、动态影集等多种分类。",
		card_2_title: "相机参数解析",
		card_2_desc: "自动解析相机光圈、焦距、滤镜参数及拍摄坐标，助你轻松复现精美构图。",
		card_3_title: "高效批量处理",
		card_3_desc: "支持批量导出、还原、转移、删除，内置智能去重功能，让相册管理更省心。",
		card_4_title: "动图与实况转换",
		card_4_desc: "一键将视频或动态影集转换为苹果或安卓兼容的实况照片 (Live Photo) 或 GIF 动图。",
		card_5_title: "多渠道无损分享",
		card_5_desc: "支持一键复制到剪贴板，通过本地硬盘或局域网无损导出，分享快人一步。",
		footer_disclaimer: "暖暖相册并非《无限暖暖》官方或叠纸游戏的官方产品。所有素材版权归原公司所有。",
		footer_friendship_link: "友情链接",
		footer_friendship_link_buildingmomo: "搬砖吧大喵",
		footer_friendship_link_gongeous: "暖暖共鸣录",
		modal_title: "首次运行 macOS 版的重要提示",
		modal_desc: "由于当前程序是免签名的便携版，首次打开可能会被系统拦截。<br><br>请按照以下步骤正常打开：<br>1. 若弹出“Apple 无法检查 App 是否包含恶意软件”，请点按 <b>好</b>。<br>2. 打开系统的 <b>系统设置</b> > <b>隐私与安全性</b>。<br>3. 前往“安全性”部分，找到关于 Nikki Albums 的提示，然后点按 <b>打开</b>。<br>4. 点按 <b>仍要打开</b>，输入你的登录密码，然后点按 <b>好</b>。",
		modal_btn: "我已了解"
	},
	"zh-tw": {
		page_title: "暖暖相簿 - 一款用於管理您的《無限暖暖》相簿的工具",
		app_name: "暖暖相簿",
		nav_qq: "交流群組 1062670402",
		nav_tutorial: "教學",
		nav_download: "下載",
		hero_title: "暖暖相簿",
		hero_desc: "一款專為《無限暖暖》玩家精心打造的相簿管理軟體",
		hero_subdesc: "輕鬆、高效地管理遊戲相簿，讓遊戲體驗更加暢快無憂。免費開源，無廣告。",
		btn_download: "立即下載",
		btn_github: "GitHub 儲存庫",
		compat_hint: "支援 Windows 10/11 和 macOS (M系列晶片)",
		tab_wall: "相簿概覽",
		tab_decode: "參數解碼",
		card_1_title: "全方位相簿管理",
		card_1_desc: "支援查看 19 類相簿與 3 類內部資源，完美支援日常、趣拼、動態相簿等多種分類。",
		card_2_title: "相機參數解析",
		card_2_desc: "自動解析相機光圈、焦距、濾鏡參數及拍攝座標，助您輕鬆復現精美構圖。",
		card_3_title: "高效批次處理",
		card_3_desc: "支援批次匯出、還原、轉移、刪除，內建智慧排除重複功能，讓相簿管理更省心。",
		card_4_title: "動圖與原況照片轉換",
		card_4_desc: "一鍵將影片或動態相簿轉換為 Apple 或 Android 相容的原況照片 (Live Photo) 或 GIF 動圖。",
		card_5_title: "多管道無損分享",
		card_5_desc: "支援一鍵複製到剪貼簿，透過本地硬碟或區域網路無損匯出，分享更加即時。",
		footer_disclaimer: "暖暖相簿並非《無限暖暖》官方或疊紙遊戲的官方產品。所有素材版權歸原公司所有。",
		footer_friendship_link: "友友誼連結",
		footer_friendship_link_buildingmomo: "搬砖吧大喵",
		footer_friendship_link_gongeous: "暖暖共鳴錄",
		modal_title: "首次執行 macOS 版的重要提示",
		modal_desc: "由於當前程式是免簽名的免安裝版，首次打開可能會被系統攔截。<br><br>請按照以下步驟正常打開：<br>1. 若彈出「Apple 無法檢查 App 是否含有惡意軟件/軟體」，請按一下 <b>好</b>。<br>2. 選擇「蘋果」選單 > <b>系統設定</b>，在側邊欄按一下 <b>私隱與保安（或隱私權與安全性）</b>。（您可能需要向下捲動。）<br>3. 前往「保安（或安全性）」部分，找到關於 Nikki Albums 的提示，按一下 <b>開啟（或打開）</b>。<br>4. 按一下 <b>強制開啟（或強制打開）</b>，輸入您的登入密碼，然後按一下 <b>好</b>。",
		modal_btn: "我已了解",
	},
	en: {
		page_title: "Nikki Albums - A photo album manager for Infinity Nikki",
		app_name: "Nikki Albums",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "Tutorial",
		nav_download: "Download",
		hero_title: "Nikki Albums",
		hero_desc: "An elegant and efficient photo album manager built for Infinity Nikki players",
		hero_subdesc: "Easily manage your in-game photo albums across multiple accounts. Fully open-source and completely free.",
		btn_download: "Download Now",
		btn_github: "GitHub Repo",
		compat_hint: "Supports Windows 10/11 & macOS (Apple Silicon)",
		tab_wall: "Album Showcase",
		tab_decode: "Metadata Decoder",
		card_1_title: "All-in-one Album Management",
		card_1_desc: "View 19 album categories and 3 internal resource types, fully optimized for daily, collage, and video albums.",
		card_2_title: "Metadata Analysis",
		card_2_desc: "Automatically analyze aperture, focal length, filters, and coordinates to help you recreate perfect shots.",
		card_3_title: "Efficient Batch Processing",
		card_3_desc: "Batch export, restore, transfer, and delete with built-in smart duplicate detection.",
		card_4_title: "Live Photo & GIF Converter",
		card_4_desc: "Convert video albums to Apple or Android compatible Live Photos or animated GIFs in one click.",
		card_5_title: "Lossless Sharing",
		card_5_desc: "Copy to clipboard or export losslessly via local drive or LAN for lightning-fast sharing.",
		footer_disclaimer: "Nikki Albums is an open-source tool and is not affiliated with Infinity Nikki or Papergames. All copyrights belong to their respective owners.",
		footer_friendship_link: "Friendship Link",
		footer_friendship_link_buildingmomo: "BuildingMomo",
		footer_friendship_link_gongeous: "Resonance Tracker",
		modal_title: "Important Note for macOS Users",
		modal_desc: "Since this is an ad-hoc signed app, macOS Gatekeeper might block it on the first run.<br><br>Please follow these steps to open it normally:<br>1. If a dialog says \"Apple can't check app for malicious software\", click <b>OK</b>.<br>2. Open <b>System Settings</b> > <b>Privacy & Security</b>.<br>3. Under the \"Security\" section, locate Nikki Albums and click <b>Open</b>.<br>4. Click <b>Open Anyway</b>, enter your login password, and click <b>OK</b>.",
		modal_btn: "Got it"
	},
	ja: {
		page_title: "ニキアルバム - インフィニティニキの写真アルバム管理ツール",
		app_name: "ニキアルバム",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "チュートリアル",
		nav_download: "ダウンロード",
		hero_title: "ニキアルバム",
		hero_desc: "『インフィニティニキ』プレイヤーのために設計されたアルバム管理ソフト",
		hero_subdesc: "ゲーム内の写真アルバムを簡単に効率よく管理。完全無料でオープンソース、広告なし。",
		btn_download: "今すぐダウンロード",
		btn_github: "GitHub リポジトリ",
		compat_hint: "Windows 10/11 および macOS (Apple Silicon) に対応",
		tab_wall: "アルバム一覧",
		tab_decode: "パラメータ解析",
		card_1_title: "総合的なアルバム管理",
		card_1_desc: "19種類のアルバムと3種類の内部リソースに対応。日常、コラージュ、動画アルバムなどを完璧にサポート。",
		card_2_title: "撮影パラメータ解析",
		card_2_desc: "絞り、焦点距離、フィルター、撮影座標を自動解析し、美しい構図の再現をサポート。",
		card_3_title: "効率的な一括処理",
		card_3_desc: "一括書き出し、復元、転送、削除に対応。重複検出機能でアルバム管理をよりスマートに。",
		card_4_title: "Live Photo・GIF変換",
		card_4_desc: "動画アルバムをワンクリックでAppleまたはAndroid互換のLive PhotoやGIFに変換。",
		card_5_title: "多彩な無劣化共有",
		card_5_desc: "クリップボードへのコピー、ローカルディスクやLAN経由の無劣化転送で、素早く共有。",
		footer_disclaimer: "『ニキアルバム』はオープンソースのツールであり、インフィニティニキ公式やPapergamesとは一切関係ありません。すべての素材の著作権は原権利者に帰属します。",
		footer_friendship_link: "Friendship Link",
		footer_friendship_link_buildingmomo: "BuildingMomo",
		footer_friendship_link_gongeous: "ィニキ 共鳴録",
		modal_title: "macOS版の初回実行に関する重要なお知らせ",
		modal_desc: "署名なしのポータブル版であるため、初回起動時にmacOSによってブロックされる場合があります。<br><br>以下の手順に従って正常に開いてください：<br>1. 「Appleは悪質なソフトウェアがないか確認できません」と表示された場合は、<b>OK</b>をクリックします。<br>2. <b>システム設定</b> > <b>プライバシーとセキュリティ</b>を開きます。<br>3. セキュリティ欄にあるNikki Albumsの起動に関するメッセージを確認し、<b>このまま開く</b>をクリックします。<br>4. ログインパスワードを入力し、<b>OK</b>をクリックします。",
		modal_btn: "了解しました"
	},
	ko: {
		page_title: "니키 앨범 - 인피니티 니키 사진 앨범 관리 도구",
		app_name: "니키 앨범",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "튜토리얼",
		nav_download: "다운로드",
		hero_title: "니키 앨범",
		hero_desc: "인피니티 니키 플레이어를 위해 특별히 제작된 앨범 관리 소프트웨어",
		hero_subdesc: "게임 앨범을 쉽고 효율적으로 관리하여 더욱 쾌적한 게임 경험을 선사합니다. 광고 없는 완전 무료 오픈 소스.",
		btn_download: "지금 다운로드",
		btn_github: "GitHub 저장소",
		compat_hint: "Windows 10/11 및 macOS (Apple Silicon) 지원",
		tab_wall: "앨범 개요",
		tab_decode: "파라미터 디코더",
		card_1_title: "올인원 앨범 관리",
		card_1_desc: "19개 앨범 카테고리와 3개 내부 리소스 지원. 일상, 퍼즐, 동영상 앨범 등 완벽 대응.",
		card_2_title: "카메라 파라미터 분석",
		card_2_desc: "조리개, 초점 거리, 필터 및 촬영 좌표를 자동 분석하여 완벽한 구도 재현 지원.",
		card_3_title: "효율적인 일괄 처리",
		card_3_desc: "일괄 내보내기, 복원, 전송, 삭제 지원. 스마트 중복 제거로 간편한 관리.",
		card_4_title: "라이브 포토 & GIF 변환",
		card_4_desc: "동영상 앨범을 원클릭으로 Apple 또는 Android 호환 라이브 포토나 GIF로 변환.",
		card_5_title: "다채널 무손실 공유",
		card_5_desc: "클립보드 복사, 로컬 드라이브 또는 LAN을 통한 무손실 내보내기로 빠른 공유 가능.",
		footer_disclaimer: "니키 앨범 는 오픈 소스 도구이며 인피니티 니키 공식 또는 Papergames와 관련이 없습니다. 모든 자료의 저작권은 해당 회사에 있습니다.",
		footer_friendship_link: "Friendship Link",
		footer_friendship_link_buildingmomo: "BuildingMomo",
		footer_friendship_link_gongeous: "공명 기록 및 스타일링 도우미",
		modal_title: "macOS 버전 최초 실행 시 중요 안내",
		modal_desc: "본 앱은 서명되지 않은 포터블 버전으로, 최초 실행 시 시스템에 의해 차단될 수 있습니다.<br><br>정상적으로 실행하려면 다음 단계를 따르십시오:<br>1. \"Apple에서 악성 소프트웨어가 있는지 확인할 수 없습니다\"라는 팝업이 뜨면 <b>확인</b>을 클릭합니다.<br>2. 시스템의 <b>설정</b> > <b>개인정보 보호 및 보안</b>을 엽니다.<br>3. 보안 섹션에서 Nikki Albums 관련 안내를 찾아 <b>열기</b>를 클릭합니다.<br>4. <b>계속 열기</b>를 클릭하고 컴퓨터 암호를 입력한 뒤 <b>확인</b>을 클릭합니다.",
		modal_btn: "확인 완료"
	},
	fr: {
		page_title: "Albums de Nikki - Un gestionnaire d'albums photo pour Infinity Nikki",
		app_name: "Albums de Nikki",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "Tutoriel",
		nav_download: "Télécharger",
		hero_title: "Albums de Nikki",
		hero_desc: "Un gestionnaire d'albums photo élégant et efficace conçu pour les joueurs d'Infinity Nikki",
		hero_subdesc: "Gerez facilement et efficacement vos albums photo de jeu. Entièrement gratuit, open-source et sans publicité.",
		btn_download: "Télécharger maintenant",
		btn_github: "Dépôt GitHub",
		compat_hint: "Prend en charge Windows 10/11 et macOS (Apple Silicon)",
		tab_wall: "Galerie d'Albums",
		tab_decode: "Décodeur de métadonnées",
		card_1_title: "Gestion d'Albums Complète",
		card_1_desc: "Gerez 19 catégories d'albums et 3 types de ressources internes, optimisés pour tous vos souvenirs.",
		card_2_title: "Analyse des Métadonnées",
		card_2_desc: "Analyse l'ouverture, la focale, les filtres et les coordonnées pour recréer vos meilleures prises.",
		card_3_title: "Traitement par Lots Efficace",
		card_3_desc: "Exportation, restauration, transfert et suppression par lots avec détection intelligente des doublons.",
		card_4_title: "Convertisseur Live Photo & GIF",
		card_4_desc: "Convertissez vos vidéos en Live Photos (compatible Apple/Android) ou GIFs animés en un clic.",
		card_5_title: "Partage Sans Perte",
		card_5_desc: "Copie dans le presse-papiers ou export sans perte via disque local ou LAN pour un partage rapide.",
		footer_disclaimer: "Albums de Nikki est un outil open-source non affilié à Infinity Nikki ou Papergames. Tous les droits d'auteur appartiennent à leurs propriétaires respectifs.",
		footer_friendship_link: "Friendship Link",
		footer_friendship_link_buildingmomo: "BuildingMomo",
		footer_friendship_link_gongeous: "Suivi de Résonance et compagnon de style",
		modal_title: "Note importante pour les utilisateurs macOS",
		modal_desc: "Puisqu'il s'agit d'une application portable signée ad-hoc, macOS Gatekeeper peut la bloquer lors du premier lancement.<br><br>Veuillez suivre ces étapes pour l'ouvrir normalement :<br>1. Si une boîte de dialogue indique \"Apple ne peut pas vérifier si l'application contient des logiciels malveillants\", cliquez sur <b>OK</b>.<br>2. Ouvrez <b>Réglages Système</b> > <b>Confidentialité et sécurité</b>.<br>3. Dans la section \"Sécurité\", localisez l'avis Nikki Albums et cliquez sur <b>Ouvrir quand même</b>.<br>4. Entrez votre mot de passe et validez.",
		modal_btn: "J'ai compris"
	},
	de: {
		page_title: "Nikki Alben - Ein Fotoalbum-Manager für Infinity Nikki",
		app_name: "Nikki Alben",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "Tutorial",
		nav_download: "Herunterladen",
		hero_title: "Nikki Alben",
		hero_desc: "Ein eleganter und effizienter Fotoalbum-Manager für Spieler von Infinity Nikki",
		hero_subdesc: "Verwalten Sie Ihre Fotoalben im Spiel einfach und effizient. Völlig kostenlos, Open-Source und werbefrei.",
		btn_download: "Jetzt herunterladen",
		btn_github: "GitHub-Repository",
		compat_hint: "Unterstützt Windows 10/11 & macOS (Apple Silicon)",
		tab_wall: "Album-Galerie",
		tab_decode: "Metadaten-Decoder",
		card_1_title: "Umfassende Alben-Verwaltung",
		card_1_desc: "Unterstützt 19 Albenkategorien und 3 interne Ressourcentypen, optimiert für alle Bildformate.",
		card_2_title: "Metadaten-Analyse",
		card_2_desc: "Analysiert Blende, Brennweite, Filter und Koordinaten, um perfekte Kompositionen zu reproduzieren.",
		card_3_title: "Effiziente Stapelverarbeitung",
		card_3_desc: "Massenexport, Wiederherstellung, Übertragung und Löschung mit intelligenter Duplikaterkennung.",
		card_4_title: "Live Photo & GIF Konverter",
		card_4_desc: "Konvertieren Sie Videoalben in Apple- oder Android-kompatible Live Photos oder animierte GIFs.",
		card_5_title: "Verlustfreies Teilen",
		card_5_desc: "In die Zwischenablage kopieren oder verlustfrei über lokale Festplatte oder LAN exportieren.",
		footer_disclaimer: "Nikki Alben ist ein Open-Source-Tool und steht in keiner Verbindung zu Infinity Nikki oder Papergames. Alle Urheberrechte liegen bei ihren jeweiligen Eigentümern.",
		footer_friendship_link: "Friendship Link",
		footer_friendship_link_buildingmomo: "BuildingMomo",
		footer_friendship_link_gongeous: "Resonanz-Tracker & Styling-Begleiter",
		modal_title: "Wichtiger Hinweis für macOS-Benutzer",
		modal_desc: "Da es sich um eine nicht signierte portable Anwendung handelt, blockiert macOS Gatekeeper sie möglicherweise beim ersten Start.<br><br>Bitte befolgen Sie diese Schritte, um sie normal zu öffnen:<br>1. Wenn ein Dialogfeld meldet, dass Apple die App nicht auf Schadsoftware überprüfen kann, klicken Sie auf <b>OK</b>.<br>2. Öffnen Sie die <b>Systemeinstellungen</b> > <b>Datenschutz & Sicherheit</b>.<br>3. Suchen Sie im Bereich „Sicherheit“ nach dem Hinweis zu Nikki Albums und klicken Sie auf <b>Dennoch öffnen</b>.<br>4. Geben Sie Ihr Passwort ein und bestätigen Sie.",
		modal_btn: "Verstanden"
	},
	es: {
		page_title: "Álbumes de Nikki - Un gestor de álbumes de fotos para Infinity Nikki",
		app_name: "Álbumes de Nikki",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "Tutorial",
		nav_download: "Descargar",
		hero_title: "Álbumes de Nikki",
		hero_desc: "Un gestor de álbumes de fotos elegante y eficiente diseñado para jugadores de Infinity Nikki",
		hero_subdesc: "Gestiona tus álbumes de fotos del juego de forma fácil y eficaz. Totalmente gratuito, de código abierto y sin anuncios.",
		btn_download: "Descargar ahora",
		btn_github: "Repositorio GitHub",
		compat_hint: "Soporta Windows 10/11 y macOS (Apple Silicon)",
		tab_wall: "Galería de Álbumes",
		tab_decode: "Decodificador de metadatos",
		card_1_title: "Gestión Integral de Álbumes",
		card_1_desc: "Soporta 19 categorías de álbumes y 3 tipos de recursos internos, optimizado para fotos y vídeos.",
		card_2_title: "Análisis de Metadatos",
		card_2_desc: "Analiza automáticamente apertura, distancia focal, filtros y coordenadas para recrear tomas perfectas.",
		card_3_title: "Procesamiento por Lotes Eficaz",
		card_3_desc: "Exportación, restauración, transferencia y eliminación por lotes con detección inteligente de duplicados.",
		card_4_title: "Conversor de Live Photo y GIF",
		card_4_desc: "Convierte vídeos en Live Photos (compatibles con Apple/Android) o GIFs animados con un clic.",
		card_5_title: "Compartir Sin Pérdidas",
		card_5_desc: "Copia al portapapeles o exporta sin pérdidas vía disco local o red para compartir rápidamente.",
		footer_disclaimer: "Álbumes de Nikki es una herramienta de código abierto y no está afiliada a Infinity Nikki ni a Papergames. Todos los derechos de autor pertenecen a sus respectivos propietarios.",
		footer_friendship_link: "Friendship Link",
		footer_friendship_link_buildingmomo: "BuildingMomo",
		footer_friendship_link_gongeous: "Rastreador de resonancia y compañero de estilismo",
		modal_title: "Nota importante para usuarios de macOS",
		modal_desc: "Como es una aplicación portátil sin firmar, macOS Gatekeeper podría bloquearla en el primer inicio.<br><br>Sigue estos pasos para abrirla normalmente:<br>1. Si aparece un diálogo que dice \"Apple no puede comprobar si la aplicación contiene software malicioso\", haz clic en <b>OK</b>.<br>2. Abre <b>Ajustes del Sistema</b> > <b>Privacidad y seguridad</b>.<br>3. En la sección \"Seguridad\", busca el aviso sobre Nikki Albums y haz clic en <b>Abrir de todos modos</b>.<br>4. Introduce tu contraseña y confirma.",
		modal_btn: "Entendido"
	},
	it: {
		page_title: "Album di Nikki - Un gestore di album fotografici per Infinity Nikki",
		app_name: "Album di Nikki",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "Tutorial",
		nav_download: "Scarica",
		hero_title: "Album di Nikki",
		hero_desc: "Un gestore di album fotografici elegante ed efficiente pensato per i giocatori di Infinity Nikki",
		hero_subdesc: "Gestisci i tuoi album fotografici di gioco in modo facile ed efficiente. Completamente gratuito, open-source e senza pubblicità.",
		btn_download: "Scarica ora",
		btn_github: "Repository GitHub",
		compat_hint: "Supporta Windows 10/11 e macOS (Apple Silicon)",
		tab_wall: "Galleria Album",
		tab_decode: "Decodificatore metadati",
		card_1_title: "Gestione Album Completa",
		card_1_desc: "Supporta 19 categorie di album e 3 tipi di risorse interne, ottimizzato per ogni tipo di contenuto.",
		card_2_title: "Analisi dei Metadati",
		card_2_desc: "Analizza apertura, focale, filtri e coordinate per aiutarti a ricreare i tuoi scatti migliori.",
		card_3_title: "Elaborazione Batch Efficiente",
		card_3_desc: "Esportazione, ripristino, trasferimento e rimozione batch con rilevamento intelligente dei duplicati.",
		card_4_title: "Convertitore Live Photo e GIF",
		card_4_desc: "Converti video in Live Photo (compatibili Apple/Android) o GIF animate in un solo clic.",
		card_5_title: "Condivisione Senza Perdita",
		card_5_desc: "Copia negli appunti o esporta senza perdita via disco locale o LAN per una condivisione veloce.",
		footer_disclaimer: "Album di Nikki è uno strumento open-source e non è affiliato a Infinity Nikki o Papergames. Tutti i diritti d'autore appartengono ai rispettivi proprietari.",
		footer_friendship_link: "Friendship Link",
		footer_friendship_link_buildingmomo: "BuildingMomo",
		footer_friendship_link_gongeous: "Tracker di risonanza e compagno di styling",
		modal_title: "Nota importante per gli utenti macOS",
		modal_desc: "Trattandosi di un'applicazione portabile non firmata, macOS Gatekeeper potrebbe bloccarla al primo avvio.<br><br>Segui questi passaggi per aprirla normalmente:<br>1. Se compare un avviso che dice \"Apple non può verificare la presenza di malware\", fai clic su <b>OK</b>.<br>2. Apri <b>Impostazioni di Sistema</b> > <b>Privacy e sicurezza</b>.<br>3. Nella sezione \"Sicurezza\", individua l'avviso su Nikki Albums e fai clic su <b>Apri comunque</b>.<br>4. Inserisci la tua password e conferma.",
		modal_btn: "Capito"
	},
	pt: {
		page_title: "Álbuns da Nikki - Um gerenciador de álbuns de fotos para Infinity Nikki",
		app_name: "Álbuns da Nikki",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "Tutorial",
		nav_download: "Baixar",
		hero_title: "Álbuns da Nikki",
		hero_desc: "Um gerenciador de álbuns de fotos elegante e eficiente criado para jogadores de Infinity Nikki",
		hero_subdesc: "Gerencie seus álbuns de fotos do jogo de forma fácil e eficiente. Totalmente gratuito, de código aberto e sem anúncios.",
		btn_download: "Baixar agora",
		btn_github: "Repositório GitHub",
		compat_hint: "Suporta Windows 10/11 e macOS (Apple Silicon)",
		tab_wall: "Galeria de Álbuns",
		tab_decode: "Decodificador de metadados",
		card_1_title: "Gestão Abrangente de Álbuns",
		card_1_desc: "Suporta 19 categorias de álbuns e 3 tipos de recursos internos, otimizado para todos os formatos.",
		card_2_title: "Análise de Metadados",
		card_2_desc: "Analisa abertura, distância focal, filtros e coordenadas para ajudar a recriar fotos perfeitas.",
		card_3_title: "Processamento em Lote Eficiente",
		card_3_desc: "Exportação, restauração, transferência e eliminação em lote com deteção inteligente de duplicados.",
		card_4_title: "Conversor de Live Photo e GIF",
		card_4_desc: "Converta vídeos em Live Photos (compatíveis com Apple/Android) o GIFs animados num clique.",
		card_5_title: "Partilha Sem Perdas",
		card_5_desc: "Copie para a área de transferência o exporte sem perdas via disco local ou rede local.",
		footer_disclaimer: "Álbuns da Nikki é uma ferramenta de código aberto e não é afiliada à Infinity Nikki ou Papergames. Todos os direitos autorais pertencem aos seus respectivos proprietários.",
		footer_friendship_link: "Friendship Link",
		footer_friendship_link_buildingmomo: "BuildingMomo",
		footer_friendship_link_gongeous: "Rastreador de Ressonância e companheiro de estilo",
		modal_title: "Nota importante para usuários do macOS",
		modal_desc: "Como este é um aplicativo portátil sem assinatura oficial, o macOS Gatekeeper pode bloqueá-lo na primeira execução.<br><br>Siga estas etapas para abri-lo normalmente:<br>1. Se um aviso disser que a Apple não pode verificar se há malware, clique em <b>OK</b>.<br>2. Abra <b>Ajustes do Sistema</b> > <b>Privacidade e Segurança</b>.<br>3. Na seção \"Segurança\", localize a mensagem sobre o Nikki Albums e clique em <b>Abrir Mesmo Assim</b>.<br>4. Digite a sua senha e confirme.",
		modal_btn: "Entendido"
	},
	id: {
		page_title: "Album Nikki - Pengelola album foto untuk Infinity Nikki",
		app_name: "Album Nikki",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "Tutorial",
		nav_download: "Unduh",
		hero_title: "Album Nikki",
		hero_desc: "Pengelola album foto yang elegan dan efisien untuk pemain Infinity Nikki",
		hero_subdesc: "Kelola album foto game Anda dengan mudah dan efisien. Sepenuhnya gratis, open-source, dan tanpa iklan.",
		btn_download: "Unduh Sekarang",
		btn_github: "Repositori GitHub",
		compat_hint: "Mendukung Windows 10/11 & macOS (Apple Silicon)",
		tab_wall: "Galeri Album",
		tab_decode: "Dekoder Metadata",
		card_1_title: "Manajemen Album Menyeluruh",
		card_1_desc: "Mendukung 19 kategori album dan 3 jenis sumber daya internal, dioptimalkan untuk semua format.",
		card_2_title: "Analisis Metadata Kamera",
		card_2_desc: "Menganalisis bukaan, panjang fokus, filter, dan koordinat untuk mempermudah reproduksi komposisi.",
		card_3_title: "Pemrosesan Massal Efisien",
		card_3_desc: "Ekspor, pulihkan, transfer, dan hapus massal dengan fitur deteksi duplikasi cerdas.",
		card_4_title: "Konverter Live Photo & GIF",
		card_4_desc: "Konversi album video menjadi Live Photo (kompatibel Apple/Android) atau GIF dalam satu klik.",
		card_5_title: "Berbagi Tanpa Penurunan Kualitas",
		card_5_desc: "Salin ke papan klip atau ekspor tanpa kehilangan kualitas via drive lokal atau LAN.",
		footer_disclaimer: "Album Nikki adalah alat sumber terbuka dan tidak berafiliasi dengan Infinity Nikki atau Papergames. Hak cipta materi milik pemilik aslinya.",
		footer_friendship_link: "Friendship Link",
		footer_friendship_link_buildingmomo: "BuildingMomo",
		footer_friendship_link_gongeous: "Resonance Tracker",
		modal_title: "Pemberitahuan Penting untuk Pengguna macOS",
		modal_desc: "Karena ini adalah aplikasi portabel yang tidak ditandatangani secara resmi, macOS Gatekeeper mungkin memblokirnya pada peluncuran pertama.<br><br>Silakan ikuti langkah-langkah berikut untuk membukanya secara normal:<br>1. Jika muncul dialog \"Apple tidak dapat memeriksa apakah aplikasi mengandung malware\", klik <b>OK</b>.<br>2. Buka <b>Pengaturan Sistem</b> > <b>Privasi & Keamanan</b>.<br>3. Di bawah bagian \"Keamanan\", cari pesan tentang Nikki Albums lalu klik <b>Tetap Buka</b>.<br>4. Masukkan kata sandi komputer Anda lalu konfirmasi.",
		modal_btn: "Saya mengerti"
	},
	th: {
		page_title: "อัลบั้มนิกกี้ - เครื่องมือจัดการอัลบั้มรูปภาพสำหรับ Infinity Nikki",
		app_name: "อัลบั้มนิกกี้",
		nav_qq: "QQ Group 1062670402",
		nav_tutorial: "บทช่วยสอน",
		nav_download: "ดาวน์โหลด",
		hero_title: "อัลบั้มนิกกี้",
		hero_desc: "ซอฟต์แวร์จัดการอัลบั้มรูปภาพที่หรูหราและมีประสิทธิภาพสำหรับผู้เล่น Infinity Nikki",
		hero_subdesc: "จัดการอัลบั้มรูปภาพในเกมได้อย่างง่ายดายและมีประสิทธิภาพ ฟรี เปิดเผยซอร์สโค้ด และไม่มีโฆษณา",
		btn_download: "ดาวน์โหลดทันที",
		btn_github: "พื้นที่จัดเก็บ GitHub",
		compat_hint: "รองรับ Windows 10/11 และ macOS (Apple Silicon)",
		tab_wall: "ภาพรวมอัลบั้ม",
		tab_decode: "ตัวถอดรหัสพารามิเตอร์",
		card_1_title: "การจัดการอัลบั้มแบบครบวงจร",
		card_1_desc: "รองรับอัลบั้ม 19 ประเภทและทรัพยากรภายใน 3 ประเภท ปรับแต่งมาเพื่ออัลบั้มรูปและวิดีโอทุกรูปแบบ",
		card_2_title: "การวิเคราะห์พารามิเตอร์กล้อง",
		card_2_desc: "วิเคราะห์รูรับแสง ความยาวโฟกัส ฟิลเตอร์ และพิกัดโดยอัตโนมัติ ช่วยให้คุณถ่ายภาพซ้ำได้อย่างแม่นยำ",
		card_3_title: "การประมวลผลแบบกลุ่มที่มีประสิทธิภาพ",
		card_3_desc: "ส่งออก กู้คืน โอน และลบแบบกลุ่ม พร้อมระบบตรวจจับไฟล์ซ้ำอัจฉริยะ",
		card_4_title: "ตัวแปลง Live Photo และ GIF",
		card_4_desc: "แปลงวิดีโอเป็น Live Photo (รองรับ Apple/Android) หรือไฟล์ GIF ได้ในคลิกเดียว",
		card_5_title: "การแชร์แบบไม่สูญเสียความละเอียด",
		card_5_desc: "คัดลอกไปยังคลิปบอร์ดหรือส่งออกผ่านไดรฟ์โลคอลหรือ LAN โดยไม่ลดทอนคุณภาพ",
		footer_disclaimer: "อัลบั้มนิกกี้ เป็นเครื่องมือเปิดเผยซอร์สโค้ดและไม่ได้เกี่ยวข้องกับ Infinity Nikki หรือ Papergames ลิขสิทธิ์ของเนื้อหาทั้งหมดเป็นของบริษัทผู้พัฒนาดั้งเดิม",
		footer_friendship_link: "Friendship Link",
		footer_friendship_link_buildingmomo: "BuildingMomo",
		footer_friendship_link_gongeous: "Resonance Tracker",
		modal_title: "คำแนะนำที่สำคัญสำหรับการเรียกใช้งาน macOS เป็นครั้งแรก",
		modal_desc: "เนื่องจากโปรแกรมปัจจุบันเป็นเวอร์ชันพกพาที่ไม่มีการลงนามดิจิทัล ระบบอาจสกัดกั้นการเปิดใช้งานในครั้งแรก<br><br>โปรดปฏิบัติตามขั้นตอนต่อไปนี้เพื่อเปิดตามปกติ:<br>1. หากมีข้อความแจ้งเตือน \"Apple ไม่สามารถตรวจสอบแอปเพื่อหาซอฟต์แวร์ที่เป็นอันตรายได้\" โปรดคลิก <b>ตกลง</b><br>2. เปิด <b>การตั้งค่าระบบ</b> > <b>ความเป็นส่วนตัวและความปลอดภัย</b><br>3. ไปที่ส่วน \"ความปลอดภัย\" ค้นหาข้อความแจ้งเตือนเกี่ยวกับ Nikki Albums แล้วคลิก <b>เปิดต่อไป</b><br>4. ป้อนรหัสผ่านการเข้าสู่ระบบของคุณแล้วคลิก <b>ตกลง</b>",
		modal_btn: "ฉันเข้าใจแล้ว"
	}
};
