// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deserialize`, `serialize`

class CameraParams {
  final PlatformInt64 flag;
  final PlatformInt64 portraitMode;
  final double dxCameraActor;
  final double dyCameraActor;
  final double dzCameraActor;
  final double dPitchCameraActor;
  final double dYawCameraActor;
  final PlatformInt64 mode;
  final double dxCameraComponent;
  final double dyCameraComponent;
  final double dzCameraComponent;
  final double dPitchCameraComponent;
  final double dYawCameraComponent;
  final double dRollCameraActor;
  final double cameraFocalLength;
  final int apertureSection;
  final double dRollCameraComponent;
  final String lightId;
  final double lightStrength;
  final double vignetteIntensity;
  final double bloomIntensity;
  final double bloomThreshold;
  final double brightness;
  final double exposure;
  final double contrast;
  final double saturation;
  final double vibrance;
  final double highlights;
  final double shadows;
  final String filterId;
  final double filterStrength;

  const CameraParams({
    required this.flag,
    required this.portraitMode,
    required this.dxCameraActor,
    required this.dyCameraActor,
    required this.dzCameraActor,
    required this.dPitchCameraActor,
    required this.dYawCameraActor,
    required this.mode,
    required this.dxCameraComponent,
    required this.dyCameraComponent,
    required this.dzCameraComponent,
    required this.dPitchCameraComponent,
    required this.dYawCameraComponent,
    required this.dRollCameraActor,
    required this.cameraFocalLength,
    required this.apertureSection,
    required this.dRollCameraComponent,
    required this.lightId,
    required this.lightStrength,
    required this.vignetteIntensity,
    required this.bloomIntensity,
    required this.bloomThreshold,
    required this.brightness,
    required this.exposure,
    required this.contrast,
    required this.saturation,
    required this.vibrance,
    required this.highlights,
    required this.shadows,
    required this.filterId,
    required this.filterStrength,
  });

  @override
  int get hashCode =>
      flag.hashCode ^
      portraitMode.hashCode ^
      dxCameraActor.hashCode ^
      dyCameraActor.hashCode ^
      dzCameraActor.hashCode ^
      dPitchCameraActor.hashCode ^
      dYawCameraActor.hashCode ^
      mode.hashCode ^
      dxCameraComponent.hashCode ^
      dyCameraComponent.hashCode ^
      dzCameraComponent.hashCode ^
      dPitchCameraComponent.hashCode ^
      dYawCameraComponent.hashCode ^
      dRollCameraActor.hashCode ^
      cameraFocalLength.hashCode ^
      apertureSection.hashCode ^
      dRollCameraComponent.hashCode ^
      lightId.hashCode ^
      lightStrength.hashCode ^
      vignetteIntensity.hashCode ^
      bloomIntensity.hashCode ^
      bloomThreshold.hashCode ^
      brightness.hashCode ^
      exposure.hashCode ^
      contrast.hashCode ^
      saturation.hashCode ^
      vibrance.hashCode ^
      highlights.hashCode ^
      shadows.hashCode ^
      filterId.hashCode ^
      filterStrength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CameraParams &&
          runtimeType == other.runtimeType &&
          flag == other.flag &&
          portraitMode == other.portraitMode &&
          dxCameraActor == other.dxCameraActor &&
          dyCameraActor == other.dyCameraActor &&
          dzCameraActor == other.dzCameraActor &&
          dPitchCameraActor == other.dPitchCameraActor &&
          dYawCameraActor == other.dYawCameraActor &&
          mode == other.mode &&
          dxCameraComponent == other.dxCameraComponent &&
          dyCameraComponent == other.dyCameraComponent &&
          dzCameraComponent == other.dzCameraComponent &&
          dPitchCameraComponent == other.dPitchCameraComponent &&
          dYawCameraComponent == other.dYawCameraComponent &&
          dRollCameraActor == other.dRollCameraActor &&
          cameraFocalLength == other.cameraFocalLength &&
          apertureSection == other.apertureSection &&
          dRollCameraComponent == other.dRollCameraComponent &&
          lightId == other.lightId &&
          lightStrength == other.lightStrength &&
          vignetteIntensity == other.vignetteIntensity &&
          bloomIntensity == other.bloomIntensity &&
          bloomThreshold == other.bloomThreshold &&
          brightness == other.brightness &&
          exposure == other.exposure &&
          contrast == other.contrast &&
          saturation == other.saturation &&
          vibrance == other.vibrance &&
          highlights == other.highlights &&
          shadows == other.shadows &&
          filterId == other.filterId &&
          filterStrength == other.filterStrength;
}
