// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../ext_type.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'image_custom_data.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Color`, `CoreData`, `GeneralCoreData`, `HairCoreData`, `PatternCreationCoreData`, `PatternCreationExtCoreData`, `SpecialEffectCoreData`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Content>>
abstract class Content implements RustOpaqueInterface {
  IdMapI64 get patternData;

  PlatformInt64? get poseId;

  Int64List get wearingClothes;

  AdaptiveArrayNikkiDiy get wearingDiyInfos;

  set patternData(IdMapI64 patternData);

  set poseId(PlatformInt64? poseId);

  set wearingClothes(Int64List wearingClothes);

  set wearingDiyInfos(AdaptiveArrayNikkiDiy wearingDiyInfos);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DIYCustomData>>
abstract class DiyCustomData implements RustOpaqueInterface {
  Content get content;

  set content(Content content);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PhotoInfo>>
abstract class PhotoInfo implements RustOpaqueInterface {
  int get apertureSection;

  double get cameraActorLocX;

  double get cameraActorLocY;

  double get cameraActorLocZ;

  double get cameraActorRotPitch;

  double get cameraActorRotRoll;

  double get cameraActorRotYaw;

  double get cameraComponentLocX;

  double get cameraComponentLocY;

  double get cameraComponentLocZ;

  double get cameraComponentRotPitch;

  double get cameraComponentRotRoll;

  double get cameraComponentRotYaw;

  double get cameraFocalLength;

  String get filterId;

  double get filterStrength;

  String get lightId;

  double get lightStrength;

  Int64List? get magicballColorIds;

  Int64List? get nikkiClothes;

  AdaptiveArrayNikkiDiy get nikkiDiy;

  bool get nikkiHidden;

  double get nikkiLocX;

  double get nikkiLocY;

  double get nikkiLocZ;

  double get nikkiRotPitch;

  double get nikkiRotRoll;

  double get nikkiRotYaw;

  double get nikkiScaleX;

  double get nikkiScaleY;

  double get nikkiScaleZ;

  String? get nikkiWeaponTagName;

  PlatformInt64 get poseId;

  double get vignetteIntensity;

  set apertureSection(int apertureSection);

  set cameraActorLocX(double cameraActorLocX);

  set cameraActorLocY(double cameraActorLocY);

  set cameraActorLocZ(double cameraActorLocZ);

  set cameraActorRotPitch(double cameraActorRotPitch);

  set cameraActorRotRoll(double cameraActorRotRoll);

  set cameraActorRotYaw(double cameraActorRotYaw);

  set cameraComponentLocX(double cameraComponentLocX);

  set cameraComponentLocY(double cameraComponentLocY);

  set cameraComponentLocZ(double cameraComponentLocZ);

  set cameraComponentRotPitch(double cameraComponentRotPitch);

  set cameraComponentRotRoll(double cameraComponentRotRoll);

  set cameraComponentRotYaw(double cameraComponentRotYaw);

  set cameraFocalLength(double cameraFocalLength);

  set filterId(String filterId);

  set filterStrength(double filterStrength);

  set lightId(String lightId);

  set lightStrength(double lightStrength);

  set magicballColorIds(Int64List? magicballColorIds);

  set nikkiClothes(Int64List? nikkiClothes);

  set nikkiDiy(AdaptiveArrayNikkiDiy nikkiDiy);

  set nikkiHidden(bool nikkiHidden);

  set nikkiLocX(double nikkiLocX);

  set nikkiLocY(double nikkiLocY);

  set nikkiLocZ(double nikkiLocZ);

  set nikkiRotPitch(double nikkiRotPitch);

  set nikkiRotRoll(double nikkiRotRoll);

  set nikkiRotYaw(double nikkiRotYaw);

  set nikkiScaleX(double nikkiScaleX);

  set nikkiScaleY(double nikkiScaleY);

  set nikkiScaleZ(double nikkiScaleZ);

  set nikkiWeaponTagName(String? nikkiWeaponTagName);

  set poseId(PlatformInt64 poseId);

  set vignetteIntensity(double vignetteIntensity);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PhotoWallPlugin>>
abstract class PhotoWallPlugin implements RustOpaqueInterface {
  AdaptiveArrayI64 get photoId;

  set photoId(AdaptiveArrayI64 photoId);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SocialPhoto>>
abstract class SocialPhoto implements RustOpaqueInterface {
  String get cameraParams;

  CarrierInfo? get carrierInfo;

  DaMiaoInfoOption get daMiaoInfo;

  bool? get giantState;

  AdaptiveArrayInteractions get interactions;

  String get localTransforms;

  MountInfoOption? get mountInfo;

  PhotoInfo get photoInfo;

  StaticInfosOption get staticInfos;

  Time get time;

  WeaponSnapShot? get weaponSnapShot;

  PlatformInt64 get weatherType;

  set cameraParams(String cameraParams);

  set carrierInfo(CarrierInfo? carrierInfo);

  set daMiaoInfo(DaMiaoInfoOption daMiaoInfo);

  set giantState(bool? giantState);

  set interactions(AdaptiveArrayInteractions interactions);

  set localTransforms(String localTransforms);

  set mountInfo(MountInfoOption? mountInfo);

  set photoInfo(PhotoInfo photoInfo);

  set staticInfos(StaticInfosOption staticInfos);

  set time(Time time);

  set weaponSnapShot(WeaponSnapShot? weaponSnapShot);

  set weatherType(PlatformInt64 weatherType);
}

class CarrierInfo {
  final double locX;
  final double locY;
  final double locZ;
  final double scaleX;
  final double scaleY;
  final double scaleZ;
  final double rotYaw;
  final double rotPitch;
  final double rotRoll;
  final PlatformInt64 configObjId;
  final String pose;

  const CarrierInfo({
    required this.locX,
    required this.locY,
    required this.locZ,
    required this.scaleX,
    required this.scaleY,
    required this.scaleZ,
    required this.rotYaw,
    required this.rotPitch,
    required this.rotRoll,
    required this.configObjId,
    required this.pose,
  });

  @override
  int get hashCode =>
      locX.hashCode ^
      locY.hashCode ^
      locZ.hashCode ^
      scaleX.hashCode ^
      scaleY.hashCode ^
      scaleZ.hashCode ^
      rotYaw.hashCode ^
      rotPitch.hashCode ^
      rotRoll.hashCode ^
      configObjId.hashCode ^
      pose.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CarrierInfo &&
          runtimeType == other.runtimeType &&
          locX == other.locX &&
          locY == other.locY &&
          locZ == other.locZ &&
          scaleX == other.scaleX &&
          scaleY == other.scaleY &&
          scaleZ == other.scaleZ &&
          rotYaw == other.rotYaw &&
          rotPitch == other.rotPitch &&
          rotRoll == other.rotRoll &&
          configObjId == other.configObjId &&
          pose == other.pose;
}

class ClockGamePlugin {
  final PlatformInt64 tag;

  const ClockGamePlugin({required this.tag});

  @override
  int get hashCode => tag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClockGamePlugin &&
          runtimeType == other.runtimeType &&
          tag == other.tag;
}

class ClockInPhotoCustomData {
  final ClockGamePlugin clockGamePlugin;
  final PortraitModeHandler? portraitModeHandler;
  final SocialPhoto? socialPhoto;

  const ClockInPhotoCustomData({
    required this.clockGamePlugin,
    this.portraitModeHandler,
    this.socialPhoto,
  });

  @override
  int get hashCode =>
      clockGamePlugin.hashCode ^
      portraitModeHandler.hashCode ^
      socialPhoto.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClockInPhotoCustomData &&
          runtimeType == other.runtimeType &&
          clockGamePlugin == other.clockGamePlugin &&
          portraitModeHandler == other.portraitModeHandler &&
          socialPhoto == other.socialPhoto;
}

class CollageCustomData {
  final PlatformInt64 templateId;
  final List<RegionPicture> regionPictures;

  const CollageCustomData({
    required this.templateId,
    required this.regionPictures,
  });

  @override
  int get hashCode => templateId.hashCode ^ regionPictures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CollageCustomData &&
          runtimeType == other.runtimeType &&
          templateId == other.templateId &&
          regionPictures == other.regionPictures;
}

class DaMiaoInfo {
  final double locX;
  final double locY;
  final double locZ;
  final double scaleX;
  final double scaleY;
  final double scaleZ;
  final double rotYaw;
  final double rotPitch;
  final double rotRoll;
  final Int64List clothIds;
  final String action;

  const DaMiaoInfo({
    required this.locX,
    required this.locY,
    required this.locZ,
    required this.scaleX,
    required this.scaleY,
    required this.scaleZ,
    required this.rotYaw,
    required this.rotPitch,
    required this.rotRoll,
    required this.clothIds,
    required this.action,
  });

  @override
  int get hashCode =>
      locX.hashCode ^
      locY.hashCode ^
      locZ.hashCode ^
      scaleX.hashCode ^
      scaleY.hashCode ^
      scaleZ.hashCode ^
      rotYaw.hashCode ^
      rotPitch.hashCode ^
      rotRoll.hashCode ^
      clothIds.hashCode ^
      action.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DaMiaoInfo &&
          runtimeType == other.runtimeType &&
          locX == other.locX &&
          locY == other.locY &&
          locZ == other.locZ &&
          scaleX == other.scaleX &&
          scaleY == other.scaleY &&
          scaleZ == other.scaleZ &&
          rotYaw == other.rotYaw &&
          rotPitch == other.rotPitch &&
          rotRoll == other.rotRoll &&
          clothIds == other.clothIds &&
          action == other.action;
}

@freezed
sealed class DaMiaoInfoOption with _$DaMiaoInfoOption {
  const DaMiaoInfoOption._();

  const factory DaMiaoInfoOption.none() = DaMiaoInfoOption_None;
  const factory DaMiaoInfoOption.some(DaMiaoInfo field0) =
      DaMiaoInfoOption_Some;
}

class EditPhotoHandler {
  final bool editState;
  final bool hasSticker;
  final bool hasText;

  const EditPhotoHandler({
    required this.editState,
    required this.hasSticker,
    required this.hasText,
  });

  @override
  int get hashCode =>
      editState.hashCode ^ hasSticker.hashCode ^ hasText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditPhotoHandler &&
          runtimeType == other.runtimeType &&
          editState == other.editState &&
          hasSticker == other.hasSticker &&
          hasText == other.hasText;
}

class MagazinePhotoCustomData {
  const MagazinePhotoCustomData();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MagazinePhotoCustomData && runtimeType == other.runtimeType;
}

class MountInfo {
  final double locX;
  final double locY;
  final double locZ;
  final double scaleX;
  final double scaleY;
  final double scaleZ;
  final double rotYaw;
  final double rotPitch;
  final double rotRoll;
  final PlatformInt64 configId;
  final String pose;

  const MountInfo({
    required this.locX,
    required this.locY,
    required this.locZ,
    required this.scaleX,
    required this.scaleY,
    required this.scaleZ,
    required this.rotYaw,
    required this.rotPitch,
    required this.rotRoll,
    required this.configId,
    required this.pose,
  });

  @override
  int get hashCode =>
      locX.hashCode ^
      locY.hashCode ^
      locZ.hashCode ^
      scaleX.hashCode ^
      scaleY.hashCode ^
      scaleZ.hashCode ^
      rotYaw.hashCode ^
      rotPitch.hashCode ^
      rotRoll.hashCode ^
      configId.hashCode ^
      pose.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MountInfo &&
          runtimeType == other.runtimeType &&
          locX == other.locX &&
          locY == other.locY &&
          locZ == other.locZ &&
          scaleX == other.scaleX &&
          scaleY == other.scaleY &&
          scaleZ == other.scaleZ &&
          rotYaw == other.rotYaw &&
          rotPitch == other.rotPitch &&
          rotRoll == other.rotRoll &&
          configId == other.configId &&
          pose == other.pose;
}

@freezed
sealed class MountInfoOption with _$MountInfoOption {
  const MountInfoOption._();

  const factory MountInfoOption.none() = MountInfoOption_None;
  const factory MountInfoOption.some(MountInfo field0) = MountInfoOption_Some;
}

class NikkiPhotoCustomData {
  final EditPhotoHandler? editPhotoHandler;
  final IdMapBool? interactivePhoto;
  final PhotoWallPlugin? photoWallPlugin;
  final PortraitModeHandler? portraitModeHandler;
  final PuzzleGamePlugin? puzzleGamePlugin;
  final IdMapBool? riskPhoto;
  final SocialPhoto? socialPhoto;

  const NikkiPhotoCustomData({
    this.editPhotoHandler,
    this.interactivePhoto,
    this.photoWallPlugin,
    this.portraitModeHandler,
    this.puzzleGamePlugin,
    this.riskPhoto,
    this.socialPhoto,
  });

  @override
  int get hashCode =>
      editPhotoHandler.hashCode ^
      interactivePhoto.hashCode ^
      photoWallPlugin.hashCode ^
      portraitModeHandler.hashCode ^
      puzzleGamePlugin.hashCode ^
      riskPhoto.hashCode ^
      socialPhoto.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NikkiPhotoCustomData &&
          runtimeType == other.runtimeType &&
          editPhotoHandler == other.editPhotoHandler &&
          interactivePhoto == other.interactivePhoto &&
          photoWallPlugin == other.photoWallPlugin &&
          portraitModeHandler == other.portraitModeHandler &&
          puzzleGamePlugin == other.puzzleGamePlugin &&
          riskPhoto == other.riskPhoto &&
          socialPhoto == other.socialPhoto;
}

class PortraitModeHandler {
  final PlatformInt64 portraitMode;

  const PortraitModeHandler({required this.portraitMode});

  @override
  int get hashCode => portraitMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PortraitModeHandler &&
          runtimeType == other.runtimeType &&
          portraitMode == other.portraitMode;
}

class Position {
  final double x;
  final double y;

  const Position({required this.x, required this.y});

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Position &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}

class PuzzleGamePlugin {
  final PlatformInt64 tag;

  const PuzzleGamePlugin({required this.tag});

  @override
  int get hashCode => tag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PuzzleGamePlugin &&
          runtimeType == other.runtimeType &&
          tag == other.tag;
}

class RegionPicture {
  final String imageId;
  final NikkiPhotoCustomData oriCustomData;
  final Position position;
  final double rotation;
  final double scale;

  const RegionPicture({
    required this.imageId,
    required this.oriCustomData,
    required this.position,
    required this.rotation,
    required this.scale,
  });

  @override
  int get hashCode =>
      imageId.hashCode ^
      oriCustomData.hashCode ^
      position.hashCode ^
      rotation.hashCode ^
      scale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegionPicture &&
          runtimeType == other.runtimeType &&
          imageId == other.imageId &&
          oriCustomData == other.oriCustomData &&
          position == other.position &&
          rotation == other.rotation &&
          scale == other.scale;
}

class StaticInfos {
  const StaticInfos();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StaticInfos && runtimeType == other.runtimeType;
}

@freezed
sealed class StaticInfosOption with _$StaticInfosOption {
  const StaticInfosOption._();

  const factory StaticInfosOption.none() = StaticInfosOption_None;
  const factory StaticInfosOption.some(StaticInfos field0) =
      StaticInfosOption_Some;
}

class Time {
  final PlatformInt64 day;
  final int hour;
  final int min;
  final double sec;

  const Time({
    required this.day,
    required this.hour,
    required this.min,
    required this.sec,
  });

  @override
  int get hashCode =>
      day.hashCode ^ hour.hashCode ^ min.hashCode ^ sec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Time &&
          runtimeType == other.runtimeType &&
          day == other.day &&
          hour == other.hour &&
          min == other.min &&
          sec == other.sec;
}

class WeaponSnapShot {
  final PlatformInt64 weaponId;
  final String customState;
  final String slotType;

  const WeaponSnapShot({
    required this.weaponId,
    required this.customState,
    required this.slotType,
  });

  @override
  int get hashCode =>
      weaponId.hashCode ^ customState.hashCode ^ slotType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeaponSnapShot &&
          runtimeType == other.runtimeType &&
          weaponId == other.weaponId &&
          customState == other.customState &&
          slotType == other.slotType;
}
