// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'image_custom_data.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ShareCode>>
abstract class ShareCode implements RustOpaqueInterface {
  DiyCustomData get content;

  set content(DiyCustomData content);
}

class DiyHistoryShareCode {
  final String roleId;
  final double timeStamp;
  final String shareCode;

  const DiyHistoryShareCode({
    required this.roleId,
    required this.timeStamp,
    required this.shareCode,
  });

  @override
  int get hashCode => roleId.hashCode ^ timeStamp.hashCode ^ shareCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiyHistoryShareCode &&
          runtimeType == other.runtimeType &&
          roleId == other.roleId &&
          timeStamp == other.timeStamp &&
          shareCode == other.shareCode;
}
