// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`

class VideoCoverCustomData {
  final VideoCoverData videoCoverData;

  const VideoCoverCustomData({required this.videoCoverData});

  @override
  int get hashCode => videoCoverData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoCoverCustomData &&
          runtimeType == other.runtimeType &&
          videoCoverData == other.videoCoverData;
}

class VideoCoverData {
  final BigInt roleId;
  final BigInt createTime;
  final VideoRecordData videoCustomData;

  const VideoCoverData({
    required this.roleId,
    required this.createTime,
    required this.videoCustomData,
  });

  @override
  int get hashCode =>
      roleId.hashCode ^ createTime.hashCode ^ videoCustomData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoCoverData &&
          runtimeType == other.runtimeType &&
          roleId == other.roleId &&
          createTime == other.createTime &&
          videoCustomData == other.videoCustomData;
}

class VideoCustomData {
  final VideoRecordData videoRecordData;

  const VideoCustomData({required this.videoRecordData});

  @override
  int get hashCode => videoRecordData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoCustomData &&
          runtimeType == other.runtimeType &&
          videoRecordData == other.videoRecordData;
}

class VideoRecordData {
  final double createTime;
  final BigInt crf;
  final BigInt desiredHeight;
  final BigInt desiredWidth;
  final String durationStr;
  final BigInt framesCount;
  final String frameEndWith;
  final BigInt frameRate;
  final String inputFilePath;
  final String outputFilePath;
  final String presetQuality;
  final BigInt roleId;
  final BigInt sourceHeight;
  final BigInt sourceWidth;
  final String videoSaveName;
  final BigInt viewportHeight;
  final String videoSavePath;
  final BigInt viewportWidth;

  const VideoRecordData({
    required this.createTime,
    required this.crf,
    required this.desiredHeight,
    required this.desiredWidth,
    required this.durationStr,
    required this.framesCount,
    required this.frameEndWith,
    required this.frameRate,
    required this.inputFilePath,
    required this.outputFilePath,
    required this.presetQuality,
    required this.roleId,
    required this.sourceHeight,
    required this.sourceWidth,
    required this.videoSaveName,
    required this.viewportHeight,
    required this.videoSavePath,
    required this.viewportWidth,
  });

  @override
  int get hashCode =>
      createTime.hashCode ^
      crf.hashCode ^
      desiredHeight.hashCode ^
      desiredWidth.hashCode ^
      durationStr.hashCode ^
      framesCount.hashCode ^
      frameEndWith.hashCode ^
      frameRate.hashCode ^
      inputFilePath.hashCode ^
      outputFilePath.hashCode ^
      presetQuality.hashCode ^
      roleId.hashCode ^
      sourceHeight.hashCode ^
      sourceWidth.hashCode ^
      videoSaveName.hashCode ^
      viewportHeight.hashCode ^
      videoSavePath.hashCode ^
      viewportWidth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoRecordData &&
          runtimeType == other.runtimeType &&
          createTime == other.createTime &&
          crf == other.crf &&
          desiredHeight == other.desiredHeight &&
          desiredWidth == other.desiredWidth &&
          durationStr == other.durationStr &&
          framesCount == other.framesCount &&
          frameEndWith == other.frameEndWith &&
          frameRate == other.frameRate &&
          inputFilePath == other.inputFilePath &&
          outputFilePath == other.outputFilePath &&
          presetQuality == other.presetQuality &&
          roleId == other.roleId &&
          sourceHeight == other.sourceHeight &&
          sourceWidth == other.sourceWidth &&
          videoSaveName == other.videoSaveName &&
          viewportHeight == other.viewportHeight &&
          videoSavePath == other.videoSavePath &&
          viewportWidth == other.viewportWidth;
}
