// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'string_config.freezed.dart';

class StringConfig {
  final List<StringProcessConfig> process;

  const StringConfig({required this.process});

  @override
  int get hashCode => process.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StringConfig &&
          runtimeType == other.runtimeType &&
          process == other.process;
}

class StringJoinProcessConfig {
  final String symbol;
  final List<List<StringProcessConfig>> target;

  const StringJoinProcessConfig({required this.symbol, required this.target});

  @override
  int get hashCode => symbol.hashCode ^ target.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StringJoinProcessConfig &&
          runtimeType == other.runtimeType &&
          symbol == other.symbol &&
          target == other.target;
}

class StringMatchProcessConfig {
  final String regex;
  final int which;
  final String successful;
  final List<StringProcessConfig> failed;

  const StringMatchProcessConfig({
    required this.regex,
    required this.which,
    required this.successful,
    required this.failed,
  });

  @override
  int get hashCode =>
      regex.hashCode ^ which.hashCode ^ successful.hashCode ^ failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StringMatchProcessConfig &&
          runtimeType == other.runtimeType &&
          regex == other.regex &&
          which == other.which &&
          successful == other.successful &&
          failed == other.failed;
}

@freezed
sealed class StringProcessConfig with _$StringProcessConfig {
  const StringProcessConfig._();

  const factory StringProcessConfig.join(StringJoinProcessConfig field0) =
      StringProcessConfig_Join;
  const factory StringProcessConfig.match(StringMatchProcessConfig field0) =
      StringProcessConfig_Match;
  const factory StringProcessConfig.replace(StringReplaceProcessConfig field0) =
      StringProcessConfig_Replace;
  const factory StringProcessConfig.replaceAll(
    StringReplaceAllProcessConfig field0,
  ) = StringProcessConfig_ReplaceAll;
}

class StringReplaceAllProcessConfig {
  final String regex;
  final String to;

  const StringReplaceAllProcessConfig({required this.regex, required this.to});

  @override
  int get hashCode => regex.hashCode ^ to.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StringReplaceAllProcessConfig &&
          runtimeType == other.runtimeType &&
          regex == other.regex &&
          to == other.to;
}

class StringReplaceProcessConfig {
  final String regex;
  final int which;
  final String to;

  const StringReplaceProcessConfig({
    required this.regex,
    required this.which,
    required this.to,
  });

  @override
  int get hashCode => regex.hashCode ^ which.hashCode ^ to.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StringReplaceProcessConfig &&
          runtimeType == other.runtimeType &&
          regex == other.regex &&
          which == other.which &&
          to == other.to;
}
