// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'text_config.freezed.dart';

class LiteralTextConfig {
  final String text;

  const LiteralTextConfig({required this.text});

  @override
  int get hashCode => text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiteralTextConfig &&
          runtimeType == other.runtimeType &&
          text == other.text;
}

@freezed
sealed class TextConfig with _$TextConfig {
  const TextConfig._();

  const factory TextConfig.literal(LiteralTextConfig field0) =
      TextConfig_Literal;
  const factory TextConfig.translate(TranslateTextConfig field0) =
      TextConfig_Translate;

  static TextConfig? fromJson({required String json}) => RustLib.instance.api
      .crateConfigCommonTextConfigTextConfigFromJson(json: json);

  String toJson() => RustLib.instance.api
      .crateConfigCommonTextConfigTextConfigToJson(that: this);

  String toJsonPretty() => RustLib.instance.api
      .crateConfigCommonTextConfigTextConfigToJsonPretty(that: this);
}

class TranslateTextConfig {
  final String key;
  final List<String>? args;
  final Map<String, String>? namedArgs;
  final String? gender;

  const TranslateTextConfig({
    required this.key,
    this.args,
    this.namedArgs,
    this.gender,
  });

  @override
  int get hashCode =>
      key.hashCode ^ args.hashCode ^ namedArgs.hashCode ^ gender.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranslateTextConfig &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          args == other.args &&
          namedArgs == other.namedArgs &&
          gender == other.gender;
}
