// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'cloth.dart';
import 'eureka.dart';
import 'nikki_photo_params.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'world.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ClockInPhotoMainParams`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

class ClockInPhotoParams {
  final PlatformInt64 tag;
  final PhotographyParams photography;
  final RichCameraParams? camera;
  final NikkiParams? nikki;
  final MomoHiddenState? momo;

  const ClockInPhotoParams({
    required this.tag,
    required this.photography,
    this.camera,
    this.nikki,
    this.momo,
  });

  @override
  int get hashCode =>
      tag.hashCode ^
      photography.hashCode ^
      camera.hashCode ^
      nikki.hashCode ^
      momo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClockInPhotoParams &&
          runtimeType == other.runtimeType &&
          tag == other.tag &&
          photography == other.photography &&
          camera == other.camera &&
          nikki == other.nikki &&
          momo == other.momo;
}
