// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

class Cloth {
  final PlatformInt64 id;
  final PlatformInt64? outfit;
  final int species;
  final int clothType;
  final int state;

  const Cloth({
    required this.id,
    this.outfit,
    required this.species,
    required this.clothType,
    required this.state,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      outfit.hashCode ^
      species.hashCode ^
      clothType.hashCode ^
      state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Cloth &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          outfit == other.outfit &&
          species == other.species &&
          clothType == other.clothType &&
          state == other.state;
}
