// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'game_config.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`

class AndroidCustomGameConfig {
  final Text? toLauncherTip;
  final String toLauncherThenToInstall;

  const AndroidCustomGameConfig({
    this.toLauncherTip,
    required this.toLauncherThenToInstall,
  });

  @override
  int get hashCode => toLauncherTip.hashCode ^ toLauncherThenToInstall.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AndroidCustomGameConfig &&
          runtimeType == other.runtimeType &&
          toLauncherTip == other.toLauncherTip &&
          toLauncherThenToInstall == other.toLauncherThenToInstall;
}

/// -----------------
/// AndroidGameConfig
/// -----------------
class AndroidGameConfig {
  final List<AndroidGameLocationConfig> locate;
  final AndroidCustomGameConfig? custom;

  const AndroidGameConfig({required this.locate, this.custom});

  @override
  int get hashCode => locate.hashCode ^ custom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AndroidGameConfig &&
          runtimeType == other.runtimeType &&
          locate == other.locate &&
          custom == other.custom;
}

class AndroidGameLocationConfig {
  final String channel;
  final Text name;
  final String icon;
  final AndroidGameSearcherConfig searcher;

  const AndroidGameLocationConfig({
    required this.channel,
    required this.name,
    required this.icon,
    required this.searcher,
  });

  @override
  int get hashCode =>
      channel.hashCode ^ name.hashCode ^ icon.hashCode ^ searcher.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AndroidGameLocationConfig &&
          runtimeType == other.runtimeType &&
          channel == other.channel &&
          name == other.name &&
          icon == other.icon &&
          searcher == other.searcher;
}

class AndroidGameSearcherConfig {
  final String applicationId;
  final String toInstall;

  const AndroidGameSearcherConfig({
    required this.applicationId,
    required this.toInstall,
  });

  @override
  int get hashCode => applicationId.hashCode ^ toInstall.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AndroidGameSearcherConfig &&
          runtimeType == other.runtimeType &&
          applicationId == other.applicationId &&
          toInstall == other.toInstall;
}

class GameAlbumConfig {
  final String id;
  final bool visible;
  final bool unimportance;
  final Text name;
  final Text? description;
  final String? icon;
  final bool requireUid;
  final String locate;
  final String toMedia;
  final String? toCover;
  final String? toThumbnail;
  final bool allowMove;
  final bool allowDelete;
  final bool cacheByName;
  final Map<String, bool> chainDeletion;
  final List<Platform> platforms;

  const GameAlbumConfig({
    required this.id,
    required this.visible,
    required this.unimportance,
    required this.name,
    this.description,
    this.icon,
    required this.requireUid,
    required this.locate,
    required this.toMedia,
    this.toCover,
    this.toThumbnail,
    required this.allowMove,
    required this.allowDelete,
    required this.cacheByName,
    required this.chainDeletion,
    required this.platforms,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      visible.hashCode ^
      unimportance.hashCode ^
      name.hashCode ^
      description.hashCode ^
      icon.hashCode ^
      requireUid.hashCode ^
      locate.hashCode ^
      toMedia.hashCode ^
      toCover.hashCode ^
      toThumbnail.hashCode ^
      allowMove.hashCode ^
      allowDelete.hashCode ^
      cacheByName.hashCode ^
      chainDeletion.hashCode ^
      platforms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameAlbumConfig &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          visible == other.visible &&
          unimportance == other.unimportance &&
          name == other.name &&
          description == other.description &&
          icon == other.icon &&
          requireUid == other.requireUid &&
          locate == other.locate &&
          toMedia == other.toMedia &&
          toCover == other.toCover &&
          toThumbnail == other.toThumbnail &&
          allowMove == other.allowMove &&
          allowDelete == other.allowDelete &&
          cacheByName == other.cacheByName &&
          chainDeletion == other.chainDeletion &&
          platforms == other.platforms;
}

class GameConfig {
  final String id;
  final Text name;
  final String? icon;
  final List<GameAlbumConfig> albumsConfig;
  final WindowsGameConfig? windows;
  final MacOSGameConfig? macos;
  final AndroidGameConfig? android;

  const GameConfig({
    required this.id,
    required this.name,
    this.icon,
    required this.albumsConfig,
    this.windows,
    this.macos,
    this.android,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      icon.hashCode ^
      albumsConfig.hashCode ^
      windows.hashCode ^
      macos.hashCode ^
      android.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameConfig &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          icon == other.icon &&
          albumsConfig == other.albumsConfig &&
          windows == other.windows &&
          macos == other.macos &&
          android == other.android;
}

class MacOSCustomGameConfig {
  final Text? toLauncherTip;
  final String toLauncherThenToInstall;

  const MacOSCustomGameConfig({
    this.toLauncherTip,
    required this.toLauncherThenToInstall,
  });

  @override
  int get hashCode => toLauncherTip.hashCode ^ toLauncherThenToInstall.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MacOSCustomGameConfig &&
          runtimeType == other.runtimeType &&
          toLauncherTip == other.toLauncherTip &&
          toLauncherThenToInstall == other.toLauncherThenToInstall;
}

/// -----------------
/// MacOSGameConfig
/// -----------------
class MacOSGameConfig {
  final List<MacOSGameLocationConfig> locate;
  final MacOSCustomGameConfig? custom;

  const MacOSGameConfig({required this.locate, this.custom});

  @override
  int get hashCode => locate.hashCode ^ custom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MacOSGameConfig &&
          runtimeType == other.runtimeType &&
          locate == other.locate &&
          custom == other.custom;
}

class MacOSGameLocationConfig {
  final String channel;
  final Text name;
  final String icon;
  final MacOSGameSearcherConfig searcher;

  const MacOSGameLocationConfig({
    required this.channel,
    required this.name,
    required this.icon,
    required this.searcher,
  });

  @override
  int get hashCode =>
      channel.hashCode ^ name.hashCode ^ icon.hashCode ^ searcher.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MacOSGameLocationConfig &&
          runtimeType == other.runtimeType &&
          channel == other.channel &&
          name == other.name &&
          icon == other.icon &&
          searcher == other.searcher;
}

class MacOSGameSearcherConfig {
  final String bundleId;
  final String toInstall;

  const MacOSGameSearcherConfig({
    required this.bundleId,
    required this.toInstall,
  });

  @override
  int get hashCode => bundleId.hashCode ^ toInstall.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MacOSGameSearcherConfig &&
          runtimeType == other.runtimeType &&
          bundleId == other.bundleId &&
          toInstall == other.toInstall;
}

class WindowsCustomGameConfig {
  final Text? toLauncherTip;
  final List<FileEntityLocationConfig>? toLauncher;
  final List<String>? toLauncherThenToInstall;
  final Text? toInstallTip;
  final List<FileEntityLocationConfig> toInstall;
  final List<String>? toInstallThenToLauncher;

  const WindowsCustomGameConfig({
    this.toLauncherTip,
    this.toLauncher,
    this.toLauncherThenToInstall,
    this.toInstallTip,
    required this.toInstall,
    this.toInstallThenToLauncher,
  });

  @override
  int get hashCode =>
      toLauncherTip.hashCode ^
      toLauncher.hashCode ^
      toLauncherThenToInstall.hashCode ^
      toInstallTip.hashCode ^
      toInstall.hashCode ^
      toInstallThenToLauncher.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WindowsCustomGameConfig &&
          runtimeType == other.runtimeType &&
          toLauncherTip == other.toLauncherTip &&
          toLauncher == other.toLauncher &&
          toLauncherThenToInstall == other.toLauncherThenToInstall &&
          toInstallTip == other.toInstallTip &&
          toInstall == other.toInstall &&
          toInstallThenToLauncher == other.toInstallThenToLauncher;
}

/// -----------------
/// WindowsGameConfig
/// -----------------
class WindowsGameConfig {
  final List<WindowsGameLocationConfig> locate;
  final WindowsCustomGameConfig? custom;

  const WindowsGameConfig({required this.locate, this.custom});

  @override
  int get hashCode => locate.hashCode ^ custom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WindowsGameConfig &&
          runtimeType == other.runtimeType &&
          locate == other.locate &&
          custom == other.custom;
}

class WindowsGameLocationConfig {
  final String channel;
  final Text name;
  final String icon;
  final bool requireLauncher;
  final List<WindowsGameSearcherConfig> searcher;

  const WindowsGameLocationConfig({
    required this.channel,
    required this.name,
    required this.icon,
    required this.requireLauncher,
    required this.searcher,
  });

  @override
  int get hashCode =>
      channel.hashCode ^
      name.hashCode ^
      icon.hashCode ^
      requireLauncher.hashCode ^
      searcher.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WindowsGameLocationConfig &&
          runtimeType == other.runtimeType &&
          channel == other.channel &&
          name == other.name &&
          icon == other.icon &&
          requireLauncher == other.requireLauncher &&
          searcher == other.searcher;
}

@freezed
sealed class WindowsGameSearcherConfig with _$WindowsGameSearcherConfig {
  const WindowsGameSearcherConfig._();

  const factory WindowsGameSearcherConfig.registry({
    WindowsRegistryConfig? toLauncher,
    required WindowsRegistryConfig toInstall,
    required bool useConfigFile,
  }) = WindowsGameSearcherConfig_Registry;
  const factory WindowsGameSearcherConfig.configFile({
    required String path,
    required ConfigFileType configType,
    String? toLauncher,
    String? toLauncherRegex,
    required String toInstall,
    String? toInstallRegex,
  }) = WindowsGameSearcherConfig_ConfigFile;
}

class WindowsRegistryConfig {
  final WindowsRegistryHive hive;
  final String path;
  final String key;
  final String? regex;
  final String locate;

  const WindowsRegistryConfig({
    required this.hive,
    required this.path,
    required this.key,
    this.regex,
    required this.locate,
  });

  @override
  int get hashCode =>
      hive.hashCode ^
      path.hashCode ^
      key.hashCode ^
      regex.hashCode ^
      locate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WindowsRegistryConfig &&
          runtimeType == other.runtimeType &&
          hive == other.hive &&
          path == other.path &&
          key == other.key &&
          regex == other.regex &&
          locate == other.locate;
}
