// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PluginSource`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

class PluginInfo {
  final String? asExtensionOf;
  final String uuid;
  final Text name;
  final Text description;
  final String? icon;
  final int version;
  final String? author;
  final String? web;
  final String? downloadUrl;
  final String? pluginList;
  final int appVersion;
  final List<Platform> platforms;

  const PluginInfo({
    this.asExtensionOf,
    required this.uuid,
    required this.name,
    required this.description,
    this.icon,
    required this.version,
    this.author,
    this.web,
    this.downloadUrl,
    this.pluginList,
    required this.appVersion,
    required this.platforms,
  });

  @override
  int get hashCode =>
      asExtensionOf.hashCode ^
      uuid.hashCode ^
      name.hashCode ^
      description.hashCode ^
      icon.hashCode ^
      version.hashCode ^
      author.hashCode ^
      web.hashCode ^
      downloadUrl.hashCode ^
      pluginList.hashCode ^
      appVersion.hashCode ^
      platforms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginInfo &&
          runtimeType == other.runtimeType &&
          asExtensionOf == other.asExtensionOf &&
          uuid == other.uuid &&
          name == other.name &&
          description == other.description &&
          icon == other.icon &&
          version == other.version &&
          author == other.author &&
          web == other.web &&
          downloadUrl == other.downloadUrl &&
          pluginList == other.pluginList &&
          appVersion == other.appVersion &&
          platforms == other.platforms;
}
