// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'text.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`

class OrdinaryText {
  final String text;

  const OrdinaryText({required this.text});

  @override
  int get hashCode => text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrdinaryText &&
          runtimeType == other.runtimeType &&
          text == other.text;
}

@freezed
sealed class Text with _$Text {
  const Text._();

  const factory Text.ordinary(OrdinaryText field0) = Text_Ordinary;
  const factory Text.translate(TranslateText field0) = Text_Translate;
}

class TranslateText {
  final String key;
  final List<String>? args;
  final List<String>? namedArgs;
  final String? gender;

  const TranslateText({
    required this.key,
    this.args,
    this.namedArgs,
    this.gender,
  });

  @override
  int get hashCode =>
      key.hashCode ^ args.hashCode ^ namedArgs.hashCode ^ gender.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranslateText &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          args == other.args &&
          namedArgs == other.namedArgs &&
          gender == other.gender;
}
