// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'theme.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`

class ColorRoleScheme {
  final int color;
  final int onColor;
  final int enabledColor;
  final int onEnabledColor;
  final int disabledColor;
  final int onDisabledColor;
  final int hoveredColor;
  final int onHoveredColor;
  final int pressedColor;
  final int onPressedColor;

  const ColorRoleScheme({
    required this.color,
    required this.onColor,
    required this.enabledColor,
    required this.onEnabledColor,
    required this.disabledColor,
    required this.onDisabledColor,
    required this.hoveredColor,
    required this.onHoveredColor,
    required this.pressedColor,
    required this.onPressedColor,
  });

  @override
  int get hashCode =>
      color.hashCode ^
      onColor.hashCode ^
      enabledColor.hashCode ^
      onEnabledColor.hashCode ^
      disabledColor.hashCode ^
      onDisabledColor.hashCode ^
      hoveredColor.hashCode ^
      onHoveredColor.hashCode ^
      pressedColor.hashCode ^
      onPressedColor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColorRoleScheme &&
          runtimeType == other.runtimeType &&
          color == other.color &&
          onColor == other.onColor &&
          enabledColor == other.enabledColor &&
          onEnabledColor == other.onEnabledColor &&
          disabledColor == other.disabledColor &&
          onDisabledColor == other.onDisabledColor &&
          hoveredColor == other.hoveredColor &&
          onHoveredColor == other.onHoveredColor &&
          pressedColor == other.pressedColor &&
          onPressedColor == other.onPressedColor;
}

class ColorScheme {
  final ColorRoleScheme primary;
  final ColorRoleScheme secondary;
  final ColorRoleScheme tertiary;
  final ColorRoleScheme success;
  final ColorRoleScheme error;
  final ColorRoleScheme background;
  final ColorRoleScheme highlight;

  const ColorScheme({
    required this.primary,
    required this.secondary,
    required this.tertiary,
    required this.success,
    required this.error,
    required this.background,
    required this.highlight,
  });

  @override
  int get hashCode =>
      primary.hashCode ^
      secondary.hashCode ^
      tertiary.hashCode ^
      success.hashCode ^
      error.hashCode ^
      background.hashCode ^
      highlight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColorScheme &&
          runtimeType == other.runtimeType &&
          primary == other.primary &&
          secondary == other.secondary &&
          tertiary == other.tertiary &&
          success == other.success &&
          error == other.error &&
          background == other.background &&
          highlight == other.highlight;
}

class ThemeConfigV1 {
  final bool v1;
  final Text name;
  final (int, int, int) color;
  final ColorScheme scheme;

  const ThemeConfigV1({
    required this.v1,
    required this.name,
    required this.color,
    required this.scheme,
  });

  @override
  int get hashCode =>
      v1.hashCode ^ name.hashCode ^ color.hashCode ^ scheme.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThemeConfigV1 &&
          runtimeType == other.runtimeType &&
          v1 == other.v1 &&
          name == other.name &&
          color == other.color &&
          scheme == other.scheme;
}

@freezed
sealed class ThemeConfigWrapper with _$ThemeConfigWrapper {
  const ThemeConfigWrapper._();

  const factory ThemeConfigWrapper.v1(ThemeConfigV1 field0) =
      ThemeConfigWrapper_V1;
}
