// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Thumbnail {
  final int width;
  final int height;
  final Uint8List bytes;

  const Thumbnail({
    required this.width,
    required this.height,
    required this.bytes,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Thumbnail &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          bytes == other.bytes;
}
