// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'decrypt.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'structs/clock_in_photo_params.dart';
import 'structs/collage_params.dart';
import 'structs/diy_params.dart';
import 'structs/momo_camera_params.dart';
import 'structs/nikki_photo_params.dart';
import 'structs/world.dart';
part 'decode.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

Future<MediaCustomData> decodeMediaParam({
  required MediaParamType paramType,
  required CustomData data,
}) => RustLib.instance.api.crateNuan5MediaParamDecodeDecodeMediaParam(
  paramType: paramType,
  data: data,
);

@freezed
sealed class MediaCustomData with _$MediaCustomData {
  const MediaCustomData._();

  const factory MediaCustomData.invalid() = MediaCustomData_Invalid;
  const factory MediaCustomData.valid(MediaParam field0) =
      MediaCustomData_Valid;
}

@freezed
sealed class MediaParam with _$MediaParam {
  const MediaParam._();

  const factory MediaParam.momoCameraParams(MomoCameraParams field0) =
      MediaParam_MomoCameraParams;
  const factory MediaParam.nikkiPhoto(NikkiPhotoParams field0) =
      MediaParam_NikkiPhoto;
  const factory MediaParam.clockInPhoto(ClockInPhotoParams field0) =
      MediaParam_ClockInPhoto;
  const factory MediaParam.collage(CollageParams field0) = MediaParam_Collage;
  const factory MediaParam.diy(DiyParams field0) = MediaParam_DIY;
}

enum MediaParamType { momoCameraParams, nikkiPhoto, clockInPhoto, collage, diy }
