// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'decrypt.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `convert_media_result`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

CustomData? mediaDecrypt(List<int> data, MediaKey key) => RustLib.instance.api
    .crateNuan5MediaParamDecryptMediaDecrypt(data: data, key: key);

CustomData? mediaDecodeFileBytesUnchecked({
  required List<int> flag,
  required List<int> bytes,
  required MediaKey key,
}) => RustLib.instance.api
    .crateNuan5MediaParamDecryptMediaDecodeFileBytesUnchecked(
      flag: flag,
      bytes: bytes,
      key: key,
    );

Future<CustomData?> mediaDecodeFileUnchecked({
  required List<int> flag,
  required String path,
  required MediaKey key,
}) => RustLib.instance.api.crateNuan5MediaParamDecryptMediaDecodeFileUnchecked(
  flag: flag,
  path: path,
  key: key,
);

CustomData? mediaDecodeFileUncheckedSync({
  required List<int> flag,
  required String path,
  required MediaKey key,
}) => RustLib.instance.api
    .crateNuan5MediaParamDecryptMediaDecodeFileUncheckedSync(
      flag: flag,
      path: path,
      key: key,
    );

Stream<MediaDecodeEvent> mediaDecodeFilesUnchecked({
  required List<int> flag,
  required List<String> paths,
  required MediaKey key,
}) => RustLib.instance.api.crateNuan5MediaParamDecryptMediaDecodeFilesUnchecked(
  flag: flag,
  paths: paths,
  key: key,
);

/// 批量解密（无进度）
Future<List<CustomData?>> mediaDecodeFilesUncheckedNoProgress({
  required List<int> flag,
  required List<String> paths,
  required MediaKey key,
}) => RustLib.instance.api
    .crateNuan5MediaParamDecryptMediaDecodeFilesUncheckedNoProgress(
      flag: flag,
      paths: paths,
      key: key,
    );

/// 批量解密文件（流式回调，并行执行）。
Stream<MediaStreamResult> mediaDecodeFilesUncheckedStream({
  required List<int> flag,
  required List<String> paths,
  required MediaKey key,
}) => RustLib.instance.api
    .crateNuan5MediaParamDecryptMediaDecodeFilesUncheckedStream(
      flag: flag,
      paths: paths,
      key: key,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MediaKey>>
abstract class MediaKey implements RustOpaqueInterface {
  static MediaKey cameraParam() =>
      RustLib.instance.api.crateNuan5MediaParamDecryptMediaKeyCameraParam();

  @override
  Future<void> dispose();

  static MediaKey fromStr(String s) =>
      RustLib.instance.api.crateNuan5MediaParamDecryptMediaKeyFromStr(s: s);

  static MediaKey fromStrBytes(List<int> bytes) => RustLib.instance.api
      .crateNuan5MediaParamDecryptMediaKeyFromStrBytes(bytes: bytes);
}

@freezed
sealed class CustomData with _$CustomData {
  const CustomData._();

  const factory CustomData.invalid() = CustomData_Invalid;
  const factory CustomData.valid(Uint8List field0) = CustomData_Valid;
}

@freezed
sealed class MediaDecodeEvent with _$MediaDecodeEvent {
  const MediaDecodeEvent._();

  const factory MediaDecodeEvent.progress(double field0) =
      MediaDecodeEvent_Progress;
  const factory MediaDecodeEvent.result(List<CustomData?> field0) =
      MediaDecodeEvent_Result;
}

/// 流式批量解密的单文件结果
class MediaStreamResult {
  final BigInt index;
  final CustomData? data;

  const MediaStreamResult({required this.index, this.data});

  @override
  int get hashCode => index.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaStreamResult &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          data == other.data;
}
