// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'decrypt.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `convert_result`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

CustomData? decrypt(List<int> data, Key key) =>
    RustLib.instance.api.crateApiMediaParamDecryptDecrypt(data: data, key: key);

CustomData? decodeFileBytesUnchecked({
  required List<int> flag,
  required List<int> bytes,
  required Key key,
}) => RustLib.instance.api.crateApiMediaParamDecryptDecodeFileBytesUnchecked(
  flag: flag,
  bytes: bytes,
  key: key,
);

Future<CustomData?> decodeFileUnchecked({
  required List<int> flag,
  required String path,
  required Key key,
}) => RustLib.instance.api.crateApiMediaParamDecryptDecodeFileUnchecked(
  flag: flag,
  path: path,
  key: key,
);

CustomData? decodeFileUncheckedSync({
  required List<int> flag,
  required String path,
  required Key key,
}) => RustLib.instance.api.crateApiMediaParamDecryptDecodeFileUncheckedSync(
  flag: flag,
  path: path,
  key: key,
);

/// 批量解密（无进度）
Future<List<CustomData?>> decodeFilesUncheckedNoProgress({
  required List<int> flag,
  required List<String> paths,
  required Key key,
}) => RustLib.instance.api
    .crateApiMediaParamDecryptDecodeFilesUncheckedNoProgress(
      flag: flag,
      paths: paths,
      key: key,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Key>>
abstract class Key implements RustOpaqueInterface {
  static Key cameraParam() =>
      RustLib.instance.api.crateApiMediaParamDecryptKeyCameraParam();

  @override
  Future<void> dispose();

  static Key fromBytes(List<int> bytes) =>
      RustLib.instance.api.crateApiMediaParamDecryptKeyFromBytes(bytes: bytes);

  static Key fromStr(String s) =>
      RustLib.instance.api.crateApiMediaParamDecryptKeyFromStr(s: s);

  static Key fromStrBytes(List<int> bytes) => RustLib.instance.api
      .crateApiMediaParamDecryptKeyFromStrBytes(bytes: bytes);
}

@freezed
sealed class CustomData with _$CustomData {
  const CustomData._();

  const factory CustomData.invalid() = CustomData_Invalid;
  const factory CustomData.valid(Uint8List field0) = CustomData_Valid;
}
