// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'structs/common.dart';
import 'structs/theme.dart';

Future<ThemeConfigWrapper> deserializeThemeConfig({required List<int> value}) =>
    RustLib.instance.api.crateSerdeConfigDeDeserializeThemeConfig(value: value);
