// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `custom`, `custom`, `fmt`, `fmt`, `fmt`

class Error {
  final BigInt column;
  final BigInt line;
  final ErrorCode code;

  const Error({required this.column, required this.line, required this.code});

  static Future<Error> fromCode({required ErrorCode code}) =>
      RustLib.instance.api.crateMediaParamErrorErrorCode(code: code);

  static Future<Error> syntax({
    required ErrorCode code,
    required BigInt line,
    required BigInt column,
  }) => RustLib.instance.api.crateMediaParamErrorErrorSyntax(
    code: code,
    line: line,
    column: column,
  );

  @override
  int get hashCode => column.hashCode ^ line.hashCode ^ code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Error &&
          runtimeType == other.runtimeType &&
          column == other.column &&
          line == other.line &&
          code == other.code;
}

@freezed
sealed class ErrorCode with _$ErrorCode {
  const ErrorCode._();

  const factory ErrorCode.expectedSomeValue() = ErrorCode_ExpectedSomeValue;
  const factory ErrorCode.expectedSomeIdent() = ErrorCode_ExpectedSomeIdent;
  const factory ErrorCode.invalidNumber() = ErrorCode_InvalidNumber;
  const factory ErrorCode.numberOutOfRange() = ErrorCode_NumberOutOfRange;
  const factory ErrorCode.invalidUnicodeCodePoint() =
      ErrorCode_InvalidUnicodeCodePoint;
  const factory ErrorCode.expectedDoubleQuote() = ErrorCode_ExpectedDoubleQuote;
  const factory ErrorCode.eofWhileParsingString() =
      ErrorCode_EofWhileParsingString;
  const factory ErrorCode.controlCharacterWhileParsingString() =
      ErrorCode_ControlCharacterWhileParsingString;
  const factory ErrorCode.invalidEscape() = ErrorCode_InvalidEscape;
  const factory ErrorCode.loneLeadingSurrogateInHexEscape() =
      ErrorCode_LoneLeadingSurrogateInHexEscape;
  const factory ErrorCode.unexpectedEndOfHexEscape() =
      ErrorCode_UnexpectedEndOfHexEscape;
  const factory ErrorCode.keyMustBeAString() = ErrorCode_KeyMustBeAString;
  const factory ErrorCode.floatKeyMustBeFinite() =
      ErrorCode_FloatKeyMustBeFinite;
  const factory ErrorCode.idMapKeyMustBeAnInteger() =
      ErrorCode_IdMapKeyMustBeAnInteger;
  const factory ErrorCode.expectedNumericKey() = ErrorCode_ExpectedNumericKey;
  const factory ErrorCode.eofWhileParsingObject() =
      ErrorCode_EofWhileParsingObject;
  const factory ErrorCode.expectedColon() = ErrorCode_ExpectedColon;
  const factory ErrorCode.expectedColonAtStart() =
      ErrorCode_ExpectedColonAtStart;
  const factory ErrorCode.expectedObjectCommaOrEnd() =
      ErrorCode_ExpectedObjectCommaOrEnd;
  const factory ErrorCode.trailingComma() = ErrorCode_TrailingComma;
  const factory ErrorCode.eofWhileParsingIdMap() =
      ErrorCode_EofWhileParsingIdMap;
  const factory ErrorCode.eofWhileParsingArray() =
      ErrorCode_EofWhileParsingArray;
  const factory ErrorCode.expectedArrayCommaOrEnd() =
      ErrorCode_ExpectedArrayCommaOrEnd;
  const factory ErrorCode.eofWhileParsingValue() =
      ErrorCode_EofWhileParsingValue;
  const factory ErrorCode.trailingCharacters() = ErrorCode_TrailingCharacters;
  const factory ErrorCode.recursionLimitExceeded() =
      ErrorCode_RecursionLimitExceeded;
  const factory ErrorCode.message(String field0) = ErrorCode_Message;
}
