// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EmptyMap`, `Int`, `StringOptionMap`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `deref_mut`, `deref`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `as_bool`, `as_i64`, `new`

Map<PlatformInt64, bool> convertToBoolIdMap(IdMapBool map) =>
    RustLib.instance.api.crateMediaParamExtTypeConvertToBoolIdMap(map: map);

Map<PlatformInt64, PlatformInt64> convertToIntIdMap(IdMapI64 map) =>
    RustLib.instance.api.crateMediaParamExtTypeConvertToIntIdMap(map: map);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AdaptiveArray < Interactions >>>
abstract class AdaptiveArrayInteractions implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AdaptiveArray < NikkiDIY >>>
abstract class AdaptiveArrayNikkiDiy implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AdaptiveArray < i64 >>>
abstract class AdaptiveArrayI64 implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IdMap < bool >>>
abstract class IdMapBool implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IdMap < i64 >>>
abstract class IdMapI64 implements RustOpaqueInterface {}
